### PR TITLE
Update grafana and use preinstalled helm

### PR DESCRIPTION
**Pull request by martell**
READY

### CODE REVIEW

**Comment by martell** [comment]
Tested this last night and everything is working

```
cadvisor-8cf5z                                              1/1       Running   0          19h
cadvisor-bjmxs                                              1/1       Running   0          19h
dashboard-grafana-5d864656b8-sjtbn                          1/1       Running   0          19h
monitoring-prometheus-kube-state-metrics-6bc48cd465-p76fz   1/1       Running   0          19h
monitoring-prometheus-node-exporter-gl9th                   1/1       Running   0          19h
monitoring-prometheus-node-exporter-kdlf5                   1/1       Running   0          19h
monitoring-prometheus-pushgateway-d4f679b7-trcgm            1/1       Running   0          19h
monitoring-prometheus-server-75bb797794-js8kb               2/2       Running   0          19h
```

Same instructions apply and it picks up the Prometheus metrics.
v5 looks like a very nice visual refresh I must say.

This is now ready for merging.

**Comment by jackfrancis** [comment]
@ritazh FYI, may I lean on you for comment/approval?

**Comment by ritazh** [comment]
LGTM
Confirm this works on 1.8.11, 1.9.6, 1.10.0

**Comment by martell** [comment]
Thanks for reviewing and confirming @ritazh

**Pull request merged**
