### PR TITLE
remove docker dependency from hyperkube extract

### PR DESCRIPTION
**Pull request by jessfraz**
doing this in parts til I find the dns issue in https://github.com/Azure/acs-engine/pull/2973

### CODE REVIEW

**Comment by jessfraz** [comment]
https://jenkins.azure-containers.io/view/acs-engine/job/k8s-containerd/36/console

**Comment by jessfraz** [comment]
thanks @CecileRobertMichon

**Comment by karataliu** [comment]
Seems 'img pull' has some dependency on it, shall we turn to 'docker pull' if runtime is set to docker?

**Comment by jessfraz** [comment]
it has a dep on runc which docker does as well so its relative, there is no point in having a different command that is only tested under certain scenarios it would give more likely hood for failure

**Pull request merged**
