### PR TITLE
update to k8s v1.8.1

### PR DESCRIPTION
**Pull request by lachie83**

### CODE REVIEW

**Comment by lachie83** [comment]
@JiangtianLi Can you cut the windows release?

**Comment by JiangtianLi** [comment]
@lachie83 Sure. Doing now.

**Comment by JiangtianLi** [comment]
@lachie83 I have built the zip and uploaded to my blob container. It worked fine except that windows container comes up in 2m. So could you change in this PR: https://github.com/Azure/acs-engine/blob/master/parts/kuberneteswindowssetup.ps1#L317  from 5m to 2m?

**Comment by lachie83** [comment]
@JiangtianLi done. Can we get this merged?

**Comment by lachie83** [comment]
Also ran upstream conformance tests against this cluster and they passed

**Comment by JiangtianLi** [comment]
@lachie83 I am going to upload win zip to prod soon. So pls hold for windows test.

**Comment by JiangtianLi** [comment]
@lachie83  upload done. I'll kick off a windows test.

**Pull request merged**
