### PR TITLE
Bump k8s/client-go to 6.0.0

### PR DESCRIPTION
**Pull request by adelina-t**
In an effort to allow kubetest to use acs-engine to spawn k8s clusters we need client-go bumped to 6.0.0 to avoid dependency conflicts. This effort goes to running k8s e2e tests on azure.

### CODE REVIEW

**Comment by jackfrancis** [comment]
Thanks for beginning this effort @adelina-t! It's not as simple as bumping to 6.0 unfortunately:

`[ERROR]	Failed to generate lock file: Generating lock produced conflicting versions of github.com/onsi/gomega. import (dcabb60a477c2b6f456df65037cb6708210fbb02), testImport ()`

**Comment by adelina-t** [comment]
@jackfrancis glide was really uncooperative, so I had to pin down gomega and ginkgo in glide.yaml or else they don't play nice with the k8s dependencies.

**Comment by jackfrancis** [comment]
@adelina-t To speak to the lack of movement on this PR, we're still trying to reconcile how to make this acs-engine change without breaking the dependency graph of AKS+acs-engine. Thanks for your patience, hopefully you are able to continue testing against this branch.

**Comment by adelina-t** [comment]
@jackfrancis I'm working for my fork in the meantime so that's ok ftm. I'm also looking for a way to maybe eliminate the dependency between the two, I'll keep you posted on that end.

**Comment by thomastaylor312** [comment]
Just an update, I got this working with client-go v7.0.0 in #2954

**Comment by jackfrancis** [comment]
@adelina-t Thanks for your patience, we merged support for client-go v7 here (and your PR was a helpful template for that!)

Let me know if there are any remaining gaps to unblock kubetest efforts.

**Comment by test-e2e-win** [comment]
Hi @adelina-t. Thanks for your PR.

I'm waiting for a [Azure](https://github.com/orgs/Azure/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/Azure/people) to skip this step.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by test-e2e-win** [comment]
Hi @adelina-t. Thanks for your PR.

I'm waiting for a [Azure](https://github.com/orgs/Azure/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/Azure/people) to skip this step.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by adelina-t** [comment]
comment test

**Comment by adelina-t** [comment]
test

**Pull request closed without merging**
