### PR TITLE
Use ginkgo as e2e test runner

### LINKED ISSUE #678: Identify good Kubernetes functional test candidate to try out w/Ginkgo
Functional tests are a mixture of Go and shell scripts. We want to try out using [Ginkgo](https://github.com/onsi/ginkgo) as the test runner for both unit and integration/functional/regression tests, which will make tests easier to write, refactor, and reuse.

acceptance criteria:
- Identify an existing Kubernetes functional test that would be a good candidate to quickly spike on with Ginkgo.
- Lay down Ginkgo boilerplate/setup.

### PR DESCRIPTION
**Pull request by seanknox**
Courtesy of @jchauncey, this PR introduces using [Ginkgo](http://onsi.github.io/ginkgo/) as a test runner for e2e tests. 

We want to try out using Ginkgo as the test runner for both unit and integration/functional/regression tests, which will make tests easier to write, refactor, and reuse.

Goals of this PR:
- [x] Identify an existing Kubernetes functional test that would be a good candidate to quickly spike on with Ginkgo.
- [x] Lay down Ginkgo boilerplate/setup.

Fixes #678

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/691)

### CODE REVIEW

**Comment by seanknox** [comment]
@jchauncey This is a great start, thanks for kicking this off. The commits in this PR/branch are the same as the WIP commit in your branch, with a couple minor changes:
- rebased onto latest master
- changed two tests that were failing on my machine to pending (I probably an lacking some sort of setup)
- Re-checked in `vendor/` to use `git config --global core.autocrlf input` to let git manage line endings

I'd like to get this in with the scope as is, no need to add any more tests yet. Let's get the tests added here all passing reliably and then added to CI.

**Comment by jchauncey** [comment]
I still need to add the cluster creation code to these suite. Right now I am just working against a static cluster in my subscription.

**Comment by jchauncey** [comment]
Can we just close this until I can finish up?

**Comment by seanknox** [comment]
@jchauncey We already have a method of provisioning a test cluster. Can we use that for the time being? @dmitsh can speak more about that.

I want to keep this PR as small and focused as possible, if possible.

**Comment by jchauncey** [comment]
@seanknox close this PR in favor of #709

**Comment by seanknox** [comment]
Closing in favor of #709

**Pull request closed without merging**
