### PR TITLE
deploy OpenShift registry-console with openshift-ansible

### PR DESCRIPTION
**Pull request by maxamillion**
Signed-off-by: Adam Miller <admiller@redhat.com>

**What this PR does / why we need it**:
Deploy's OpenShift registry-console with openshift-ansible for OpenShift Container Platform and OpenShift Origin Deployments.

### CODE REVIEW

**Comment by kargakis** [comment]
@maxamillion please rebase on latest master, one of the tests should fail now and require you to check in generated code.

**Comment by maxamillion** [comment]
@kargakis why are we checking in generated code?

**Comment by kargakis** [comment]
@jim-minter and @jackfrancis should know better but from what I remember we
had issues with static validation.

**Comment by jackfrancis** [comment]
@maxamillion checking in validated code unblocked our compilation CI. From a high level I think this can be classified as a // TODO in terms of how to make go-bindata + CI maintainable long-term. Open to any practical ideas. (but let's not functionally block this PR, I reckon)

**Comment by jim-minter** [comment]
lgtm, please merge

**Pull request merged**
