### PR TITLE
enable VMAS + VMSS mixed mode agent pools

### PR DESCRIPTION
**Pull request by jackfrancis**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**If applicable**:
- [ ] documentation
- [ ] unit tests
- [ ] tested backward compatibility (ie. deploy with previous version, upgrade with this branch)

**Release note**:

```
enable VMAS + VMSS mixed mode agent pools
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
cloudprovider config on a mixed mode cluster master:

```
azureuser@k8s-master-42544108-0:~$ sudo cat /etc/kubernetes/azure.json 
{
    "cloud":"AzurePublicCloud",
    "tenantId": "redacted",
    "subscriptionId": "redacted",
    "aadClientId": "redacted",
    "aadClientSecret": "redacted",
    "resourceGroup": "kubernetes-westcentralus-9413",
    "location": "westcentralus",
    "vmType": "vmss",
    "subnetName": "k8s-subnet",
    "securityGroupName": "k8s-master-42544108-nsg",
    "vnetName": "k8s-vnet-42544108",
    "vnetResourceGroup": "",
    "routeTableName": "k8s-master-42544108-routetable",
    "primaryAvailabilitySetName": "",
    "primaryScaleSetName": "k8s-agentpool1-42544108-vmss",
    "cloudProviderBackoff": false,
    "cloudProviderBackoffRetries": 0,
    "cloudProviderBackoffExponent": 0,
    "cloudProviderBackoffDuration": 0,
    "cloudProviderBackoffJitter": 0,
    "cloudProviderRatelimit": false,
    "cloudProviderRateLimitQPS": 0,
    "cloudProviderRateLimitBucket": 0,
    "useManagedIdentityExtension": false,
    "useInstanceMetadata": true,
    "providerVaultName": "",
    "providerKeyName": "k8s",
    "providerKeyVersion": ""
}
```

**Comment by JunSun17** [comment]
azureuser@k8s-master-42544108-0:~$ sudo cat /etc/kubernetes/azure.json 
{
    "cloud":"AzurePublicCloud",
    "tenantId": "redacted",
    "subscriptionId": "redacted",
    "aadClientId": "redacted",
    "aadClientSecret": "redacted",
    "resourceGroup": "kubernetes-westcentralus-9413",
    "location": "westcentralus",
    **"vmType": "vmss",**
    "subnetName": "k8s-subnet",
    "securityGroupName": "k8s-master-42544108-nsg",
    "vnetName": "k8s-vnet-42544108",
    "vnetResourceGroup": "",
    "routeTableName": "k8s-master-42544108-routetable",
    **"primaryAvailabilitySetName": "",
    "primaryScaleSetName": "k8s-agentpool1-42544108-vmss",**
    "cloudProviderBackoff": false,
    "cloudProviderBackoffRetries": 0,
    "cloudProviderBackoffExponent": 0,
    "cloudProviderBackoffDuration": 0,
    "cloudProviderBackoffJitter": 0,
    "cloudProviderRatelimit": false,
    "cloudProviderRateLimitQPS": 0,
    "cloudProviderRateLimitBucket": 0,
    "useManagedIdentityExtension": false,
    "useInstanceMetadata": true,
    "providerVaultName": "",
    "providerKeyName": "k8s",
    "providerKeyVersion": ""
}

I wonder dd we have the right support for mixed/multiple models. The azure.json is now hard coded to take only one value of either primaryScaleSetName or primaryAvailabilitySetName, and only one value of vmType is allowed.

**Comment by feiskyer** [comment]
> I wonder if we have the right support for mixed/multiple models. The azure.json is now hard coded to take only one value of either primaryScaleSetName or primaryAvailabilitySetName, and only one value of vmType is allowed.

Yep, each should work for mixed cluster. Another choice is standard LB, which supports all nodes to LB backends.

**Comment by CecileRobertMichon** [comment]
@francis do we still want this in aks-engine?

**Pull request closed without merging**
