### PR TITLE
"prereqs" dependency is missing from the "build" rule in the Makefile

### PR DESCRIPTION
**Pull request by jsilberm**
**What this PR does / why we need it**:

'make build' does not complete cleanly without manual intervention
pkg/acsengine/fileloader.go:3: running "go-bindata": exec: "go-bindata": executable file not found in $PATH
The 'prereqs' dependency is missing from the 'build' rule.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

https://github.com/Azure/acs-engine/issues/880

**Special notes for your reviewer**:

**Release note**:

```release-note
```

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/881)

### CODE REVIEW

**Comment by jsilberm** [comment]
GTG?

**Comment by jsilberm** [comment]
Tried to make everything easier and more consistent by updating the `acsengine.md` file to reflect the simplicity.   Less is more.

**Comment by amanohar** [comment]
cc: @colemickens

**Comment by jsilberm** [comment]
@rjtsdl @seanknox :  I would humbly suggest that your review orientation and reference should be external rather than MS internal/CI.   If you're trying to encourage acs-engine adoption, you should try to bias towards simplicity.   As a contributor, I'm less interested in internal CI and more interested in using the product as quickly as possible.  (I've hit this problem a number of times, otherwise I wouldn't have opened the PR).   Thanks.

**Comment by seanknox** [comment]
Hi @jsilberm, I hear you and @rjtsdl is correct, though let me attempt to explain a bit more why developer bootstrapping is viewed as a one off task.

1. Project dependencies (via glide) due not change very often.
1. As a developer, I want to minimal number of things to run when building the project (speed).

That's why we don't run to attempt to re-install developer dependencies every time on `make build`. You should be able run `make prereqs` once and start using the project.

**Pull request closed without merging**
