### PR TITLE
add haproxy validation in dcos

### PR DESCRIPTION
**Pull request by rjtsdl**
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/396)

### CODE REVIEW

**Comment by rjtsdl** [comment]
@acs-bot test this please

**Comment by colemickens** [comment]
Does this catch stuff the other service didn't catch?

**Comment by rjtsdl** [comment]
@colemickens , I am not sure what are your referring for "other service".

This PR is to enrich the existing deployment validation for dcos. I noticed that the current validation only verify 3 instance is running, without even to ping the service at all. So this PR will catch the stuff like, if the marathon-lb is working well, which is not covered by current validation.

**Comment by colemickens** [comment]
Oops. I totally misremembered! Ignore me!

**Pull request merged**
