### PR TITLE
Fix #116 - Name the `kubelet` container when starting

### LINKED ISSUE #116: [kubernetes] systemctl stop kubelet.service
Unable to stop kubelet.service via systemctl on k8s master node.

```
> systemctl stop kubelet.service
> systemctl status kubelet.service
Nov 22 01:29:19 k8s-master-1479775666-0 systemd[1]: Stopping Kubelet...
Nov 22 01:29:19 k8s-master-1479775666-0 docker[26894]: Error response from daemon: No such container: kubelet

```

Should be a fairly easy fix if you name the docker image when starting:
https://github.com/Azure/acs-engine/blob/master/parts/kubernetesmastercustomdata.yml#L323

### PR DESCRIPTION
**Pull request by jpoon**
Fixes #116 by naming the container. Sorry about breaking it before @colemickens. This time around, I deployed, tested, and validated this change on my own cluster and it all works fine.

### CODE REVIEW

**Comment by jpoon** [comment]
Accidentally closed this. 

```
jason@k8s-master-25142663-0:~$ systemctl stop kubelet.service
jason@k8s-master-25142663-0:~$ systemctl status kubelet.service
● kubelet.service - Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2016-12-15 20:00:38 UTC; 5s ago
  Process: 11965 ExecStop=/usr/bin/docker stop -t 2 kubelet (code=exited, status=0/SUCCESS)
 Main PID: 5568 (code=exited, status=143)

Dec 15 20:00:23 k8s-master-25142663-0 docker[5568]: I1215 20:00:23.419937    6170 conversion.go:134] failed to handle multiple d
Dec 15 20:00:23 k8s-master-25142663-0 docker[5568]: I1215 20:00:23.420020    6170 conversion.go:134] failed to handle multiple d
Dec 15 20:00:33 k8s-master-25142663-0 docker[5568]: I1215 20:00:33.469447    6170 conversion.go:134] failed to handle multiple d
Dec 15 20:00:33 k8s-master-25142663-0 docker[5568]: I1215 20:00:33.469467    6170 conversion.go:134] failed to handle multiple d
Dec 15 20:00:37 k8s-master-25142663-0 systemd[1]: Stopping Kubelet...
Dec 15 20:00:38 k8s-master-25142663-0 docker[11965]: kubelet
Dec 15 20:00:38 k8s-master-25142663-0 systemd[1]: kubelet.service: Main process exited, code=exited, status=143/n/a
Dec 15 20:00:38 k8s-master-25142663-0 systemd[1]: Stopped Kubelet.
Dec 15 20:00:38 k8s-master-25142663-0 systemd[1]: kubelet.service: Unit entered failed state.
Dec 15 20:00:38 k8s-master-25142663-0 systemd[1]: kubelet.service: Failed with result 'exit-code'.
```

Docker stop is successful. Not sure why `kubelet.service` reports a failed status though.

**Comment by jpoon** [comment]
Running through the `start/stop` cycle again worked without issue.

```
jason@k8s-master-25142663-0:~$ systemctl status kubelet.service
● kubelet.service - Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Thu 2016-12-15 21:06:48 UTC; 3s ago
  Process: 2879 ExecStop=/usr/bin/docker stop -t 2 kubelet (code=exited, status=0/SUCCESS)
  Process: 2875 ExecStart=/usr/bin/docker run --name=kubelet --net=host --pid=host --privileged --volume=/dev:/dev --volume=/sys
  Process: 2872 ExecStartPre=/bin/mount --make-shared /var/lib/kubelet (code=exited, status=0/SUCCESS)
  Process: 2863 ExecStartPre=/bin/mount --bind /var/lib/kubelet /var/lib/kubelet (code=exited, status=0/SUCCESS)
  Process: 2858 ExecStartPre=/bin/sed -i s|<kubernetesHyperkubeSpec>|gcr.io/google_containers/hyperkube-amd64:v1.4.6|g /etc/kube
  Process: 2856 ExecStartPre=/bin/mkdir -p /var/lib/kubelet (code=exited, status=0/SUCCESS)
 Main PID: 2875 (code=killed, signal=TERM)

Dec 15 21:06:37 k8s-master-25142663-0 systemd[1]: Starting Kubelet...
Dec 15 21:06:48 k8s-master-25142663-0 systemd[1]: Started Kubelet.
Dec 15 21:06:48 k8s-master-25142663-0 systemd[1]: Stopping Kubelet...
Dec 15 21:06:48 k8s-master-25142663-0 docker[2879]: kubelet
Dec 15 21:06:48 k8s-master-25142663-0 systemd[1]: Stopped Kubelet.
```

**Comment by colemickens** [comment]
I don't know why this didn't occur to me before, but I think the simpler fix is flat out removing the ExecStop line. In that case, systemd should treat it as a normal process and kill off the instance of `docker run`. I'm also wondering if that will avoid hitting the "exit code 143" case that you hit today.

**Comment by jpoon** [comment]
I'd slightly prefer the `ExecStop` method as it's a tad more graceful giving kubelet a couple seconds to shutdown before killing the process. Researching the 143 error, it seems expected as the exit code implies the application was killed with a SIGTERM.

The end result of both cases is the same and as the impact is fairly minimal in both regard, let me know if you want me to update the PR deleting the `ExecStop` altogether.

**Comment by anhowe** [comment]
@jpoon - sorry for the delay on this.  We are reviewing now.  Please resolve the conflicts, and add the removal execstop from @colemickens .

**Comment by jpoon** [comment]
I've updated the PR removing the `ExecStop` but still naming the `kubelet` container. I also updated the `kubernetes_expected.json` but it's not clear to me how to run these tests.

**Comment by colemickens** [comment]
Please run `make ci` to run the appropriate tests and verifications.

If you're on Windows, please read the Makefile and run the equivalent steps. Thanks.

I'll review and test this in a bit and get it merged.

**Comment by jpoon** [comment]
@colemickens thanks. had to change a few things, git push -f'd and `make ci` looks all good.

**Comment by colemickens** [comment]
If you remove the ExecStop, then naming the container isn't necessary.

As is, this is very problematic. If you stop kubelet, it can not be restarted because `--rm` is not present on the `docker run` invocation.

I don't know what `--rm` does if systemd stops the container running in FG rather than exitting normally on it's own.

Can we just remove the `--name` as well?

**Comment by colemickens** [comment]
This doc recommends something different. Can you follow the recommendations here: https://docs.docker.com/engine/admin/host_integration/

Seems the most appropriate thing to do.

**Comment by jpoon** [comment]
@colemickens that was dumb -- sorry about that last commit; just brainlessly edited it. 

i added the `execstoppost` which should be sufficient for post-mortem clean up.

**Comment by jpoon** [comment]
Fixed merge conflicts through rebase and `push -f`. Changes are the same as last revision. I tested the changes prior to the rebase (ie. 13 days ago) and k8s came up fine.

**Comment by colemickens** [comment]
Please give the container 10 seconds to stop. 2 is too few and it still winds up exiting uncleanly.

Then I'll merge. Thanks @jpoon !

**Comment by jpoon** [comment]
@colemickens it has been done.

**Pull request merged**
