### PR TITLE
enable typha and add horizontal autoscaler

### PR DESCRIPTION
**Pull request by briansan**
**What this PR does / why we need it**:
enables Typha for Calico and also adds a horizontal autoscaler for it

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
None

**Special notes for your reviewer**:
None

**Release note**:
NONE

### CODE REVIEW

**Comment by jackfrancis** [comment]
@feiskyer FYI

**Comment by jackfrancis** [comment]
Hi @briansan as implemented, this only enables Typha for k8s 1.12 and above. Which versions of k8s should this implementation of Typha work with?

Thanks!

**Comment by feiskyer** [comment]
LGTM.

@caseydavenport I think this would work since v1.7?

**Comment by briansan** [comment]
hi @jackfrancis, what makes you say so? Typha should be supported on all version of Kubernetes

**Comment by jackfrancis** [comment]
@briansan We have version-specific implementations of the calico addon (see the version subdirs in the `parts/k8s/adddons` directory. I'm happy to do the work, we just need precise clarification of which versions of calico support the manifest definition additions as-is in the PR.

**Comment by jackfrancis** [comment]
@briansan I noticed that the `calico-typha` Deployment still has `0` replicas. Is that intentional?

**Comment by briansan** [comment]
@jackfrancis one of the goals of this PR is to set up an autoscaler which handles setting the replica count based on the number of k8s nodes

**Comment by jackfrancis** [comment]
@briansan Got it, thanks!

**Pull request merged**
