### PR TITLE
fix(e2e): run bootstrap/build in e2e.sh

### PR DESCRIPTION
**Pull request by seanknox**
Fix for regression tests still running on Jenkins

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/1158)

### CODE REVIEW

**Comment by seanknox** [comment]
> we need test/acs-engine-test.sh for regression.

Regression jobs on Jenkins + service jobs were updated last night to refer to `test/e2e.sh`. Is there something else that explicitly refers to `test/acs-engine-test.sh`?

**Comment by dmitsh** [comment]
Could you clarify what is CIRCLE_BUILD_NUM? Do we need to set it for Jenkins builds?

**Comment by seanknox** [comment]
> Could you clarify what is CIRCLE_BUILD_NUM? Do we need to set it for Jenkins builds?

Changed so BUILD_NUM is how files in `test/` will refer to the build. On Circle CI we overwrite with `CIRCLE_BUILD_NUM`.

**Comment by dmitsh** [comment]
thanks!

**Pull request merged**
