### PR TITLE
enable kubernetes cloudprovider backoff on agent nodes

### LINKED ISSUE #981: cloudprovider backoff is only configured on master
Is this intentional? I thought there had been throttling issues just from the nodes querying too often as well?

### PR DESCRIPTION
**Pull request by jackfrancis**
**What this PR does / why we need it**:

Enables kubernetes cloudprovider backoff functionality on agent nodes

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #981 

**Special notes for your reviewer**:

- moved provision.sh variables ordinality around to accommodate agent usage
- added backoff vars to agent resources template
- re-ordered backoff vars in master resources template to accommodate changes

**Release note**:

```enable kubernetes cloudprovider backoff on agent nodes
```

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/988)

### CODE REVIEW

**Comment by seanknox** [comment]
LGTM. Are there *any* opportunities for unit tests here?

**Comment by jackfrancis** [comment]
The implications are more holistic, so E2E tests should really be in play to confirm that the particulars of a configuration objective are realized at the end state (a deployed cluster with config values).

Perhaps @colemickens can comment on some go-bindata functional (for lack of a better word) style test approaches.

**Comment by seanknox** [comment]
Sounds good. Don't hold up on account of this, go ahead and merge if you're ready.

**Comment by seanknox** [comment]
@acs-bot test this please

**Pull request merged**
