### PR TITLE
remove extraneous sed statements for mooncake configs

### PR DESCRIPTION
**Pull request by tariq1890**
Remove sed statements that are no longer required.

### CODE REVIEW

**Comment by tariq1890** [comment]
@andyzhangx These seds should not longer be required, once these changes go into master.

https://github.com/Azure/acs-engine/pull/4218/files#diff-728b4e2bd2c87eb4c387b23ef082ddb8R30

We have made ipmasq agent image configurable through code. The defaults.go logic will ensure that the right Image base used for Mooncake scenarios.

**Comment by andyzhangx** [comment]
/hold
Since this PR depends on #4218

**Comment by andyzhangx** [comment]
@tariq1890 do you know how can I set `ipmasq agent image` on mooncake if #4218 is merged?

**Comment by tariq1890** [comment]
@andyzhangx if `ip-masq-agent` addon in enabled and you don't specify that in the  PR, it'll use the "k8s.gcr.io/gcr.azk8s.cn/google_containers/(depending on location) + ip-masq-agent-amd64:v2.0.0" image by default.

**Pull request closed without merging**
