### PR TITLE
Update to Azure-CNI v1.0.14

### PR DESCRIPTION
**Pull request by PatrickLang**
**What this PR does / why we need it**:

Azure-CNI v1.0.14 has fixes needed for Windows https://github.com/Azure/azure-container-networking/pull/268 to fix outbound NAT

```release-note
Update to Azure CNI v1.0.14
```

### CODE REVIEW

**Comment by PatrickLang** [comment]
This fails because azure-cni hasn't been uploaded to the acs-engine mirror. @jackfrancis can you upload it?

**Comment by PatrickLang** [comment]
@daschott


Pod -> Service connectivity seems ok:

```patrick@planglx1:~/cni14/_output/plang1128/kubeconfig$ kubectl get pod -o wide
NAME                           READY   STATUS    RESTARTS   AGE   IP            NODE           NOMINATED NODE
whoami-1803-65c957dcd7-h54cx   1/1     Running   0          15m   10.240.0.17   35483k8s9000   <none>
whoami-1803-65c957dcd7-t5c4p   1/1     Running   0          16m   10.240.0.39   35483k8s9001   <none>
whoami-1803-65c957dcd7-vppc6   1/1     Running   0          15m   10.240.0.15   35483k8s9000   <none>
whoami-1803-65c957dcd7-zdlfs   1/1     Running   0          15m   10.240.0.42   35483k8s9001   <none>

patrick@planglx1:~/cni14/_output/plang1128/kubeconfig$ kubectl exec -t whoami-1803-65c957dcd7-zdlfs curl http://10.240.0.17:8080
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    58  100    58    0     0   I'm whoami-1803-65c957dcd7-h54cx running on windows/amd64
  58      0  0:00:01 --:--:--  0:00:01 58000

patrick@planglx1:~/cni14/_output/plang1128/kubeconfig$ kubectl exec -t whoami-1803-65c957dcd7-zdlfs curl http://ogfg.link
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    76  100    76    0     0     76      0  0:00:01 --:--:--  0:00:01  4750
<html><body>Nothing to see here. I'm just a lonely API server.</body></html>

patrick@planglx1:~/cni14$ kubectl get svc
NAME              TYPE           CLUSTER-IP    EXTERNAL-IP    PORT(S)        AGE
kubernetes        ClusterIP      10.0.0.1      <none>         443/TCP        28m
whoami-1803-svc   LoadBalancer   10.0.208.79   13.77.160.29   80:30593/TCP   17m

patrick@planglx1:~/cni14$ kubectl exec -t whoami-1803-65c957dcd7-zdlfs curl http://10.0.208.79
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    58  100    58    0     0     58      0  0:00:01 --:--:--  0:00:01  3625
I'm whoami-1803-65c957dcd7-vppc6 running on windows/amd64
```

**Comment by jackfrancis** [comment]
@PatrickLang I uploaded the artifact and ran a successful E2E. I think circleci is confused, re-running the suite.

**Pull request merged**
