### PR TITLE
Default output of acs-engine updated in documentation

### PR DESCRIPTION
**Pull request by DonMartin76**
(No code changes, just a change in the docs).

Despite having switched off rebase, something is off in my repo, I'll have to refork it.

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/652)

### CODE REVIEW

**Comment by colemickens** [comment]
@acs-bot test this please

**Comment by colemickens** [comment]
@acs-bot test this please

**Comment by colemickens** [comment]
@acs-bot test this please

**Comment by colemickens** [comment]
@acs-bot test this please

**Comment by colemickens** [comment]
@acs-bot test this please

**Comment by colemickens** [comment]
@acs-bot test this please

**Comment by dmitsh** [comment]
@acs-bot test this please

**Comment by dmitsh** [comment]
@DonMartin76 please rebase

**Comment by colemickens** [comment]
@acs-bot test this please

**Comment by colemickens** [comment]
@acs-bot test this please

**Comment by dmitsh** [comment]
@acs-bot test this please

**Pull request merged**
