### PR TITLE
Fix DCOS 1.8.8 download URL

### PR DESCRIPTION
**Pull request by raveeram**

### CODE REVIEW

**Comment by raveeram** [comment]
@wangtt03 to make sure updating the URL is okay for china cloud

**Comment by colemickens** [comment]
Do you need to update the testdata files too? `./scripts/rebase.sh` is your friend.

**Comment by raveeram** [comment]
@colemickens i should install bash on windows and starting using that :). Running a batch file of mine currently. Will update PR with tests in a bit.

**Comment by colemickens** [comment]
@raveeram If you have docker `make devenv` is your friend too :) Also ensures you're on the right version of Go, etc.

**Comment by raveeram** [comment]
@colemickens Ahh I see, I'll try that out now. Updated tests.

**Pull request merged**
