### PR TITLE
Fix the network blip caused during network creation/deletion

### PR DESCRIPTION
**Pull request by madhanrm**
**What this PR does / why we need it**:
The changes in this PR will fix the network blip/disconnection caused during the first POD creation (very much visible to customers logged into the windows node via RDP)
This change has a dependency with the latest azure cni 1.0.7 ( I can undo this change, if that is already being taken care of)
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**If applicable**:
- [ ] documentation
- [ ] unit tests
- [ ] tested backward compatibility (ie. deploy with previous version, upgrade with this branch)

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
Thanks @madhanrm! I have a separate PR w/ Azure CNI 1.0.7 here:

https://github.com/Azure/acs-engine/pull/3433

Do these changes depend on it?

**Comment by madhanrm** [comment]
@jackfrancis  Yes, this change depend on azure cni 1.0.7

**Comment by jackfrancis** [comment]
@madhanrm as Azure CNI 1.0.7 has merged, you can fix the conflict by simply removing the update to defaults.go

**Comment by madhanrm** [comment]
@jackfrancis  Done

**Comment by jackfrancis** [comment]
@PatrickLang for your eyes

**Comment by PatrickLang** [comment]
@jackfrancis or @CecileRobertMichon can you merge?

**Pull request merged**
