### PR TITLE
remove StorageProfile defaults in v20170701

### LINKED ISSUE #1117: regression on 2017-07-01
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
issue
---

**What version of acs-engine?**:
05871f14ea21b33889db0d4a82f2464608ea96d3
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
DockerCE

**What happened**:
StorageProfile used to be default to ManagedDisks. Now it's StorageAccounts

**What you expected to happen**:
StorageProfile should be ManagedDisks

**How to reproduce it** (as minimally and precisely as possible):
cannot say when the regression was introduced. but RP is using a fairly old version of acs-engine.

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by rjtsdl**
**What this PR does / why we need it**:
DockerCE has different default setup. So remove it, so the setDefaultValue function in generateTemplate would populate the default

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1117 

**Special notes for your reviewer**:

**Release note**:

```release-note
```

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/1119)

### CODE REVIEW

**Comment by rjtsdl** [comment]
@acs-bot test this please

**Comment by rjtsdl** [comment]
@acs-bot test this please

**Comment by rjtsdl** [comment]
@acs-bot test this please

**Comment by seanknox** [comment]
@acs-bot test this please

**Comment by rjtsdl** [comment]
@acs-bot test this please

**Comment by rjtsdl** [comment]
@acs-bot test this please

**Comment by rjtsdl** [comment]
@acs-bot test this please

**Comment by weinong** [comment]
@acs-bot test this please

**Comment by dmitsh** [comment]
@acs-bot test this please

**Pull request merged**
