### PR TITLE
update openshift validations to match patterns

### PR DESCRIPTION
**Pull request by pweil-**
add validate method for OpenShift config, refactor test case to use table driven tests, update test case to ensure actual error messages are checked, add test for OpenShift config

@jim-minter @CecileRobertMichon @jackfrancis

### CODE REVIEW

**Comment by jim-minter** [comment]
bump

**Comment by pweil-** [comment]
> bump

forgot about this one.  Will rebase :smile:

**Comment by pweil-** [comment]
rebased PTAL @kargakis @jim-minter

**Comment by kargakis** [comment]
lgtm

**Comment by jim-minter** [comment]
@CecileRobertMichon please merge

**Comment by jim-minter** [comment]
@CecileRobertMichon bump :)

**Comment by CecileRobertMichon** [comment]
@jim-minter the openshift test failed, can you please take a look?

**Comment by kargakis** [comment]
```
        "code": "VMExtensionProvisioningTimeout",

        "message": "Provisioning of VM extension 'cse-agent-0' has timed out. Extension installation may be taking too long, or extension status could not be obtained."
```
Seems a common error in azure

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/error-messages
https://stackoverflow.com/questions/44463477/how-to-diagnose-an-intermittent-azure-custom-script-extension-hang

**Pull request merged**
