### PR TITLE
Extensions support

### PR DESCRIPTION
**Pull request by RobBagby**
**What this PR does / why we need it**:
This PR adds extension support to acs-engine.  Extensions provide an easy way for acs-engine users to add pre-packaged functionality into their cluster.  For example, an extension could configure a monitoring solution on an ACS cluster.  Other examples include: OMS, Helm, Helm charts, Deis Workflow, Sysdig, Vamp and more.  The user would not need to know the details of how to install the monitoring solution.  Rather, the user would simply add the extension into the extensionsProfile section of the template and the masterProfile as below:

```jacascript
{
  "masterProfile": {
      "count": 3,
      "dnsPrefix": "dnsprefix",
      "vmSize": "Standard_D2_v2",
      "osType": "Linux",
      "firstConsecutiveStaticIP": "10.240.255.5",
      "extensions": [
        { 
          "name": "hello-world-k8s"
        }
     ]
  },
  "extensionsProfile": [
    {
        "name": "hello-world-k8s",
        "version": "v1",
        "extensionParameters": "parameters"
    }
  ]
}
```

**How are extensions implemented**
Extensions take advantage of the following ARM constructs: Linked Templates, Custom Script Extensions.  A typical extension would consist of the following files:

|File Name|Description|
|-----------------------------|---|
|template.json               |The ARM template used to deploy the extension|
|template-link.json          |The ARM template snippet which will be injected into azuredeploy.json to call template.json|
|EXTENSION-NAME.sh           |The script file that will execute on the VM itself via Custom Script Extension to perform installation of the extension|
|supported-orchestrators.json |Defines what orchestrators are supported by the extension (Swarm, Dcos, or Kubernetes).  This will be extended in the future to contain more than just supported orchestrators.  Dependencies between extensions, for example will be added here.|

**MVP**
The minimum viable product for extensions will run a script via the above ARM constructs on a master node.  This will work for the scenarios where the extension is deploying a container/pod/daemonset/etc.  Future versions will allow for running scripts on one or more agents in agent pools.

**Extensions**
Although this PR only contains 2 hello world extensions, several extensions have been written and will be added by subsequent PRs.  The extensions written include:
- OMS for Kubernetes
- Sysdig for Kubernetes
- Helm for Kubernetes (installs Helm)
- VAMP for DC/OS

**Testing Extensions**
Because extensions will exist in the GitHub repo, a "rootURL" property exists for an extension in the extensionsProfile:
```javascript
"extensionsProfile": [
      { 
        "name": "hello-world-k8s", 
        "version": "v1",
        "rootURL": "https://bagbyimages.blob.core.windows.net:443/"
      }
    ],
```
This allows developers to place their in-development extensions in any http accessible location for testing.  If/when this PR is accepted, another pull request will be issued to remove the rootURL in the examples in the examples/extensions directory. 

**Documentation**
There is documentation on the extensions in docs/extensions.md

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/687)

### CODE REVIEW

**Comment by skasturi** [comment]
This is awesome. We need this for DC/OS as well. Any plans for it?

**Comment by JackQuincy** [comment]
currently adding this to DC/OS isn't on the our teams TODO list. but PRs are welcome

**Comment by shrutir25** [comment]
@RobBagby - please rebase and submit

**Comment by JackQuincy** [comment]
looks like @RobBagby isn't maintaining this I'm going to start a new PR based on this later today after rebasing etc.

**Pull request closed without merging**
