### PR TITLE
optimized tests

### PR DESCRIPTION
**Pull request by dmitsh**
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/604)

### CODE REVIEW

**Comment by dmitsh** [comment]
@acs-bot test this please

**Comment by JackQuincy** [comment]
Can you put more comments about what the code is doing? I see you now have more parameters/properties but it wasn't immediately obvious how this optimized the tests

**Comment by dmitsh** [comment]
@acs-bot test this please

**Comment by dmitsh** [comment]
@JackQuincy I didn't introduce any new parameters. I updated the tests to match recent changes. Also I needed to preserve artifacts, so instead of removing the workspace I'm changing its permission to allow next test to clean the workspace.

**Pull request merged**
