### PR TITLE
Set stability iterations on Windows tests to 1

### LINKED ISSUE #4245: Test issue - Ran command on 0 of 0 desired attempts with 0 successes
I was looking for results for Windows <-> Linux connectivity tests, and it seems that the jobs in CircleCI are skipping them with "Ran command on 0 of 0 desired attempts with 0 successes". I would expect to see at least 1 desired attempt.

Code:

https://github.com/Azure/acs-engine/blob/32db97e90acf9583e7ba201e2aca2ed985d56c2f/test/e2e/kubernetes/kubernetes_test.go#L1052

Logs:

https://circleci.com/gh/Azure/acs-engine/48546?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link 

```
Azure Container Cluster using the Kubernetes Orchestrator with a windows agent pool 
  should be able to resolve DNS across windows and linux deployments
  /go/src/github.com/Azure/acs-engine/test/e2e/kubernetes/kubernetes_test.go:996
STEP: Creating a deployment running IIS
2018/11/10 03:40:00 $ kubectl run iis-dns-kubernetes-southeastasia-71563-37788 -n default --image microsoft/iis:windowsservercore-1803 --port 80 --hostport -1 --overrides { "spec":{"template":{"spec": {"nodeSelector":{"beta.kubernetes.io/os":"windows"}}}}}
2018/11/10 03:40:01 #### $ kubectl run iis-dns-kubernetes-southeastasia-71563-37788 -n default --image microsoft/iis:windowsservercore-1803 --port 80 --hostport -1 --overrides { "spec":{"template":{"spec": {"nodeSelector":{"beta.kubernetes.io/os":"windows"}}}}} completed in 1.347935646s
2018/11/10 03:40:01 $ kubectl get deploy -o json -n default iis-dns-kubernetes-southeastasia-71563-37788
2018/11/10 03:40:02 #### $ kubectl get deploy -o json -n default iis-dns-kubernetes-southeastasia-71563-37788 completed in 1.064802198s
STEP: Creating a nginx deployment
2018/11/10 03:40:02 $ kubectl run nginx-dns-kubernetes-southeastasia-71563-39258 -n default --image library/nginx:latest --image-pull-policy=IfNotPresent --overrides { "spec":{"template":{"spec": {"nodeSelector":{"beta.kubernetes.io/os":"linux"}}}}}
2018/11/10 03:40:04 #### $ kubectl run nginx-dns-kubernetes-southeastasia-71563-39258 -n default --image library/nginx:latest --image-pull-policy=IfNotPresent --overrides { "spec":{"template":{"spec": {"nodeSelector":{"beta.kubernetes.io/os":"linux"}}}}} completed in 1.339700564s
2018/11/10 03:40:04 $ kubectl get deploy -o json -n default nginx-dns-kubernetes-southeastasia-71563-39258
2018/11/10 03:40:05 #### $ kubectl get deploy -o json -n default nginx-dns-kubernetes-southeastasia-71563-39258 completed in 1.041215328s
STEP: Ensure there is a Running nginx pod
STEP: Ensure there is a Running iis pod
STEP: Exposing a internal service for the linux nginx deployment
2018/11/10 03:40:44 $ kubectl expose deployment nginx-dns-kubernetes-southeastasia-71563-39258 --type ClusterIP -n default --target-port 80 --port 80
2018/11/10 03:40:45 #### $ kubectl expose deployment nginx-dns-kubernetes-southeastasia-71563-39258 --type ClusterIP -n default --target-port 80 --port 80 completed in 1.40608925s
STEP: Exposing a internal service for the windows iis deployment
2018/11/10 03:40:46 $ kubectl expose deployment iis-dns-kubernetes-southeastasia-71563-37788 --type ClusterIP -n default --target-port 80 --port 80
2018/11/10 03:40:48 #### $ kubectl expose deployment iis-dns-kubernetes-southeastasia-71563-37788 --type ClusterIP -n default --target-port 80 --port 80 completed in 1.381682045s
STEP: Connecting to Windows from another Windows deployment
STEP: Connecting to Linux from Windows deployment
STEP: Connecting to Windows from Linux deployment
STEP: Cleaning up after ourselves
2018/11/10 03:40:49 Ran command on 0 of 0 desired attempts with 0 successes

2018/11/10 03:40:49 Ran command on 0 of 0 desired attempts with 0 successes

2018/11/10 03:40:49 Ran command on 0 of 0 desired attempts with 0 successes

2018/11/10 03:40:49 $ kubectl delete deploy -n default iis-dns-kubernetes-southeastasia-71563-37788
2018/11/10 03:40:55 #### $ kubectl delete deploy -n default iis-dns-kubernetes-southeastasia-71563-37788 completed in 6.399218663s
2018/11/10 03:40:55 $ kubectl delete deploy -n default nginx-dns-kubernetes-southeastasia-71563-39258
2018/11/10 03:41:01 #### $ kubectl delete deploy -n default nginx-dns-kubernetes-southeastasia-71563-39258 completed in 6.408415964s
2018/11/10 03:41:01 $ kubectl delete svc -n default iis-dns-kubernetes-southeastasia-71563-37788
2018/11/10 03:41:03 #### $ kubectl delete svc -n default iis-dns-kubernetes-southeastasia-71563-37788 completed in 1.104378957s
2018/11/10 03:41:03 $ kubectl delete svc -n default nginx-dns-kubernetes-southeastasia-71563-39258
•2018/11/10 03:41:04 #### $ kubectl delete svc -n default nginx-dns-kubernetes-southeastasia-71563-39258 completed in 1.115405802s
```

cc @dascott @jsturtevant

### PR DESCRIPTION
**Pull request by PatrickLang**
The tests with `cfg.stabilityIterations` checks are important and shouldn't be skipped. If they're too flaky to run 10x, at least run 1x.

I heard a report that service IPs were broken in acs-engine deployments, so I went to check on the test cases and found that they weren't run. This sets it back to run at least once.

Resolves #4245

### CODE REVIEW

**Comment by PatrickLang** [comment]
/hold
Thanks @jsturtevant . Will check and fix it tomorrow

**Comment by PatrickLang** [comment]
Fixed & tests scheduled

**Comment by PatrickLang** [comment]
Ok - this is actually failing now. @jsturtevant @daschott and I thought it would fail, and it might be a real bug

```
STEP: Exposing a internal service for the linux nginx deployment
2018/11/14 16:41:51 $ kubectl expose deployment nginx-dns-kubernetes-southcentralus-1699-3293 --type ClusterIP -n default --target-port 80 --port 80
2018/11/14 16:41:51 #### $ kubectl expose deployment nginx-dns-kubernetes-southcentralus-1699-3293 --type ClusterIP -n default --target-port 80 --port 80 completed in 356.913314ms
STEP: Exposing a internal service for the windows iis deployment
2018/11/14 16:41:52 $ kubectl expose deployment iis-dns-kubernetes-southcentralus-1699-88446 --type ClusterIP -n default --target-port 80 --port 80
2018/11/14 16:41:52 #### $ kubectl expose deployment iis-dns-kubernetes-southcentralus-1699-88446 --type ClusterIP -n default --target-port 80 --port 80 completed in 399.014003ms
STEP: Connecting to Windows from another Windows deployment
2018/11/14 16:41:52 $ kubectl run windows-2-windows-kubernetes-southcentralus-1699-66436 -n default --image microsoft/windowsservercore:1803 --image-pull-policy=IfNotPresent --restart=Never --overrides { "spec": {"nodeSelector":{"beta.kubernetes.io/os":"windows"}}} --command -- powershell iwr -UseBasicParsing -TimeoutSec 60 iis-dns-kubernetes-southcentralus-1699-88446
2018/11/14 16:41:53 #### $ kubectl run windows-2-windows-kubernetes-southcentralus-1699-66436 -n default --image microsoft/windowsservercore:1803 --image-pull-policy=IfNotPresent --restart=Never --overrides { "spec": {"nodeSelector":{"beta.kubernetes.io/os":"windows"}}} --command -- powershell iwr -UseBasicParsing -TimeoutSec 60 iis-dns-kubernetes-southcentralus-1699-88446 completed in 314.919451ms
.
2018/11/14 16:42:29 iwr : The remote name could not be resolved: 

'iis-dns-kubernetes-southcentralus-1699-88446'

At line:1 char:1

+ iwr -UseBasicParsing -TimeoutSec 60 iis-dns-kubernetes-southcentralus ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt 

   pWebRequest) [Invoke-WebRequest], WebException

    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe 

   ll.Commands.InvokeWebRequestCommand

 


2018/11/14 16:42:29 $ kubectl delete po -n default windows-2-windows-kubernetes-southcentralus-1699-66436
2018/11/14 16:42:30 #### $ kubectl delete po -n default windows-2-windows-kubernetes-southcentralus-1699-66436 completed in 367.684252ms
2018/11/14 16:42:30 Ran command on 1 of 1 desired attempts with 0 successes


• Failure [102.187 seconds]
Azure Container Cluster using the Kubernetes Orchestrator
/go/src/github.com/Azure/acs-engine/test/e2e/kubernetes/kubernetes_test.go:82
  with a windows agent pool
  /go/src/github.com/Azure/acs-engine/test/e2e/kubernetes/kubernetes_test.go:969
    should be able to resolve DNS across windows and linux deployments [It]
    /go/src/github.com/Azure/acs-engine/test/e2e/kubernetes/kubernetes_test.go:1015

    Expected
        <int>: 0
    to equal
        <int>: 1

    /go/src/github.com/Azure/acs-engine/test/e2e/kubernetes/kubernetes_test.go:1058
------------------------------
```

**Comment by PatrickLang** [comment]
with Azure-CNI v1.0.12, k8s 1.12 and 1.13 failed the first attempt. Doing a second run to see if it's consistent or not.

```
STEP: Connecting to Linux from Windows deployment
2018/11/14 19:52:47 #### $ kubectl delete po -n default windows-2-windows-kubernetes-westus2-69593-1765 completed in 541.202353ms
2018/11/14 19:52:47 Ran command on 1 of 1 desired attempts with 1 successes

2018/11/14 19:52:47 $ kubectl run windows-2-linux-kubernetes-westus2-69593-73235 -n default --image microsoft/windowsservercore:1803 --image-pull-policy=IfNotPresent --restart=Never --overrides { "spec": {"nodeSelector":{"beta.kubernetes.io/os":"windows"}}} --command -- powershell iwr -UseBasicParsing -TimeoutSec 60 nginx-dns-kubernetes-westus2-69593-5913
2018/11/14 19:52:48 #### $ kubectl run windows-2-linux-kubernetes-westus2-69593-73235 -n default --image microsoft/windowsservercore:1803 --image-pull-policy=IfNotPresent --restart=Never --overrides { "spec": {"nodeSelector":{"beta.kubernetes.io/os":"windows"}}} --command -- powershell iwr -UseBasicParsing -TimeoutSec 60 nginx-dns-kubernetes-westus2-69593-5913 completed in 436.065763ms
.
2018/11/14 19:54:24 iwr : The remote name could not be resolved: 

'nginx-dns-kubernetes-westus2-69593-5913'

At line:1 char:1

+ iwr -UseBasicParsing -TimeoutSec 60 nginx-dns-kubernetes-westus2-6959 ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt 

   pWebRequest) [Invoke-WebRequest], WebException

    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe 

   ll.Commands.InvokeWebRequestCommand

 


2018/11/14 19:54:24 $ kubectl delete po -n default windows-2-linux-kubernetes-westus2-69593-73235
2018/11/14 19:54:24 #### $ kubectl delete po -n default windows-2-linux-kubernetes-westus2-69593-73235 completed in 580.798093ms
2018/11/14 19:54:24 Ran command on 1 of 1 desired attempts with 0 successes


• Failure [164.412 seconds]
```

**Comment by PatrickLang** [comment]
The failed windows <-> Linux traffic issue could be https://github.com/Azure/acs-engine/issues/4188

**Comment by PatrickLang** [comment]
I took the azure-cni version changes back out. Looks like this will need some more manual testing and maybe a new azure-cni version before it should merge.

**Comment by PatrickLang** [comment]
Ok - just added the new Azure-CNI v1.0.14 for Windows. let's try again

**Comment by PatrickLang** [comment]
This needs some manual investigation. All Windows tests failed - the nodes did not join the cluster.

**Comment by PatrickLang** [comment]
Azure CNI 1.0.14 merged in #4297 , so retesting without that as part of the changelist

**Comment by PatrickLang** [comment]
Windows Server 2019 merged to acs-engine master, so next attempt this will run on 2019

**Comment by daschott** [comment]
@PatrickLang does this mean the Dockerfile for `kubletwin/pause` (notice the typo btw) is also updated? I've found that the Dockerfile is still referencing `microsoft` registry which doesn't have images for 1809, when it should be updated to the new registry `mcr.microsoft.com/windows/nanoserver:1809`

**Comment by PatrickLang** [comment]
The dockerfile in the repo is never used. The setup scripts create one as needed.

Sent from a tiny keyboard

On Nov 29, 2018, at 5:42 PM, David Schott <notifications@github.com<mailto:notifications@github.com>> wrote:


@PatrickLang<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPatrickLang&data=02%7C01%7C%7C70c79fb6ca734206f30f08d656651598%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636791389477395408&sdata=QgfmH7T3iTETZrqoQC5f8KyfnqsI9Y9B3eF6OEUDqQ0%3D&reserved=0> does this mean the Dockerfile for kubletwin/pause (notice the typo btw) is also updated? I've found that the Dockerfile is still referencing microsoft registry which doesn't have images for 1809, when it should be updated to the new registry mcr.microsoft.com/windows/nanoserver:1809<http://mcr.microsoft.com/windows/nanoserver:1809>

**Comment by CecileRobertMichon** [comment]
Closing. @PatrickLang did this make it to https://github.com/Azure/aks-engine?

**Pull request closed without merging**
