### PR TITLE
Enable k8s 1.7.2 release

### LINKED ISSUE #1071: Release Kubernetes 1.7.2 - Linux only
This contains a storage fixes for Azure. I'll work on the PR.

### PR DESCRIPTION
**Pull request by lachie83**
Fixes #1071 

This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/1072)

### CODE REVIEW

**Comment by seanknox** [comment]
@acs-bot test this please

**Comment by martell** [comment]
@lachie83 is there a reason why the resizer was rolled back to 1.7 when 2.0 is used with 1.7.1?

Looking forward to seeing this merged because https://github.com/kubernetes/kubernetes/pull/46360/files
currently disks are very slow and fail a lot with attaching initially on readyness. :)

**Comment by lachie83** [comment]
hey @martell. It seems it has caused a regression because some options have been remove in 2.0. I've currently opted to go back to 1.7 then we can raise another PR to go to 2.0 across the board later. https://github.com/Azure/acs-engine/issues/1075 How does that sound. I couldn't actually see any compelling reason to bounce this version as part of any of these PR. Do you know of one. Is there a changelog somewhere for the resizer?

**Comment by martell** [comment]
hey @lachie83 :)

hmm, the versioning for that contrib project is not immediately obvious.
From looking through the logs though I see we can just remove the following 2 options.
`--estimator=exponential` and `--threshold=5` the latter seems to be removed by the rbac PR.
Assuming we can get that merged it should be easy to just remove the former option.
Seems reasonable to revert 170 and 171 to 1.7 until we do this.

Are there other options where it is causing trouble for you?

**Comment by lachie83** [comment]
That sounds good to me.

**Comment by lachie83** [comment]
@acs-bot test this please

**Comment by JiangtianLi** [comment]
@lachie83 @rjtsdl I think there will be merge conflict with your PRs. Please coordinate to resolve.

**Comment by JiangtianLi** [comment]
Also, do we need to add to tests for 1.7.2 (except Windows, which I will add)?

**Comment by lachie83** [comment]
> Also, do we need to add to tests for 1.7.2 (except Windows, which I will add)?

Nothing specific to this release

**Comment by lachie83** [comment]
> @lachie83 @rjtsdl I think there will be merge conflict with your PRs. Please coordinate to resolve.

I will rebase once this is approved

**Comment by JiangtianLi** [comment]
Jingtao's #1108 is not in yet.

**Comment by lachie83** [comment]
@acs-bot test this please

**Comment by rjtsdl** [comment]
Let's get this in first. I Will resolve on my. Lgtm. You can consider approved from me. Don't know How to hit approve button on phone :(

**Comment by lachie83** [comment]
@rjtsdl @JiangtianLi how do I get CI running?

**Comment by rjtsdl** [comment]
1 remove in progress label
2 @acs-bot test this please

**Comment by lachie83** [comment]
@acs-bot test this please

**Comment by seanknox** [comment]
@acs-bot test this please

**Comment by seanknox** [comment]
@rjtsdl @lachie83 no need to remove the "in progress" label—CI doesn't use it anymore. In fact, please do not do this as our backlog uses it.

**Comment by seanknox** [comment]
@lachie83 can you try deploying a k8s 1.5.7 cluster from your branch? e2e tests keep failing on v1.5.7 tests due to some error in the provisioning process:

```
{
  "id": "/subscriptions/xxx/resourceGroups/y-kubernetesversions-kubernetes1.5.7-centralus-1037-16-0",
  "location": "centralus",
  "managedBy": null,
  "name": "y-kubernetesversions-kubernetes1.5.7-centralus-1037-16-0",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null
}
time="2017-07-27T02:43:02Z" level=info msg="Generating assets..." 
time="2017-07-27T02:43:12Z" level=debug msg="pki: PKI asset creation took 3.345644484s" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/apimodel.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/azuredeploy.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/azuredeploy.parameters.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.australiaeast.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.australiasoutheast.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.brazilsouth.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.canadacentral.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.canadaeast.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.centralindia.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.centralus.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.centraluseuap.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.chinaeast.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.chinanorth.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.eastasia.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.eastus.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.eastus2.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.eastus2euap.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.japaneast.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.japanwest.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.koreacentral.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.koreasouth.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.northcentralus.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.northeurope.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.southcentralus.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.southeastasia.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.southindia.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.uksouth.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.ukwest.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.westcentralus.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.westeurope.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.westindia.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.westus.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubeconfig/kubeconfig.westus2.json" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/ca.key" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/ca.crt" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/apiserver.key" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/apiserver.crt" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/client.key" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/client.crt" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubectlClient.key" 
time="2017-07-27T02:43:12Z" level=debug msg="output: wrote /gopath/src/github.com/Azure/acs-engine/_output/acse-2257273-centralus-1037-16-0/kubectlClient.crt" 
Error [deploy_template:y-kubernetesversions-kubernetes1.5.7-centralus-1037-16-0] exit status 1
Output: /usr/local/bin/kubectl
/usr/local/bin/az
ERROR: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'cse0'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=127\"."
      }
    ]
  }
}  
```

https://jenkins.azure-containers.io/job/acs-engine-pr/1037/artifact/_logs/y-kubernetesversions-kubernetes1.5.7-centralus-1037-16-0.log

**Comment by lachie83** [comment]
@seanknox sure thing

**Comment by lachie83** [comment]
@seanknox please retest.

**Comment by lachie83** [comment]
@acs-bot test this please

**Pull request merged**
