### PR TITLE
Translate README.md in root folder into Chinese.

### PR DESCRIPTION
**Pull request by wangtt03**
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/299)

### CODE REVIEW

**Comment by wangtt03** [comment]
Translate the README.md and acs-engine.md into Chinese.

**Comment by brendandburns** [comment]
Can one of the admins verify this patch?

**Comment by wangtt03** [comment]
@rjtsdl Hi Jingtao, I translated the cluster definition.md in this commit. Could you please review it? Thanks!

**Comment by amanohar** [comment]
@wangtt03, it would great if you can add documentation page of how to enable other national clouds to use ACS Engine using the changes you added. E.g. for K8s document what KubernetesImageBase property means and format/file name each image name is expected to be in ("hyperkube-amd64:v1.5.3", "kubernetes-dashboard-amd64:v1.5.10", etc.).

**Comment by wangtt03** [comment]
@amanohar sure. Will update soon.

**Comment by wangtt03** [comment]
@amanohar I create another PR https://github.com/Azure/acs-engine/pull/367 and combine the cluster definition changes with another bug fix. Please have a look at it. Thanks😊

**Comment by wangtt03** [comment]
ping @amanohar @colemickens

**Pull request merged**
