### PR TITLE
[WIP] working CIS-conformant Kubernetes example

### PR DESCRIPTION
**Pull request by jackfrancis**
**What this PR does / why we need it**: Add an example api model to demonstrate a CIS-compliant cluster configuration, with any necessary knobs/changes.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**If applicable**:
- [ ] documentation
- [ ] unit tests
- [ ] tested backward compatibility (ie. deploy with previous version, upgrade with this branch)

**Release note**:

```
working CIS-conformant Kubernetes example
```

### CODE REVIEW

**Comment by serbrech** [comment]
To get some documentation about this, would it make sense to run https://github.com/aquasecurity/kube-bench
- on aks
- on the extended apimodel that @jackfrancis provided

Then document what are the risks incurred by each item not fulfilled, why they are not fulfilled and what it would cost (in terms of feature/ux) to fulfill them, as well as how to do it if possible

**Comment by khenidak** [comment]
ref: https://github.com/Azure/AKS/issues/367

**Comment by shanepeckham** [comment]
We need to enable Admission Controller for PodSecurityPolicy as well as the CIS benchmark findings. Ultimately we need to be able to set '--allow-privileged' but also PSP so that if privileged containers are allowed to run cluster wide, that we can control them via RBAC and PSPs.

**Comment by ams0** [comment]
I tried to deploy your template verbatim and although deployment succeed, the cluster is unusable, but I can't figure out why. Notably, `/etc/kubernetes/manifests/pod-security-policy.yaml` is not present.

```
root@k8s-master-86715174-0:/home/azureuser# systemctl is-active kubelet
active
root@k8s-master-86715174-0:/home/azureuser# docker ps
CONTAINER ID        IMAGE                                                                                                                      COMMAND                  CREATED             STATUS              PORTS               NAMES
db02418b26fa        k8s-gcrio.azureedge.net/hyperkube-amd64@sha256:63ae27eea22f8d3873906377511145d0bfcc5cb1f96475ef0e3db15425677596            "/hyperkube schedu..."   9 hours ago         Up 9 hours                              k8s_kube-scheduler_kube-scheduler-k8s-master-86715174-0_kube-system_9c1e706a900180b9a5538522b2a6f6ea_0
ff5ab7017caa        k8s-gcrio.azureedge.net/kube-addon-manager-amd64@sha256:3519273916ba45cfc9b318448d4629819cb5fbccbb0822cce054dd8c1f68cb60   "/opt/kube-addons.sh"    9 hours ago         Up 9 hours                              k8s_kube-addon-manager_kube-addon-manager-k8s-master-86715174-0_kube-system_bc728e0878993a5b965b990b099abcd9_0
2de190a12c20        k8s-gcrio.azureedge.net/hyperkube-amd64@sha256:63ae27eea22f8d3873906377511145d0bfcc5cb1f96475ef0e3db15425677596            "/hyperkube contro..."   9 hours ago         Up 9 hours                              k8s_kube-controller-manager_kube-controller-manager-k8s-master-86715174-0_kube-system_28d565eb47bc2da8b7ebce1b573e1842_0
1ebaabd05447        k8s-gcrio.azureedge.net/pause-amd64:3.1                                                                                    "/pause"                 9 hours ago         Up 9 hours                              k8s_POD_kube-apiserver-k8s-master-86715174-0_kube-system_836a48a85becf0d75360fb2aefd17c13_0
ce43f90a0b5c        k8s-gcrio.azureedge.net/pause-amd64:3.1                                                                                    "/pause"                 9 hours ago         Up 9 hours                              k8s_POD_kube-addon-manager-k8s-master-86715174-0_kube-system_bc728e0878993a5b965b990b099abcd9_0
3a89c65ead7b        k8s-gcrio.azureedge.net/pause-amd64:3.1                                                                                    "/pause"                 9 hours ago         Up 9 hours                              k8s_POD_kube-scheduler-k8s-master-86715174-0_kube-system_9c1e706a900180b9a5538522b2a6f6ea_0
c10e30d6ead9        k8s-gcrio.azureedge.net/pause-amd64:3.1                                                                                    "/pause"                 9 hours ago         Up 9 hours
```
but the API's are unreachable.

**Comment by marrobi** [comment]
@jackfrancis whats the best way we can help to move this forward? Thanks.

**Comment by jackfrancis** [comment]
Let's close this PR and instead focus on ticking the boxes here one at a time:

https://github.com/Azure/acs-engine/issues/3508

I'll open up a PR that demonstrates this iterative approach. I think the "turn everything on at once" approach is going to be too hard to debug.

**Comment by ams0** [comment]
I made a little progress, but the API still doesn't come up with the template attached to this PR; I had errors like:

```
Jul 24 23:39:36 k8s-master-86715174-0 kubelet[10782]: F0724 23:39:36.678244   10782 kubelet.go:1329] Failed to start ContainerManager [Invalid kernel flag: vm/overcommit_memory, expected value: 1, actual value: 0, Invalid kernel flag: kernel/panic, expected value: 10, actual value: 0, Invalid kernel flag: kernel/panic_on_oops, expected value: 1, actual value: 0]
```

which I solved by:

```
echo "1" >/proc/sys/vm/overcommit_memory
echo "1" >/proc/sys/kernel/panic_on_oops
echo "10" >/proc/sys/kernel/panic
```

I dunno why this is required with this template. However, controller-manager starts now but no API server. Still troubleshooting.

**Comment by jackfrancis** [comment]
Thanks @ams0!

I'm propose we do these changes one at a time. A PR prototype for apiserver `--insecure-port=0` is here:

https://github.com/Azure/acs-engine/pull/3541

**Pull request closed without merging**
