### PR TITLE
Add nodeCidrMask parameter to allow running in a smaller IP vnet.

### PR DESCRIPTION
**Pull request by ashb**
Further to #473 where it is possible to change the IP space kubernetes uses this gives us further control of the IPs k8s uses for the Pods making it practical to deploy everything into a /21 - and have a cluster bigger than 7 agents+masters.

Given the number of parameters that we have to add through all layers to get this into the file it might be time to see about another way of specifying these, but I don't know what such a way might look like.

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/495)

### CODE REVIEW

**Comment by colemickens** [comment]
We can't really look at or consider this until we sort through and address this: https://github.com/Azure/acs-engine/issues/493

**Comment by shrutir25** [comment]
@anhowe how do we want to proceed with this PR ?

**Comment by shrutir25** [comment]
@ashb We have made changes to the acs-engine repo, where we have removed test comparison with the expected files. Please pull the latest changes and resubmit.

**Comment by asktomsk** [comment]
@ashb good job on this, thanks!
Looking forward to see this PR rebased and merged in master.

**Comment by ashb** [comment]
The change that this depended on (#473) got backed out. Has that been put backed in does anyone know? (I'm not doing much actively on ACS/k8s right now as I've moved jobs -- I'm happy to rebase this if so.

**Comment by shrutir25** [comment]
@anhowe how do we want to proceed with this PR ?

**Comment by jackfrancis** [comment]
Closing as #1361 is ready to go. Thanks again @ashb, apologies for any delays on our part!

**Pull request closed without merging**
