### PR TITLE
openshift: fix retry interval in rollout e2e test

### PR DESCRIPTION
**Pull request by kargakis**
Fixes https://github.com/Azure/acs-engine/issues/2952 (hopefully)

@jackfrancis @CecileRobertMichon please merge; potential flake fix

### CODE REVIEW

**Comment by kargakis** [comment]
@mjudeikis ptal

**Comment by mjudeikis** [comment]
/lgtm 
I wonder is it worth parameterise  it? Or its one time value?

**Comment by jim-minter** [comment]
@kargakis you don't think 200ms is still pretty short?  1s?

**Comment by kargakis** [comment]
The interval is doubled after each retry and we retry 10 times so I think
starting off with 200ms is reasonable.

**Comment by jim-minter** [comment]
ah, cool, didn't realise it doubled.

**Pull request merged**
