### PR TITLE
add default reg dns

### PR DESCRIPTION
**Pull request by mjudeikis**
If we redeploy registry for any reasons and recreate service it will cause all crazy things.
Good practice is to have DNS instead of IP. 

ptal @kargakis @jim-minter

### CODE REVIEW

**Comment by jim-minter** [comment]
great catch, thanks @mjudeikis !

**Comment by kargakis** [comment]
@mjudeikis can you also add this in the release-3.9 branch so it gets tested by the e2e test?

**Comment by jim-minter** [comment]
@mjudeikis is out, I've pushed an additional commit onto his branch.
/lgtm

**Comment by kargakis** [comment]
/lgtm

too

**Pull request merged**
