### PR TITLE
update kubernetes doc

### PR DESCRIPTION
**Pull request by skippy**
makes a note about the current state of managed disks in kubernetes.  addresses #849

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/860)

### CODE REVIEW

**Comment by skippy** [comment]
@anhowe very small patch in; let me know if you want different language or the note in a few places (such as examples/disks-managed/README.md)

**Comment by anhowe** [comment]
@acs-bot test this please

**Comment by rjtsdl** [comment]
I will just merge it.

**Comment by seanknox** [comment]
Thanks @skippy!

**Pull request merged**
