### PR TITLE
Commiting the latest code gen files so that circle-ci builds pass.

### PR DESCRIPTION
**Pull request by tariq1890**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**If applicable**:
- [ ] documentation
- [ ] unit tests
- [ ] tested backward compatibility (ie. deploy with previous version, upgrade with this branch)

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@kargakis thoughts?

**Comment by tariq1890** [comment]
@CecileRobertMichon @jackfrancis This is because of the commit : go-bindata/go-bindata@e1b4998#diff-76b9265a0c3cccec7fb95e6bde2f273a. The PR corresponding to this change was merged just 2 days go. Since the scripts do a go get of github.com/go-bindata/go-bindata/... the latest ones are always used. (go-bindata/go-bindata#1)


I guess the way forward would be to vendor in a particular revision/commit of the go-bindata dependency on glide. (We could also ask the go-bindata owners to maintain versions through package management)

**Comment by tariq1890** [comment]
@CecileRobertMichon @jackfrancis This is because of the commit : go-bindata/go-bindata@e1b4998#diff-76b9265a0c3cccec7fb95e6bde2f273a. The PR corresponding to this change was merged just 2 days go. Since the scripts do a go get of github.com/go-bindata/go-bindata/... the latest ones are always used. (go-bindata/go-bindata#1)
I guess the way forward would be to vendor in a particular revision/commit of the go-bindata dependency on glide. (We could also ask the go-bindata owners to maintain versions through package management)

**Comment by kargakis** [comment]
heh, @jim-minter this is what I have stumbled upon in https://github.com/Azure/acs-engine/pull/3480

/lgtm

but eventually we probably want to pin on a commit / tag

**Comment by CecileRobertMichon** [comment]
Thanks @tariq1890!

**Comment by jackfrancis** [comment]
@nicolerenee @ultimateboy How does @tariq1890's suggestion sound to you? Does that seem appropriately hacky, or too hacky? :)

**Comment by tariq1890** [comment]
Created #3527 as per the recommendations of the dep developers. :)

**Pull request merged**
