### PR TITLE
Add support for k8s 1.12.0-beta.0

### PR DESCRIPTION
**Pull request by ritazh**
This is required for the zone work.

### CODE REVIEW

**Comment by jackfrancis** [comment]
Don't merge until this version is released! :)

**Comment by sozercan** [comment]
`v1.12.0-beta.0` is out now

https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/hyperkube-amd64@sha256:d0ce3ee53c474f3c009727f2e06e84b087ecd8a6fa5bdc7e87a6b990c006b2d3/details?tab=info

**Comment by CecileRobertMichon** [comment]
did someone upload the windows binary to acsmirror?

**Comment by jackfrancis** [comment]
@CecileRobertMichon No! This PR was created before this was actually released :)

**Pull request merged**
