### PR TITLE
Do not deploy AKS Billing extension for national clouds

### LINKED ISSUE #3416: acs-engine deploy fails for national clouds (e.g. Azure Government) due to missing AKS.Linux.Billing extension
**Is this a request for help?**: No
---
**Is this an ISSUE or FEATURE REQUEST?**: Issue
---
**What version of acs-engine?**: v0.19.1
---
**Orchestrator and version**: Kubernetes v1.8

**What happened**: Attempted `acs-engine deploy` to Azure Government (with `--azure-env AzureUSGovernmentCloud`) but it failed with the following error:

 >ERRO[0357] {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"NotFound","message":"{\r\n  \"error\": {\r\n    \"code\": \"ArtifactNotFound\",\r\n    \"message\": \"Extension with publisher 'Microsoft.AKS', type 'Compute.AKS-Engine.Linux.Billing', and type handler version '1.0' could not be found in the extension repository.\"\r\n  }\r\n}"},{"code":"NotFound","message":"{\r\n  \"error\": {\r\n    \"code\": \"ArtifactNotFound\",\r\n    \"message\": \"Extension with publisher 'Microsoft.AKS', type 'Compute.AKS-Engine.Linux.Billing', and type handler version '1.0' could not be found in the extension repository.\"\r\n  }\r\n}"},{"code":"NotFound","message":"{\r\n  \"error\": {\r\n    \"code\": \"ArtifactNotFound\",\r\n    \"message\": \"Extension with publisher 'Microsoft.AKS', type 'Compute.AKS-Engine.Linux.Billing', and type handler version '1.0' could not be found in the extension repository.\"\r\n  }\r\n}"},{"code":"NotFound","message":"{\r\n  \"error\": {\r\n    \"code\": \"ArtifactNotFound\",\r\n    \"message\": \"Extension with publisher 'Microsoft.AKS', type 'Compute.AKS-Engine.Linux.Billing', and type handler version '1.0' could not be found in the extension repository.\"\r\n  }\r\n}"},{"code":"NotFound","message":"{\r\n  \"error\": {\r\n    \"code\": \"ArtifactNotFound\",\r\n    \"message\": \"Extension with publisher 'Microsoft.AKS', type 'Compute.AKS-Engine.Linux.Billing', and type handler version '1.0' could not be found in the extension repository.\"\r\n  }\r\n}"},{"code":"NotFound","message":"{\r\n  \"error\": {\r\n    \"code\": \"ArtifactNotFound\",\r\n    \"message\": \"Extension with publisher 'Microsoft.AKS', type 'Compute.AKS-Engine.Linux.Billing', and type handler version '1.0' could not be found in the extension repository.\"\r\n  }\r\n}"}]}}

**What you expected to happen**: Deployment should complete successfully either without the extension (which is how it worked in previous versions) or the extension should be published in national clouds. Probably the former is preferable though I'm not familiar with the extension and it's purpose.

**How to reproduce it** (as minimally and precisely as possible):
Run `acs-engine deploy --cloud-env AzureUSGovernment` with all the other required parameters for the `deploy` command.

**Anything else we need to know**: N/A

### PR DESCRIPTION
**Pull request by gsacavdm**
**What this PR does / why we need it**: This PR prevents acs-engine from including the AKS billing extension when deploying to national clouds given that the extension isn't available in those yet.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3416

**Special notes for your reviewer**: This is a work-in-progress but want to start getting feedback as early as possible.

**If applicable**:
- [ ] documentation
- [ ] unit tests
- [ ] tested backward compatibility (ie. deploy with previous version, upgrade with this branch)

**Release note**:
```release-note
Do not attempt to deploy AKS Billing extension in national clouds.
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
Instead of making the extension optional (which might allow users to disable it and have an effect on our billing numbers, would it be possible to disable the extension for non-AzurePublicCloud deployments? We would then be able to re-enable it when the extension is added there.

**Comment by gsacavdm** [comment]
National clouds aside, is the AKS extension supposed be running on non AKS Kubernetes deployments (aka those deployed directly through acs-engine)? Sounds off...

That aside, I can certainly remove the parameter and make it such that it automatically not deploys the extension for sovereign clouds, just need confirmation that's the preferred approach.

**Comment by CecileRobertMichon** [comment]
@gsacavdm, yes, the extension is deployed on acs-engine deployments as well, see https://github.com/Azure/acs-engine/pull/3360#issuecomment-401894376. @jackfrancis can weigh in when he gets back from vacation next week but I believe the objective is to be able to know how many VMs are deployed through acs-engine, no matter if the customer is using AKS or not.

**Comment by gsacavdm** [comment]
Ok, I rebased my PR and change the code so that UseAksExtension isn't a config rather something that's automatically set based on whether deploying to public Azure or a national cloud.

I also updated the PR title & description to align with the update.

**Comment by vidrascup** [comment]
Is this merged into acs-engine 19.4, i've tested with this version and still same issue ? if we deploy new cluster and this resource fails is this affecting the k8s cluster installation ?

**Comment by gsacavdm** [comment]
How did you deploy the new cluster? Can you share the command, api-model and steps you followed?

**Comment by vidrascup** [comment]
i've builded a new acs-engine on my own from master branch and its working..., but on acs engine 1.9.4 sources the commit was not merged, i've looked into template_generator.go , and the changes that you made are not included. maybe on the next acs-engine build

**Comment by jackfrancis** [comment]
This will be included in v0.20.0, currently in testing

**Pull request merged**
