### PR TITLE
fix master subnet for windows vmss

### PR DESCRIPTION
**Pull request by aminebizid**
**What this PR does / why we need it**:
Fix bug on creaing windows vmss

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**If applicable**:
- [ ] documentation
- [ ] unit tests
- [ ] tested backward compatibility (ie. deploy with previous version, upgrade with this branch)

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
/assign @andyzhangx 

@andyzhangx can you take a quick scan at this?

**Comment by andyzhangx** [comment]
@aminebizid could you provide more details about this PR? is there a bug link for this PR? and this PR is for VMSS and does it work for VM Availability Set?

**Comment by CecileRobertMichon** [comment]
@aminebizid ping

**Pull request closed without merging**
