### PR TITLE
k8s: v1.4.6 -> v1.5.1

### PR DESCRIPTION
**Pull request by colemickens**

### CODE REVIEW

**Comment by colemickens** [comment]
Hold off, we should take `1.5.1` when it's released sometime today. Will update this PR...

**Comment by colemickens** [comment]
PR updated for 1.5.1. @anhowe please take a look.

**Comment by yuvipanda** [comment]
Any update on this? We're blocked on using ACS because we need 1.5.1 for auto provisioning disks..

**Comment by brendandburns** [comment]
This is now merged, we'll get it into the upstream rollout.

**Comment by yuvipanda** [comment]
Thanks @brendanburns! We would appreciate it if you could ping us here when
this rolls out. Thanks :)

**Comment by yuvipanda** [comment]
Just a gentle bump to check if this ever got deployed on ACS :D

**Comment by colemickens** [comment]
Yes. It's deployed.

**Pull request merged**
