### PR TITLE
Set Azure CNI default mode to l2bridge

### PR DESCRIPTION
**Pull request by saiyan86**
**What this PR does / why we need it**:
This PR 
1. sets default operating mode of Azure CNI to l2bridge on Windows nodes.
2. makes kube-dns the default DNS server on Windows nodes.
**Special notes for your reviewer**:
This PR requires Azure CNI [PR#155](https://github.com/Azure/azure-container-networking/pull/155)

### CODE REVIEW

**Comment by saiyan86** [comment]
@sharmasushant @jackfrancis pls review. Thanks!

**Comment by PatrickLang** [comment]
@dineshgovindasamy FYI also includes dns order fix

**Pull request merged**
