### PR TITLE
‘servicePrincipalClientSecret’

### LINKED ISSUE #1208: k8s deployment fails if service principal password includes a semicolon or % char
**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: at least `0.4.0`

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**:

The variable injection logic that outputs a custom provision script treats semicolons literally, and bash interprets it as the end of command character.

Similar behavior for `%`.

See this line:

https://github.com/Azure/acs-engine/blob/096c77105ab6a20552e4211b18c923925c94f955/parts/kubernetesagentresourcesvmas.t#L259

**What you expected to happen**:

successful cluster deployment

**How to reproduce it** (as minimally and precisely as possible):

Include a service principal password that includes a `;` character, generate new templates, and deploy a cluster.

### PR DESCRIPTION
**Pull request by jackfrancis**
surround servicePrincipalClientSecret in single quotes to preserve dangerous bash characters (such as semicolon)

**What this PR does / why we need it**: service principle passwords that included semicolons were failing post-deployment

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1208 

**Special notes for your reviewer**: by surrounding the password in single quotes we should be resilient against bash interpreting a dangerous arg character literally

**Release note**:

```add more resilience against service principal passwords
```

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/1268)

### CODE REVIEW

**Comment by rjtsdl** [comment]
variables('singleQuote')

Is singleQuote already a variable?

**Comment by jackfrancis** [comment]
@rjtsdl good catch, my 2nd commit made it a variable available to all (not just windows)

**Comment by jackfrancis** [comment]
@anhowe I'm consistently getting this deployment failure when attempting to use a service principal whose password contains a `;`:

```
Deployment failed. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'cse0'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=127\"."
      }
    ]
  }
}
```

As E2E indicates, this change works, and is arguably a useful step forward (passing password strings to ARM as quote-protected). Should we proceed with this PR and punt on dealing with #1208? Or does the above error suggest that we're getting closer to enabling support for semicolons in password strings?

**Comment by jackfrancis** [comment]
@anhowe I'm going to close this PR in favor of an alternate approach that base64 encodes/decodes the sp password string

**Pull request closed without merging**
