### PR TITLE
Add node selector for heapster addon

### LINKED ISSUE #3001: Heapster pods get schedules on Windows Nodes
---

ISSUE

---

acs-engine : 0.16.2

---

Kubernetes 1.10

**What happened**:

Heapster pod was scheduled on Windows node

```
Normal   Scheduled              18m                default-scheduler      Successfully assigned heapster-74c5b5d595-bg2rb to 10934k8s9001
  Normal   SuccessfulMountVolume  18m                kubelet, 10934k8s9001  MountVolume.SetUp succeeded for volume "heapster-config-volume"
  Normal   SuccessfulMountVolume  18m                kubelet, 10934k8s9001  MountVolume.SetUp succeeded for volume "heapster-token-th4wj"
  Normal   Pulling                16m (x2 over 16m)  kubelet, 10934k8s9001  pulling image "k8s-gcrio.azureedge.net/heapster-amd64:v1.5.1"
  Warning  Failed                 16m (x2 over 16m)  kubelet, 10934k8s9001  Error: ErrImagePull
  Normal   Pulling                16m (x2 over 16m)  kubelet, 10934k8s9001  pulling image "k8s-gcrio.azureedge.net/addon-resizer:1.8.1"
  Warning  Failed                 16m (x2 over 16m)  kubelet, 10934k8s9001  Error: ErrImagePull
  Normal   SandboxChanged         16m (x3 over 16m)  kubelet, 10934k8s9001  Pod sandbox changed, it will be killed and re-created.
  Warning  Failed                 16m (x2 over 16m)  kubelet, 10934k8s9001  Back-off pulling image "k8s-gcrio.azureedge.net/addon-resizer:1.8.1"
  Normal   BackOff                2m (x63 over 16m)  kubelet, 10934k8s9001  Back-off pulling image "k8s-gcrio.azureedge.net/heapster-amd64:v1.5.1"
```

Probably there needs to be a nodeSelector in the heapster addon yaml file.

### PR DESCRIPTION
**Pull request by adelina-t**
Fixes #3001

### CODE REVIEW

**Comment by jackfrancis** [comment]
@PatrickLang can you sanity-check this change to not install heapster addon on Windows nodes?

**Comment by PatrickLang** [comment]
code LGTM. Will try a deployment shortly

**Comment by PatrickLang** [comment]
LGTM after testing

```
$ kubectl get node -o wide
NAME                       STATUS    ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE                    KERNEL-VERSION   CONTAINER-RUNTIME
37007k8s9000               Ready     <none>    6m        v1.10.1   <none>        Windows Server Datacenter   10.0.17134.1
                           docker://17.6.2
37007k8s9001               Ready     <none>    5m        v1.10.1   <none>    Windows Server Datacenter   10.0.17134.1
                           docker://17.6.2
k8s-linuxpool-37007586-0   Ready     agent     6m        v1.10.1   <none>    Ubuntu 16.04.4 LTS   4.13.0-1016-azure   docker://1.13.1
k8s-linuxpool-37007586-1   Ready     agent     5m        v1.10.1   <none>    Ubuntu 16.04.4 LTS   4.13.0-1016-azure   docker://1.13.1
k8s-master-37007586-0      Ready     master    9m        v1.10.1   <none>    Ubuntu 16.04.4 LTS   4.13.0-1016-azure   docker://1.13.1

$ kubectl -n kube-system get pod -o wide
NAME                                            READY     STATUS    RESTARTS   AGE       IP             NODE
heapster-6f7b9bdf-b764b                         2/2       Running   0          8m        10.240.0.141   k8s-linuxpool-37007586-0
kube-addon-manager-k8s-master-37007586-0        1/1       Running   0          7m        10.255.255.5   k8s-master-37007586-0
kube-apiserver-k8s-master-37007586-0            1/1       Running   0          8m        10.255.255.5   k8s-master-37007586-0
kube-controller-manager-k8s-master-37007586-0   1/1       Running   0          8m        10.255.255.5   k8s-master-37007586-0
kube-dns-v20-59b4f7dc55-5rdnd                   3/3       Running   0          8m        10.240.0.129   k8s-linuxpool-37007586-0
kube-dns-v20-59b4f7dc55-w7csn                   3/3       Running   0          8m        10.240.0.138   k8s-linuxpool-37007586-0
kube-proxy-bqwmz                                1/1       Running   0          6m        10.240.0.127   k8s-linuxpool-37007586-0
kube-proxy-fgjtm                                1/1       Running   0          8m        10.255.255.5   k8s-master-37007586-0
kube-proxy-sx8gd                                1/1       Running   0          6m        10.240.0.4     k8s-linuxpool-37007586-1
kube-scheduler-k8s-master-37007586-0            1/1       Running   0          8m        10.255.255.5   k8s-master-37007586-0
kubernetes-dashboard-65c8bbc84b-m85wd           1/1       Running   0          8m        10.240.0.149   k8s-linuxpool-37007586-0
metrics-server-5c74cf6d4f-qvhwd                 1/1       Running   0          8m        10.240.0.9     k8s-linuxpool-37007586-1
tiller-deploy-d85ccb55c-gfdlb                   1/1       Running   0          8m        10.240.0.13    k8s-linuxpool-37007586-1
```


```
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     CriticalAddonsOnly
Events:
  Type     Reason                 Age              From                               Message
  ----     ------                 ----             ----                               -------
  Warning  FailedScheduling       5m (x9 over 7m)  default-scheduler                  0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.
  Warning  FailedScheduling       4m (x5 over 5m)  default-scheduler                  0/2 nodes are available: 1 node(s) didn't match node selector, 1 node(s) had taints that the pod didn't tolerate.
  Normal   Scheduled              4m               default-scheduler                  Successfully assigned heapster-6f7b9bdf-b764b to k8s-linuxpool-37007586-0
```

**Comment by PatrickLang** [comment]
back to you @jackfrancis

**Pull request merged**
