### PR TITLE
ensure openshift examples stay in sync for base attributes

### PR DESCRIPTION
**Pull request by pweil-**
Fixes https://github.com/Azure/acs-engine/issues/2984

Will rebase when https://github.com/Azure/acs-engine/pull/2978 is merged to add normalization and new test file.

@jim-minter

### CODE REVIEW

**Comment by jim-minter** [comment]
Cool - I'd have been tempted just to json.Decode into a map[string]interface{} though to save all the boilerplate ;)

**Comment by pweil-** [comment]
> Cool - I'd have been tempted just to json.Decode into a map[string]interface{} though to save all the boilerplate ;)

Chickened out when I thought about api version skewing in examples

**Comment by pweil-** [comment]
reminder for: examples/e2e-tests/openshift/definition.json in https://github.com/Azure/acs-engine/pull/2991/files

**Pull request merged**
