### PR TITLE
Azure CNI v1.0.13

### PR DESCRIPTION
**Pull request by saiyan86**
**What this PR does / why we need it**:

This PR updates Azure CNI version from v1.0.12 to v1.0.13.
For detailed info, please refer to https://github.com/Azure/azure-container-networking/releases/tag/v1.0.13.

### CODE REVIEW

**Comment by jackfrancis** [comment]
Thanks @saiyan86! Could you also update this array so that 1.0.13 is pre-installed onto VHD images?

https://github.com/Azure/acs-engine/blob/master/packer/install-dependencies.sh#L26

**Comment by saiyan86** [comment]
@jackfrancis Thanks for the review! I added 1.0.13 to VNET_CNI_VERSIONS.

**Comment by jackfrancis** [comment]
@saiyan86 The windows artifact for this release has a `.1` suffix. Is that intentional?

azure-vnet-cni-windows-amd64-v1.0.13.1.zip

That will break our string concatenation implementation.

**Comment by saiyan86** [comment]
@jackfrancis Thanks for the notice! I renamed the Windows CNI archive.

**Pull request merged**
