### PR TITLE
remove Windows + custom VNET validation error

### PR DESCRIPTION
**Pull request by jackfrancis**
**What this PR does / why we need it**: Enable folks to experiment with Custom VNET + Windows deployments

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
@JiangtianLi @saiyan86 FYI

@idanshahar would like to experiment building hybrid clusters with custom VNET, are we okay with removing this validation check?

**Comment by idanshahar** [comment]
@jackfrancis  @JiangtianLi @saiyan86 
Yes indeed, it will be awesome. Need this for an extremely important scenario with a customer.

**Comment by JiangtianLi** [comment]
@jackfrancis Is this for RS3 or RS1?

**Comment by jackfrancis** [comment]
@JiangtianLi both

**Pull request merged**
