### PR TITLE
added fault domain and update domain labels to agent nodes

### PR DESCRIPTION
**Pull request by xtophs**
**What this PR does / why we need it**:
adds fault domain and update domain labels to agent nodes in the same way acs already does it for k8s clusters.

fault domain labels are necessary for HA deployments of container

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

Fixes Issue [1135](https://github.com/Azure/acs-engine/issues/1135)

**Special notes for your reviewer**:

**Release note**:

```release-note
```

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/1139)

### CODE REVIEW

**Comment by jchauncey** [comment]
@xtophs could you rebase this pr?

**Comment by xtophs** [comment]
Will do!

Sent from my iPhone

On Aug 24, 2017, at 7:23 PM, Jonathan Chauncey <notifications@github.com<mailto:notifications@github.com>> wrote:


@xtophs<https://github.com/xtophs> could you rebase this pr?

**Comment by xtophs** [comment]
rebased with something like this:

```
git checkout master
git fetch upstream
git merge upstream/master  
git checkout xtoph-faultdomain
git rebase master
git pull
# resolve conflicts
git commit
git push origin xtoph-faultdomain
```

Hope that's what was needed.

**Comment by xtophs** [comment]
The error compiling tests crept in with my (botched) rebase attempt. I didn't modify engine_test.go. 

make build: no errors
make test: all tests pass

There might be something wrong with in.

I've reset and this time (I hope) rebased to upstream/master correctly.

Thanks for taking a look. I'll fix the other PR if this one is ok.

**Pull request merged**
