### PR TITLE
k8s: get docker GPG key from docker's repo (https)

### PR DESCRIPTION
**Pull request by colemickens**

### CODE REVIEW

**Comment by brendandburns** [comment]
Can one of the admins verify this patch?

**Comment by colemickens** [comment]
Haha, @dmitsh something is still going on with the GHPR config. Why did @brendandburns comment on this one, but @acs-bot was commenting on the others?

**Comment by brendandburns** [comment]
LGTM.

**Comment by brendandburns** [comment]
(and that previous comment was a bot, not me...)

**Comment by brendandburns** [comment]
(presumably b/c you're using my credentials in Jenkins, not the bot...)

**Pull request merged**
