### PR TITLE
ref(k8s): remove v1.5.x support

### LINKED ISSUE #1059: Remove Kubernetes v1.5
Now that we offer Kubernetes v1.7, we will drop support for Kubernetes v1.5

## AC
- Update regression tests that refer to v1.5.x to use Kubernetes v1.7.1 instead
- Remove v1.5.x references
- Update relevant docs
- Update `pkg/operations/kubernetesupgrade` to support upgrades from v1.6.6 -> v1.71

### PR DESCRIPTION
**Pull request by seanknox**
**What this PR does / why we need it**:
Now that we offer Kubernetes v1.6 and v1.7.x, we can drop support for v1.5. This PR removes K8s v1.5 and updates regression tests to test v1.7 instead.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1059

**Special notes for your reviewer**:

**Release note**:

```release-note
```

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/1061)

### CODE REVIEW

**Comment by seanknox** [comment]
Still a WIP...need to fix `pkg/operations/kubernetesupgrade` amongst other things.

**Comment by seanknox** [comment]
Should be ready for review.

**Comment by seanknox** [comment]
Will hold on this until we better understand the upgrade story.

**Comment by jackfrancis** [comment]
We still need to support 1.5, closing this.

**Pull request closed without merging**
