### PR TITLE
Support for Kubernetes 1.5.7

### PR DESCRIPTION
**Pull request by DonMartin76**
Added support for Kubernetes 1.5.7; the only thing I'm not quite sure about is the Windows support, which I left at `v1.5.3intwinnat.zip`. Is there an 1.5.7 version for that, or will this be compatible? Can I check which versions are available?

All the other things should not have changed, as they have not for 1.6 either. The Dashboard should also stay at 1.5.1, the next version is 1.6.0, for Kubernetes 1.6.0.

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/602)

### CODE REVIEW

**Comment by JackQuincy** [comment]
@JiangtianLi  can you make a 1.5.7 windows zip file? and ping here with the location so that Don can update the windows zip location

**Comment by JiangtianLi** [comment]
Sure, I can make it. @DonMartin76 You might need to modify kuberneteswindowssetup.ps1 after I upload the zip.

**Comment by JiangtianLi** [comment]
@DonMartin76 I have uploaded the 1.5.7 zip. Also I pulled your change, deployed a 1.5.7 cluster and did smoke test. All looked good. Please change to the following line in kuberneteswindowssetup.ps1:
```
if ($global:KubeBinariesVersion -ne "1.5.3" -and $global:KubeBinariesVersion -ne "1.5.7")
```
Please let me know if you hit any issue. Thanks.

**Comment by DonMartin76** [comment]
@JiangtianLi Done. You guys are aweome!

**Comment by DonMartin76** [comment]
Umm? Closed without merging? It's not going in, @rjtsdl ?

**Comment by rjtsdl** [comment]
I must mis clicked the close button.

**Comment by JackQuincy** [comment]
@acs-bot test this please

**Comment by rjtsdl** [comment]
@DonMartin76 , can you regenerate the template.go. We use go-bindata to manage. 
It should be as simple as
```
git pull upstream master
// resolve conflict if any
go generate -v ./...
make ci
```

**Comment by DonMartin76** [comment]
@acs-bot test this please

**Comment by DonMartin76** [comment]
@rjtsdl Regenerated the templates.go; it was just one line which was regenerated. I tried to trigger the test suite via acs-bot, but I don't think it listens to what I say :-D

<details>
<summary>`make ci` output</summary>
```
# make ci
go get github.com/jteeuwen/go-bindata/...
go get github.com/Sirupsen/logrus
go get github.com/spf13/cobra
./scripts/validate-generated.sh
++ mktemp -d
+ T=/tmp/tmp.Ajim08IJwI
+ trap 'rm -rf /tmp/tmp.Ajim08IJwI' EXIT
+ cp -a /gopath/src/github.com/Azure/acs-engine/scripts/.. /tmp/tmp.Ajim08IJwI/
+ cd /tmp/tmp.Ajim08IJwI/
+ go generate ./...
templates.go
+ diff -I '.*bindataFileInfo.*' --exclude=.git -r /gopath/src/github.com/Azure/acs-engine/scripts/.. /tmp/tmp.Ajim08IJwI
+ echo 'Generated assets have no material difference than what is committed.'
Generated assets have no material difference than what is committed.
+ rm -rf /tmp/tmp.Ajim08IJwI
go generate -v ./...
main.go
cmd/generate.go
cmd/root.go
cmd/version.go
pkg/acsengine/azureconst.go
pkg/acsengine/const.go
pkg/acsengine/defaults.go
pkg/acsengine/doc.go
pkg/acsengine/engine.go
pkg/acsengine/engine_test.go
pkg/acsengine/fileloader.go
templates.go
pkg/acsengine/json.go
pkg/acsengine/output.go
pkg/acsengine/pki.go
pkg/acsengine/templates.go
pkg/acsengine/types.go
pkg/api/apiloader.go
pkg/api/const.go
pkg/api/converterfromapi.go
pkg/api/convertertoapi.go
pkg/api/doc.go
pkg/api/types.go
pkg/api/v20160330/const.go
pkg/api/v20160330/doc.go
pkg/api/v20160330/types.go
pkg/api/v20160330/validate.go
pkg/api/v20160930/const.go
pkg/api/v20160930/doc.go
pkg/api/v20160930/types.go
pkg/api/v20160930/validate.go
pkg/api/v20170131/const.go
pkg/api/v20170131/doc.go
pkg/api/v20170131/types.go
pkg/api/v20170131/validate.go
pkg/api/vlabs/const.go
pkg/api/vlabs/doc.go
pkg/api/vlabs/types.go
pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go
test/acs-engine-test/config.go
test/acs-engine-test/config_test.go
test/acs-engine-test/main.go
go get .
go build -v -ldflags="-X github.com/Azure/acs-engine/cmd.BuildSHA=`git describe --always --long --dirty` -X github.com/Azure/acs-engine/cmd.BuildTime=`date +%FT%T%z`"
github.com/Azure/acs-engine
cd test/acs-engine-test; go build -v
github.com/Azure/acs-engine/test/acs-engine-test
test -z "$(gofmt -s -l . | tee /dev/stderr)"
go test -v ./...
?   	github.com/Azure/acs-engine	[no test files]
?   	github.com/Azure/acs-engine/cmd	[no test files]
=== RUN   TestExpected
--- PASS: TestExpected (5.01s)
PASS
ok  	github.com/Azure/acs-engine/pkg/acsengine	5.020s
?   	github.com/Azure/acs-engine/pkg/api	[no test files]
?   	github.com/Azure/acs-engine/pkg/api/v20160330	[no test files]
?   	github.com/Azure/acs-engine/pkg/api/v20160930	[no test files]
?   	github.com/Azure/acs-engine/pkg/api/v20170131	[no test files]
=== RUN   TestProperties_ValidateNetworkPolicy
--- PASS: TestProperties_ValidateNetworkPolicy (0.00s)
PASS
ok  	github.com/Azure/acs-engine/pkg/api/vlabs	0.019s
=== RUN   TestConfigParse
--- PASS: TestConfigParse (0.00s)
PASS
ok  	github.com/Azure/acs-engine/test/acs-engine-test	0.018s
go get -u github.com/golang/lint/golint
# TODO: fix lint errors, enable linting
# golint -set_exit_status
```
</details>

**Comment by JackQuincy** [comment]
LGTM. We just need acs-bot to pass

**Comment by JackQuincy** [comment]
@acs-bot test this please

**Pull request merged**
