### PR TITLE
bump etcd version

### PR DESCRIPTION
**Pull request by jrwren**
**What this PR does / why we need it**:
Bump the etcd version because: https://github.com/Azure/acs-engine/issues/3866

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes 3866

**Special notes for your reviewer**:

I would make it a higher version number but 3.3.1 is the newest tarball that I could find mirrored in the appropriate blob bucket.

If someone with access can put the tarballs for 3.3.2 - 3.3.9 I can change this to 3.3.9 and add those missing versions to `pkg/api/vlabs/validate.go`

### CODE REVIEW

**Comment by tariq1890** [comment]
Thanks @jrwren :). The change looks good to me. Waiting on @CecileRobertMichon 's review

**Comment by CecileRobertMichon** [comment]
New versions of etcd have been released since this was last refreshed (https://github.com/etcd-io/etcd/releases), I would recommend we add the newest versions to the list of valid versions at https://github.com/Azure/acs-engine/blob/master/pkg/api/vlabs/validate.go#L28 and make default the latest

**Comment by jackfrancis** [comment]
Let's upgrade this to `v3.2.24`. Our prior stance has been to depend on the "n-1 of latest" minor version. Since the latest released minor version is stil 3.3, let's stick to the 3.2 track until etcd publishes 3.4.

Looks like `v3.2.24` is the most recent 3.2 version.

As @CecileRobertMichon noted the string slice `etcdValidVersions` at https://github.com/Azure/acs-engine/blob/master/pkg/api/vlabs/validate.go#L28 will also need to be appended to to accommodate new version additions.

Also @mboersma could you look into adding `v3.2.24` to acsmirror CDN?

**Comment by mboersma** [comment]
> adding v3.2.24 to acsmirror CDN?

https://acs-mirror.azureedge.net/github-coreos/etcd-v3.2.24-linux-amd64.tar.gz is available. So is v3.3.1.

**Comment by CecileRobertMichon** [comment]
@mboersma we should add most recent versions (currently most recent is `3.3.9` https://github.com/etcd-io/etcd/releases/tag/v3.3.9) to be made available, even if they aren't default

**Comment by mboersma** [comment]
@CecileRobertMichon I also added 3.3.9 and 3.3.8 but stopped short of backfilling *all* the patch releases.

**Comment by CecileRobertMichon** [comment]
@jrwren can you please add 3.2.24, 3.3.8 and 3.3.9 to https://github.com/Azure/acs-engine/blob/master/pkg/api/vlabs/validate.go#L28 and make 3.2.24 the default?

**Comment by jrwren** [comment]
It is not clear to me how my changes caused this test to fail.

```
--- FAIL: TestGetAgentVMPrefix (0.00s)
    --- FAIL: TestGetAgentVMPrefix/Windows_agent_pool_profile (0.00s)
        types_test.go:2319: expected agent VM name 24789k8s900, but got 44196k8s900
```

Can anyone help?

**Comment by tariq1890** [comment]
@jrwren Feel free to rebase your PR.

**Comment by jackfrancis** [comment]
@jrwren FYI I rebased this PR and force-pushed to deal with some refactoring that landed on master yesterday. Thanks again for driving this! Will merge pending successful E2E run.

**Pull request merged**
