### PR TITLE
Revert static IP allocation logic in Azure CNI, PR 1966.

### LINKED ISSUE #2301: Failed upgrade from kubernetes 1.9.1 to 1.9.3
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
 v0.13.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

1.9.1 -> 1.9.3
**What happened**:
FATA[0098] Error upgrading cluster: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."

**What you expected to happen**:
Upgrade is completed

**How to reproduce it** (as minimally and precisely as possible):
"networkPolicy": "azure"

**Anything else we need to know**:
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"PrivateIPAddressIsAllocated\",\r\n \"message\": \"IP configuration /subscriptions/xx-x-x-x-x-x-x-x-x-/resourceGroups/xx-xxx-xx/providers/Microsoft.Network/networkInterfaces/k8s-master-30347309-nic-0/ipConfigurations/ipconfig1 is using the private IP address 10.240.0.4 which is already allocated to resource /subscriptions/xxx-xx-x-x-x-x-x-x-xx/resourceGroups/xx-xxx-xx/providers/Microsoft.Network/networkInterfaces/k8s-agentpool1-30347309-nic-0.\",\r\n \"details\": []\r\n }\r\n}"}]}

### PR DESCRIPTION
**Pull request by JunSun17**
…NI. (#1966)"

This reverts commit 767932c98562bd9b31d45be01dc43da5c50f803c.

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2301

**Special notes for your reviewer**:
Pending for testing results.

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by serbrech** [comment]
Hi @jackfrancis, Could you provide some details explaining this revert?
In which situation was this change causing problems?
Thanks!

**Comment by JunSun17** [comment]
@serbrech The main issue behind this revert is that upgrading clusters deployed prior to v0.13.0 is failing now, as shown in #2301. We are working on a patch release to address this issue.

**Comment by yastij** [comment]
@jackfrancis - IIUC, does it mean that pod CIDR should be in vnet address space ?

**Comment by JunSun17** [comment]
@yastij I do not think this issue is related what you mentioned. Basically PR 1966 introduces new ways of assigning IPs to master nodes and pods, and it causes conflict for clusters deployed with a prior version of acs-engine.

**Pull request merged**
