### PR TITLE
Vendor dependencies

### PR DESCRIPTION
**Pull request by ahmetalpbalkan**

### CODE REVIEW

**Comment by colemickens** [comment]
I have reservations about this since we are vendoring this package elsewhere. Common guidance seems to be "vendor deps in binaries, don't vendor deps in a library".

There almost needs to be another project for the CLI on top of the core acs-engine that can live a plain library.

Related: #52

**Comment by ahmetalpbalkan** [comment]
You have a main() at the root, though. This is already a binary-producing repo. Does adding vendor.json at the root is going to impact you when you're vendoring subpackages?

**Comment by colemickens** [comment]
Hm. Maybe not, probably it's fine. Which tool did you use for this?

**Comment by ahmetalpbalkan** [comment]
https://github.com/kardianos/govendor

**Comment by colemickens** [comment]
Before I go try to read up, do you know if govendor and gb-vendor both respect the "standard" vendor.json format?

**Comment by ahmetalpbalkan** [comment]
@colemickens govendor claims to do so, however I'm not familiar with the format myself.

**Comment by colemickens** [comment]
This is the problem I'm worried about: https://github.com/mattfarina/golang-broken-vendor (This would manifest in our RP, not in this project likely)

**Comment by ahmetalpbalkan** [comment]
@colemickens that looks like the diamond dependency problem. Is the problem in this case the RP also uses the yaml library? Also it's unlikely that you'll end up assigning types from the yaml package to places, b/c it's just used for parsing things in 1-2 lines of code. So I'm assuming you won't hit this as much.

**Comment by colemickens** [comment]
I think we should go ahead and do this. We can re-evaluate if this actually winds up being a problem.

But, I think we want to do the vendor with `gb-vendor` to be consistent with the RP. Or else evaluate why we chose gb upstream and then revisit this PR.

**Comment by anhowe** [comment]
Thanks for raising this.  However, closing since we need to decide which vendoring strategy we should use.

**Pull request closed without merging**
