### PR TITLE
update prometheus config for 2.1

### LINKED ISSUE #2142: Kubernetes cluster deployment ends in error state with prometheus-grafana
**Is this a request for help?**:

YES

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

**What version of acs-engine?**:

0.12.4

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes v1.7.9

**What happened**:
I deployed a Kubernetes Cluster from scratch into the Azure Germany environment with the prometheus-grafana extension. The cluster was deployed via the following JSON-File:

`{
  "apiVersion": "vlabs",
  "location": "germanycentral",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "yestest",
      "vmSize": "Standard_D2_v2",
	  "storageProfile": "ManagedDisks"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 2,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet",
		 "storageProfile": "ManagedDisks",
		 "extensions": [
          { 
            "name": "prometheus-grafana-k8s"
          }
		  ]
      }
    ],
    "linuxProfile": {
      "adminUsername": "",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "extensionProfiles": [
      { 
        "name": "prometheus-grafana-k8s", 
        "version": "v1",
        "rootURL": "https://raw.githubusercontent.com/Azure/acs-engine/master/"
      }
    ],
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}
`
After the deployment the monitoring-prometheus-server ends up in an error state with the following error:

`PersistentVolumeClaim is not bound: "monitoring-prometheus-server" (repeated 3 times)
Unable to mount volumes for pod "monitoring-prometheus-server-4039493558-bcgdq_default(68f458f4-0108-11e8-800e-0017fa1052b9)": timeout expired waiting for volumes to attach/mount for pod "default"/"monitoring-prometheus-server-4039493558-bcgdq". list of unattached/unmounted volumes=[storage-volume]
Error syncing pod`

**What you expected to happen**:
Running cluster with a working prometheus and grafana combination.

**How to reproduce it** (as minimally and precisely as possible):
As I wrote I just deployed a cluster into the Azure Germany cloud with the conifgration as above.

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by martell**
**What this PR does / why we need it**:
fixes #2142, as a follow up to #2183

### CODE REVIEW

**Comment by trstringer** [comment]
@martell (or @dtzar if you've tested this pr out), what api-model did you use to test this out successfully? Can you share?

**Comment by trstringer** [comment]
I'm unsure how this could have been tested successfully without changing [this line of code in the fork](https://github.com/marinelayer/acs-engine/blob/update-pga/extensions/prometheus-grafana-k8s/v1/prometheus-grafana-k8s.sh#L146).

**Comment by trstringer** [comment]
Update: we are looking into this, please do not merge this yet.

cc // @ritazh

**Comment by dtzar** [comment]
There is no way I see this fixing the entire solution since in the example Readme we do not turn off RBAC (which is now enabled by default).  I approved just because this gets us closer to working.  The best solution IMO would be to have a v1 version of the extension which works with non-RBAC clusters where the helm version will match roughly the supported K8s version, using the 1.8.x version of the chart.  v2 version of the extension should have a switch for RBAC, but leave it on by default and target 1.8/1.9+ clusters with the 5.X version of prometheus.

**Comment by dtzar** [comment]
I just tested with a vanilla acs-engine configuration (no prometheus/grafana extension) which provisions K8s 1.7.9 configuration and it uses RBAC.  Without specifying `rbac.create=true` the installation fails, but with this set, the installation succeeds.  @martell can you please update this to be true in your PR for the values.yaml file?

**Comment by trstringer** [comment]
@dtzar you're talking about the manual helm installation of these charts succeeding? This is going to be a different case. This embedded `prometheus_values.yaml` config file is meant for the v4 version of the prometheus chart. It needs to be updated prior to merging.

Without RBAC set for the cluster, what is the failed error message when you try to install v5 of the Prometheus helm chart?

**Pull request closed without merging**
