### PR TITLE
k8s: update 1.6.x to 1.6.10

### PR DESCRIPTION
**Pull request by martell**
**What this PR does / why we need it**:
git cherry-pick A..B does not include A in the list
git cherry-pick A^..B includes A in the list

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
Need someone to create v1.6.10intwinnat.zip before merging.
**Release note**:

```release-note
```
NONE

### CODE REVIEW

**Comment by jackfrancis** [comment]
@JiangtianLi Does the `1.6.10` windows image referenced in this PR exist?

**Comment by martell** [comment]
@jackfrancis I left a note in the PR that says
`Need someone to create v1.6.10intwinnat.zip before merging.`

**Comment by JiangtianLi** [comment]
@jackfrancis No, I need to build it. Will update here.

**Comment by jchauncey** [comment]
i can reproduce the issue we are seeing in the e2e tests. will work on a fix

**Comment by jackfrancis** [comment]
@martell Could you kindly rebase from master? I just merged in @jchauncey's fix

**Comment by martell** [comment]
@jackfrancis whoops I just fixed the same thing :D

**Comment by jchauncey** [comment]
@martell need to fix the conflict - test/e2e/kubernetes/node/node.go
Merge pull request

**Comment by jchauncey** [comment]
@martell nevermind i just did it through github.

**Comment by jackfrancis** [comment]
Ha! I actually prefer @jchauncey's because it will accept v`1.6.100`, for example (you never know!...)

**Comment by martell** [comment]
No worries, sounds good to me, though I hope we never get to a minor version of 100 :)
@jackfrancis could you look at #1468.

**Comment by jackfrancis** [comment]
E2E for Linux 1.6 passed, thanks @jchauncey and @martell. @JiangtianLi will update when the 1.6.10 Windows build is ready and published to the URL in this PR, after which point I'll re-kick-off the hybrid 1.6 E2E test.

**Comment by martell** [comment]
closing in favour of #1513 because of a CVE

**Pull request closed without merging**
