### PR TITLE
k8s: use journald as log-driver

### PR DESCRIPTION
**Pull request by rjtsdl**
Using journald as log-driver, journald has default log retention policy.

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/373)

### CODE REVIEW

**Comment by colemickens** [comment]
Does journald roll by default then?

**Comment by rjtsdl** [comment]
@acs-bot please test this

**Comment by rjtsdl** [comment]
@colemickens from what i read, i think so.

> Defaults to one eighth of the values configured with SystemMaxUse= and RuntimeMaxUse=, so that usually seven rotated journal files are kept as history

**Comment by rjtsdl** [comment]
@acs-bot please test this

**Comment by rjtsdl** [comment]
@acs-bot  please test this

**Comment by rjtsdl** [comment]
@acs-bot test this please

**Pull request merged**
