### PR TITLE
custom script to mount volumes

### PR DESCRIPTION
**Pull request by xtophs**
Half of PR #80. Custom script mounting DC/OS volumes

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/386)

### CODE REVIEW

**Comment by colemickens** [comment]
Do we actually want this in this form, or do we want to do these sorts of things using the extension model that @RobBagby is building? cc: @anhowe ?

**Comment by anhowe** [comment]
In the statically attached disks scenario, this PR is ensuring these disks are landing in expected folders for DCOS, and then surfaced through DCOS.

**Comment by colemickens** [comment]
Yes, but can't #393 be used for this?

**Comment by shrutir25** [comment]
@colemickens @anhowe how do we want to proceed with this PR ?

**Comment by shrutir25** [comment]
@xtophs We have made changes to the acs-engine repo, where we have removed test comparison with the expected files. Please pull the latest changes and resubmit.

**Comment by shrutir25** [comment]
closing PR as there has been no response from owner for 12 days

**Pull request closed without merging**
