### PR TITLE
revert Azure CNI to 1.0.4

### LINKED ISSUE #3283: getsockopt: connection refused since v0.18.5
**Is this a request for help?**:

Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

**What version of acs-engine?**:

v0.18.5

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 1.10

**What happened**:

On cluster created with acs-engine v0.18.5, network liveliness probes are flaky and often fail with an error message like : ` dial tcp 10.240.0.38:80: getsockopt: connection refused`

This can happen for every pods we use. Clusters deployed with version v0.18.3 work fine (#3153 aside)

**How to reproduce it** (as minimally and precisely as possible):

Here is the definition : 

```{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.10"
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": "XXX",
      "vmSize": "Standard_D2_v3"
    },
    "agentPoolProfiles": [
      {
        "name": "cpuworkers",
        "count": 2,
        "vmSize": "Standard_D16s_v3",
        "availabilityProfile": "VirtualMachineScaleSets"
      }
    ],
    "linuxProfile": {
      "adminUsername": "cluster",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}
```

The following install with helm (as an example) will lead to failing pods : 
`helm install --name ddagent --set datadog.apiKey=<api_key> stable/datadog`

### PR DESCRIPTION
**Pull request by jackfrancis**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3283

**Special notes for your reviewer**:

**If applicable**:
- [ ] documentation
- [ ] unit tests
- [ ] tested backward compatibility (ie. deploy with previous version, upgrade with this branch)

**Release note**:

```
revert Azure CNI to 1.0.4
```

### CODE REVIEW

**Comment by sharmasushant** [comment]
@jackfrancis @CecileRobertMichon What happened here?

**Comment by jackfrancis** [comment]
#3283, along with a drop in network reliability across our E2E tests suggests we should revert this change and evaluate if it restores stability.

**Comment by jackfrancis** [comment]
@PatrickLang @khenidak FYI

**Comment by PatrickLang** [comment]
So where is the linked issue for https://github.com/Azure/azure-container-networking ? This puts us in a bad position because 1.0.6 included some DNS related fixes such as #3143 . Reverting to 1.0.4 regressed this

**Pull request merged**
