### PR TITLE
add containerd and fix flannel and cilium

### LINKED ISSUE #2966: network policy/plugin confusion
It seems like there is some confusion here, the only listed network plugins are azure and kubenet, cilium and flannel are both network plugins. cilium is also a network policy.

### PR DESCRIPTION
**Pull request by jessfraz**
closes #2966

Adds the following e2e tests:

- examples/e2e-tests/kubernetes/kubernetes-config/containerd.json
- examples/e2e-tests/kubernetes/kubernetes-config/flannel.json

### CODE REVIEW

**Comment by jessfraz** [comment]
clear-containers e2e running here: https://jenkins.azure-containers.io/view/acs-engine/job/k8s-clear-containers/113/

**Comment by jessfraz** [comment]
cc @thomastaylor312

**Comment by jessfraz** [comment]
running cilium e2e here: https://jenkins.azure-containers.io/view/acs-engine/job/k8s-cilium/80/console

**Comment by jessfraz** [comment]
both e2es passed :)

**Comment by thomastaylor312** [comment]
Thanks @jessfraz!

**Pull request merged**
