### PR TITLE
Improve Custom VNet support

### PR DESCRIPTION
**Pull request by sylr**
**What this PR does / why we need it**:

This PR implements https://github.com/kubernetes/kubernetes/pull/49725 in acs-engine.

At this moment Custom VNet in a separate RG has one flaw (as far as I'm aware of), Kubernetes is unable to create an `internal load balancer Azure resource` for `internal load balancer k8s service` because the Azure Cloud Provider driver looks for the master subnet in the RG of k8s and this fails (because it's not there).

https://github.com/kubernetes/kubernetes/pull/49725 fixes this by introducing a new configuration in azure.json `vnetResourceGroup`.

This patchsimply adds this new vnetResourceGroup configuration to azure.json based on the resource id of the master subnet.

To work properly is also depends on https://github.com/Azure/acs-engine/pull/1142.

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/1150)

### CODE REVIEW

**Comment by seanknox** [comment]
Please rebase off of master—we just merged in CircleCI support. Rebasing should kick off a job in CI (which you'll be able to see).

**Comment by sylr** [comment]
Rebased.

**Comment by jchauncey** [comment]
going to close and reopen this pr to see if i can get circle to pick up the right commit.

**Comment by sylr** [comment]
Can someone tell me what is wrong with the e2e tests ?

**Comment by jchauncey** [comment]
@sylr can you rebase really quick? We've changed the tests we run in circle and that would give me a better indication if something is actually wrong.

**Comment by sylr** [comment]
Rebased

**Comment by PowershellNinja** [comment]
Hi Guys
I am currently having this exact issue with a customer not being able to create a load-balancer service with an azure internal load balancer as the vnet is defined in a different resource group.
We try to do this using:
```YAML
[...]
metadata: 
    name: my-service
    annotations: 
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
[...]
```

Is it correct if I assume that for the time being, the workaround would be to create everything in the same resource group?

Thanks!

**Comment by jackfrancis** [comment]
ref: #1361

**Comment by jackfrancis** [comment]
Confirmed that `VnetResourceGroup` azure cloudprovider option is available in kubernetes versions `v1.6.11`, `v1.7.7`, and `v1.8.0`.

**Comment by jackfrancis** [comment]
@sylr If you grant maintainer edit access on this PR I can rebase for you, otherwise I'll prioritize merging this as soon as you rebase.

**Comment by sylr** [comment]
@jackfrancis rebased

**Comment by jackfrancis** [comment]
@sylr It looks like if we're not using custom vnet config, `"vnetResourceGroup"` is set to `""` (empty string) in `azure.json` for cloudprovider. Is that a supported setting value?

**Comment by sylr** [comment]
Yes, The patch I made in kubernetes/kubernetes looks for a non empty string https://github.com/kubernetes/kubernetes/pull/49725/files#diff-a25caeb366a02540977479f9e6fa9721R148

**Comment by jackfrancis** [comment]
@sylr O.K., I noticed the `/parts/kubernetesmastercustomscript.sh` is broken (probably during rebase). Here's a diff from my local fix of it:

```
$ git diff
diff --git a/parts/kubernetesmastercustomscript.sh b/parts/kubernetesmastercustomscript.sh
index 89f89f36..b45559a6 100644
--- a/parts/kubernetesmastercustomscript.sh
+++ b/parts/kubernetesmastercustomscript.sh
@@ -30,9 +30,9 @@ CLOUDPROVIDER_BACKOFF="${20}"
 CLOUDPROVIDER_BACKOFF_RETRIES="${21}"
 CLOUDPROVIDER_BACKOFF_EXPONENT="${22}"
 CLOUDPROVIDER_BACKOFF_DURATION="${23}"
-CLOUDPROVIDER_BACKOFF_JITTER="${24}
+CLOUDPROVIDER_BACKOFF_JITTER="${24}"
 # Default values for rate limit configuration
-CLOUDPROVIDER_RATELIMIT="${24}"
+CLOUDPROVIDER_RATELIMIT="${25}"
 CLOUDPROVIDER_RATELIMIT_QPS="${26}"
 CLOUDPROVIDER_RATELIMIT_BUCKET="${27}"
```

If you allow edits from maintainers I'm happy to fix this for you.

https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Pull request merged**
