### PR TITLE
Update cluster role bindings for azure-cloud-provider

### LINKED ISSUE #3847: Update azure-cloud-provider rolebinding
**Is this a request for help?**:

A placeholder for updating cluster role azure-cloud-provider and binding. This is required for https://github.com/kubernetes/kubernetes/pull/68212.

```yaml
kind: List
apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    labels:
      kubernetes.io/cluster-service: "true"
    name: system:azure-cloud-provider
  rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs:
    - create
    - patch
    - update
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
    - get
    - create
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    labels:
      kubernetes.io/cluster-service: "true"
    name: system:azure-cloud-provider
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:azure-cloud-provider
  subjects:
  - kind: ServiceAccount
    name: azure-cloud-provider
    namespace: kube-system
  - kind: ServiceAccount
    name: persistent-volume-binder
    namespace: kube-system
```

### PR DESCRIPTION
**Pull request by feiskyer**
**What this PR does / why we need it**:

Fix #3847. This is required for kubernetes v1.12.

cc @khenidak @jackfrancis 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**If applicable**:
- [ ] documentation
- [ ] unit tests
- [ ] tested backward compatibility (ie. deploy with previous version, upgrade with this branch)

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
@khenidak Is this change valid across all versions of k8s? (The way this is currently implemented, this addon spec is used by all k8s versions >= 1.7)

**Comment by jackfrancis** [comment]
@PatrickLang this change seems to have consistently busted PVC for Windows. Anything obvious jump out at you?

**Comment by PatrickLang** [comment]
@andyzhangx can you work with @feiskyer on these failures?

**Comment by feiskyer** [comment]
Splited cluster roles into two: `system:azure-persistent-volume-binder` and `system:azure-cloud-provider`. CI green now.

**Comment by andyzhangx** [comment]
@feiskyer I still don't understand why create azure file pvc failed on Windows in the prior PR.

**Pull request merged**
