### PR TITLE
differentiate the exit code for k8s provision script

### LINKED ISSUE #785: Differentiate exit code in Kubernetes provisioning script
**Is this an ISSUE or FEATURE REQUEST?** (choose one): BUG

Exit codes should be differentiated in the Kubernetes provisioning script for easier debugging.

### PR DESCRIPTION
**Pull request by rjtsdl**
**What this PR does / why we need it**:
By differentiating the exit code, better and easier for issue investigation.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #785 

**Special notes for your reviewer**:
Ready for review
**Release note**:

```release-note
```

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/791)

### CODE REVIEW

**Comment by rjtsdl** [comment]
I thought the issue is
```
Exit codes should be differentiated in the Kubernetes provisioning script for easier debugging.
```
Btw, which script do you mean docker provision script? I though each orchestrator only have one provision script.

**Comment by JackQuincy** [comment]
When we talked offline we talked about updating the other provisioning scripts for other orchestrators at the same time as it was very easy to do.  

> github.com\Azure\acs-engine\parts\configure-swarm-cluster.sh
github.com\Azure\acs-engine\parts\configure-swarmmode-cluster.sh

**Comment by rjtsdl** [comment]
Sure, just updated. I was looking the scope of the issue i am fixing.

**Comment by rjtsdl** [comment]
Failed due to 
```
"error": {
    "code": "MaxStorageAccountsCountPerSubscriptionExceeded",
    "message": "Subscription <subscription id> already contains 250 storage accounts and the maximum allowed is 250."
  }

```

**Comment by rjtsdl** [comment]
@acs-bot test this please

**Pull request merged**
