### PR TITLE
Fix for kubelet startup script when using azure cni

### PR DESCRIPTION
**Pull request by madhanrm**
**What this PR does / why we need it**:
For 1803 & below, to workaround a known issue, we need the network to be recreated on reboot. This PR adds that workaround into the Kubeletstartup script.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
As soon as the fix for the original issue is serviced (probably in June Servicing), we can remove this for 1803. But may still need it for 1709. 

**If applicable**:
- [ ] documentation
- [ ] unit tests
- [ ] tested backward compatibility (ie. deploy with previous version, upgrade with this branch)

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by saiyan86** [comment]
@madhanrm Hi Madhan, could you please add some descriptions to this PR? Thanks!

**Comment by madhanrm** [comment]
@saiyan86 Have updated the description.

**Comment by madhanrm** [comment]
@saiyan86 can you get this PR approved.

**Comment by saiyan86** [comment]
@madhanrm Thanks for updating. I just approved the PR.

**Pull request merged**
