### PR TITLE
Resolve merge conflict in building 1.7.13

### PR DESCRIPTION
**Pull request by JiangtianLi**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by JiangtianLi** [comment]
@andyzhangx

**Comment by andyzhangx** [comment]
@JiangtianLi I have identified that `3aa179744f` commit is only for linux, all conflicts are due to commit `137f4cb16e` which brings azure disk mount feature (https://github.com/kubernetes/kubernetes/pull/51252)

**Comment by andyzhangx** [comment]
@JiangtianLi  so Azure/release-1.7 is only for Windows, right? I found some commits should be back ported to this 1.7 branch also:
```
git revert --no-edit 6a2e2f47d3  Fix the Azure file to work within different cloud environments
git revert --no-edit 3a4abca2f7  Fall back on Azure public cloud endpoint when no Azure cloud provider is found
```
Just hold on and let me work out a patch

**Comment by andyzhangx** [comment]
@JiangtianLi Update:
Finally I found that below two commits are already covered by 3aa179744f commit
```
git revert --no-edit 6a2e2f47d3  Fix the Azure file to work within different cloud environments
git revert --no-edit 3a4abca2f7  Fall back on Azure public cloud endpoint when no Azure cloud provider is found
```
So everything looks good for azure/release-1.7 now
I will send a PR to add comments to all skipping comments in acs-engine build script.

**Comment by andyzhangx** [comment]
@JiangtianLi It may be better add following comments, every skipping commit should have a comment:
```
git revert --no-edit 3aa179744f || true  #only for linux
git revert --no-edit 593653c384 || true  #only for linux
git revert --no-edit 7305738dd1 || true  #add tests only
git revert --no-edit e01bafcf80 || true     #only for linux
git revert --no-edit afd79db7a6 || true    #only for linux
git revert --no-edit 3a4abca2f7 || true  #covered by commit 3aa179744f 
git revert --no-edit 6a2e2f47d3 || true  #covered by commit 3aa179744f
```

**Pull request merged**
