### PR TITLE
ref(kube-addons): move k8s manifests/scripts/etc to parts/kubernetes

### PR DESCRIPTION
**Pull request by seanknox**
This is a small refactor to organize Kubernetes files under `parts/`.

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/977)

### CODE REVIEW

**Comment by JackQuincy** [comment]
Any plans to move the actual template files? or is this just for the none template files?

**Comment by seanknox** [comment]
> Any plans to move the actual template files? or is this just for the none template files?

Was just going to ask you and @kris-nova your thoughts on that. Might as well? FYI no big design plans here, just trying to do an incremental improvement...

**Comment by seanknox** [comment]
Hey @colemickens @JackQuincy @kris-nova, what's the trick with changing paths on elements in the various YAML maps? e.g.:

```go
var kubernetesManifestYamls = map[string]string{
	"MASTER_KUBERNETES_SCHEDULER_B64_GZIP_STR":          "kubernetes/manifests/kubernetesmaster-kube-scheduler.yaml",
	"MASTER_KUBERNETES_CONTROLLER_MANAGER_B64_GZIP_STR": "kubernetesmaster-kube-controller-manager.yaml",
	"MASTER_KUBERNETES_APISERVER_B64_GZIP_STR":          "kubernetesmaster-kube-apiserver.yaml",
	"MASTER_KUBERNETES_ADDON_MANAGER_B64_GZIP_STR":      "kubernetesmaster-kube-addon-manager.yaml",
}
```

Tried adding leading `./` as well, but the file is never found if I move from outside of `parts/`.
```
--- FAIL: TestExpected (3.17s)
	engine_test.go:62: error in file testdata/disks-managed/kubernetes-vmas.json: BUG: Asset kubernetes/manifests/kubernetesmaster-kube-scheduler.yaml not found
	engine_test.go:62: error in file testdata/disks-storageaccount/kubernetes.json: BUG: Asset kubernetes/manifests/kubernetesmaster-kube-scheduler.yaml not found
	engine_test.go:62: error in file testdata/key-vault-certs/kubernetes.json: BUG: Asset kubernetes/manifests/kubernetesmaster-kube-scheduler.yaml not found
	engine_test.go:62: error in file testdata/key-vault-params/kubernetes.json: BUG: Asset kubernetes/manifests/kubernetesmaster-kube-scheduler.yaml not found
	engine_test.go:62: error in file testdata/kubernetesversions/kubernetes1.5.3.json: BUG: Asset kubernetes/manifests/kubernetesmaster-kube-scheduler.yaml not found
	engine_test.go:62: error in file testdata/kubernetesversions/kubernetes1.6.2.json: BUG: Asset kubernetes/manifests/kubernetesmaster-kube-scheduler.yaml not found
	engine_test.go:62: error in file testdata/largeclusters/kubernetes.json: BUG: Asset kubernetes/manifests/kubernetesmaster-kube-scheduler.yaml not found
	engine_test.go:62: error in file testdata/location/kubernetes.json: BUG: Asset kubernetes/manifests/kubernetesmaster-kube-scheduler.yaml not found
	engine_test.go:62: error in file testdata/simple/kubernetes.json: BUG: Asset kubernetes/manifests/kubernetesmaster-kube-scheduler.yaml not found
	engine_test.go:62: error in file testdata/v20160930/kubernetes.json: BUG: Asset kubernetes/manifests/kubernetesmaster-kube-scheduler.yaml not found
	engine_test.go:62: error in file testdata/v20170131/kubernetes.json: BUG: Asset kubernetes/manifests/kubernetesmaster-kube-scheduler.yaml not found
	engine_test.go:62: error in file testdata/v20170701/kubernetes.json: BUG: Asset kubernetes/manifests/kubernetesmaster-kube-scheduler.yaml not found
	engine_test.go:62: error in file testdata/vnet/kubernetesvnet.json: BUG: Asset kubernetes/manifests/kubernetesmaster-kube-scheduler.yaml not found
	engine_test.go:62: error in file testdata/windows/kubernetes-hybrid.json: BUG: Asset kubernetes/manifests/kubernetesmaster-kube-scheduler.yaml not found
	engine_test.go:62: error in file testdata/windows/kubernetes.json: BUG: Asset kubernetes/manifests/kubernetesmaster-kube-scheduler.yaml not found
```

**Comment by rjtsdl** [comment]
@seanknox , i think the trick is in fileloader.go. The first two lines (in comments) are for go-bindata.

```
package acsengine

//go:generate go-bindata -nometadata -pkg $GOPACKAGE -prefix ../../parts/ -o templates.go ../../parts/
//go:generate gofmt -s -l -w templates.go
// fileloader use go-bindata (https://github.com/jteeuwen/go-bindata)
// go-bindata is the way we handle embedded files, like binary, template, etc.

```

**Comment by seanknox** [comment]
@rjtsdl @colemickens is `pkg/fileloader.go` meant just to show an example? There's no code there, seemingly.

**Comment by shrutir25** [comment]
@rjtsdl - could you review this PR ?

**Comment by seanknox** [comment]
Thanks @shrutir25 and @rjtsdl but no need to review right now.

**Comment by jchauncey** [comment]
@seanknox you want to move forward with this change or close it?

**Comment by seanknox** [comment]
Will close, thanks for checking in.

**Pull request closed without merging**
