### PR TITLE
[WIP] Fix #1767 Custom VNET support for RS3 Windows 

### LINKED ISSUE #1767: Custom VNET support for Windows
**Is this a request for help?**:

---NO

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

---ISSUE

**What version of acs-engine?**:

---Version: canary
GitCommit: 8db990ba
GitTreeState: clean

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
{
  "error": {
    "code": "InvalidTemplate",
    "message": "Unable to process template language expressions for resource '/subscriptions/b21c32c2-4e59-433a-8c53-ebd4729d33ab/resourceGroups/Kubernetes-Prod-9997/providers/Microsoft.Compute/virtualMachines/11742k8s9000' at line '1' and column '46171'. 'The template variable 'subnet' is not found. Please see https://aka.ms/arm-template/#variables for usage details.'"
  }
}

**What you expected to happen**:
{
  "error": {
    "code": "InvalidTemplate",
    "message": "Unable to process template language expressions for resource '/subscriptions/b21c32c2-4e59-433a-8c53-ebd4729d33ab/resourceGroups/Kubernetes-Prod-9997/providers/Microsoft.Compute/virtualMachines/11742k8s9000' at line '1' and column '46171'. 'The template variable 'subnet' is not found. Please see https://aka.ms/arm-template/#variables for usage details.'"
  }
}

**How to reproduce it** (as minimally and precisely as possible):
{
  "error": {
    "code": "InvalidTemplate",
    "message": "Unable to process template language expressions for resource '/subscriptions/b21c32c2-4e59-433a-8c53-ebd4729d33ab/resourceGroups/Kubernetes-Prod-9997/providers/Microsoft.Compute/virtualMachines/11742k8s9000' at line '1' and column '46171'. 'The template variable 'subnet' is not found. Please see https://aka.ms/arm-template/#variables for usage details.'"
  }
}

**Anything else we need to know**:
{
  "error": {
    "code": "InvalidTemplate",
    "message": "Unable to process template language expressions for resource '/subscriptions/b21c32c2-4e59-433a-8c53-ebd4729d33ab/resourceGroups/Kubernetes-Prod-9997/providers/Microsoft.Compute/virtualMachines/11742k8s9000' at line '1' and column '46171'. 'The template variable 'subnet' is not found. Please see https://aka.ms/arm-template/#variables for usage details.'"
  }
}

### PR DESCRIPTION
**Pull request by JiangtianLi**
**What this PR does / why we need it**:
Fix #1767 Custom VNET support for RS3 Windows

### CODE REVIEW

**Comment by jackfrancis** [comment]
@JiangtianLi Could you add a deployment for `vnet/kubernetesvnet-windows.json` to the deployments array in `test/acse-conf/acse-regression.json`? This way we can continue to verify this cluster deployment pattern in periodic E2E regression tests.

**Comment by JiangtianLi** [comment]
@jackfrancis Sure thing. Will update. Note, custom vnet for windows doesn't work fully yet due to issue with windows container network config. So this is still WIP.

**Comment by sharmasushant** [comment]
@jackfrancis @JiangtianLi  @tamilmani1989 We know that azure cni integration for windows is not finished. We will take up windows/azure-cni once we sort out any remaining issues with Linux.

**Comment by JiangtianLi** [comment]
@sharmasushant Thanks. The issue I referred to is without azure network policy and cni, but the config in windows cni.

**Comment by jackfrancis** [comment]
@JiangtianLi rebase should be relatively easy, it's due to this reorganization of the `parts/` directory:

https://github.com/Azure/acs-engine/commit/30ce15e3096db424cb4ac4617347d8e74b9eb90d

**Comment by JiangtianLi** [comment]
@jackfrancis Thanks! Will rebase after fix the Windows subnet issue.

**Comment by feiskyer** [comment]
> Will rebase after fix the Windows subnet issue.

@JiangtianLi Do you explain the problem in details?

**Comment by jay-stillman** [comment]
@JiangtianLi can you update us on the estimated time to get the checks completed? appears to be on hold currently

**Comment by JiangtianLi** [comment]
@feiskyer The root cause is that Windows container network subnet configured only supports */24 CIDR and custom vnet usually configures master and agent subnet in range that doesn't work with Windows container network limitation.
@jay-stillman This is a Windows platform issue and I am working with Windows networking team to address it. There is no estimate yet but I will update asap.

**Comment by jay-stillman** [comment]
@JiangtianLi with regards to the windows container network only supporting a /24 subnet, then surely this shouldnt be an issue based on the fact that when creating an agent pool with custom vnet we define each agent pool subnet? So if we have the windows agent pool configured to a /34 this will work? or is this a larger issue based on the master networking to nodes?

**Comment by JiangtianLi** [comment]
@jay-stillman To clarify, in order for Windows node to communicate with master node or agent node, all the nodes need to be in the /24 subnet. For example, if the Windows node has IP address 10.240.0.4, the master node has IP address 10.240.255.5 and the other agent node has 10.240.0.5, the master node can't talk to Windows node while the agent node can. You need to configure master and agent vnet to be in the same 24 range.

**Comment by jay-stillman** [comment]
@JiangtianLi this is not correct..... the vnet cidr can be somethign such as 10.2.0.0/16 while the master subnet can be something like 10.2.10.0/24 and the linux pool can be something like 10.2.16.0/21 if running 5 agent nodes (each node requires its own /24 subnet) this config works with custom subnet... even with multiple agent pools. 

So I am guessing you are actually referring to something else, ie related to windows networking.... however if all the subnets are in the vnet and the agent pool subnets are bound to the route table, then they can still route.....

Can you provide some clearer detail on this, as the above works and is how we for one run our various acs environments

**Comment by JiangtianLi** [comment]
@jay-stillman Sorry for the confusion. There is no limitation to configure vnet cidr in custom vnet on Azure. The limitation is in Windows container networking on Windows node, and that limits the connection/routing to Windows POD from another subnet, i.e, master's node. Linux agent has no such issue. It is Windows container networking only.

**Comment by jay-stillman** [comment]
@JiangtianLi can you please provide any indication to when this will be resolved?

We currently are unable to use windows containers.... Is there any work around for this?

**Comment by JiangtianLi** [comment]
/cc @madhanrm @dineshgovindasamy

@jay-stillman Sorry about the delay. We are working with networking team (cc-ed) for this. I don't see a straightforward workaround at this point but @madhanrm @dineshgovindasamy can chime in.

**Comment by lastcoolnameleft** [comment]
Given the limitation, I understand that it's currently not possible to deploy Windows Containers to an existing Vnet that are not properly sized; however, it is possible to deploy a Hybrid cluster into an existing Vnet that does match how Windows Container Networking expects the subnet to look?

I tried doing that with:

```
az network vnet create -g acs-engine-vnet-hybrid -n acs-engine-hybrid-vnet --address-prefixes 10.0.0.0/16 --subnet-name mgmt --subnet-prefix 10.0.0.0/24
```

And this as my template:
```
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "acs-engine-vnet-hybrid",
      "vmSize": "Standard_A2_v2",
      "vnetSubnetId": "/subscriptions/<sub-id-removed>/resourceGroups/acs-engine-vnet-hybrid/providers/Microsoft.Network/virtualNetworks/acs-engine-hybrid-vnet/subnets/mgmt",
      "storageProfile" : "ManagedDisks",
      "firstConsecutiveStaticIP": "10.0.0.5",
      "vnetCidr": "10.0.0.0/16"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 1,
        "vmSize": "Standard_D2_v2",
        "vnetSubnetId": "/subscriptions/<sub-id-removed>/resourceGroups/acs-engine-vnet-hybrid/providers/Microsoft.Network/virtualNetworks/acs-engine-hybrid-vnet/subnets/mgmt",
        "storageProfile" : "ManagedDisks",
        "availabilityProfile": "AvailabilitySet",
        "customNodeLabels": {
          "services": "linux"
        }
      },
      {
        "name": "agentpool2",
        "count": 1,
        "vmSize": "Standard_D2_v2",
        "vnetSubnetId": "/subscriptions/<sub-id-removed>/resourceGroups/acs-engine-vnet-hybrid/providers/Microsoft.Network/virtualNetworks/acs-engine-hybrid-vnet/subnets/mgmt",
        "storageProfile" : "ManagedDisks",
        "availabilityProfile": "AvailabilitySet",
        "osType" : "Windows",
        "customNodeLabels": {
          "services": "windows"
        }
      }
```

But instead got the following error:

```
•100% ➜ acs-engine deploy --api-model kubernetes-hybrid.json --subscription-id $SUBSCRIPTION_ID --location southcentralus --resource-group acs-engine-vnet-hybrid
INFO[0014] Starting ARM Deployment (acs-engine-vnet-hybrid-1925927182). This will take some time...
INFO[0594] Finished ARM Deployment (acs-engine-vnet-hybrid-1925927182).
ERRO[0594] {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidTemplate\",\r\n    \"message\": \"Unable to process template language expressions for resource '/subscriptions/<sub-id-removed>/resourceGroups/acs-engine-vnet-hybrid/providers/Microsoft.Compute/virtualMachines/18238k8s9010' at line '1' and column '39328'. 'The template variable 'subnet' is not found. Please see https://aka.ms/arm-template/#variables for usage details.'\"\r\n  }\r\n}"}]}}
FATA[0594] resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."
```

**Comment by JiangtianLi** [comment]
@lastcoolnameleft You are using master HEAD, not this PR, right? The error is due to https://github.com/Azure/acs-engine/blob/master/parts/k8s/kuberneteswindowssetup.ps1#L57 and the same as https://github.com/Azure/acs-engine/issues/1767. It is because if your json defines custom vnet and variable subnet is not defined in that case https://github.com/Azure/acs-engine/blob/master/parts/k8s/kubernetesmastervars.t#L199

**Comment by lastcoolnameleft** [comment]
My apologies, I posted my comment in the PR, when I meant to post it in the issue.

That said, I believe that there's still an issue where the variable subnet is not defined by the output template and should be caught by the ACS-engine validator and fail the generation prior to trying to deploy.

**Comment by mboret** [comment]
@JiangtianLi I've tested this PR with an hybrid cluster and a custom Vnet and I've been able to create a cluster. I'm using this template:

```
{
    "apiVersion": "vlabs",
    "properties": {
      "orchestratorProfile": {
        "orchestratorType": "Kubernetes",
        "orchestratorRelease": "1.8",
        "kubernetesConfig": {
          "networkPolicy": "none",
          "enableRbac": true
        }
      },
      "masterProfile": {
        "count": 2,
        "dnsPrefix": "DNSPREFIX",
        "vmSize": "Standard_D2_v2",
        "vnetSubnetId": "/subscriptions/SUBSCRIPTION/resourceGroups/RESOURCEGROUP/providers/Microsoft.Network/virtualNetworks/VNETNAME/subnets/SUBNETNAME",
        "firstConsecutiveStaticIP": "10.198.3.239",
        "OSDiskSizeGB": 50
      },
      "agentPoolProfiles": [
        {
          "name": "linuxpool",
          "count": 2,
          "vmSize": "Standard_D2_v2",
          "availabilityProfile": "AvailabilitySet",
          "OSDiskSizeGB": 50,
          "distro": "ubuntu",
          "vnetSubnetId": "/subscriptions/SUBSCRIPTION/resourceGroups/RESOURCEGROUP/providers/Microsoft.Network/virtualNetworks/VNETNAME/subnets/SUBNETNAME"          
        },
        {
          "name": "windowspool",
          "count": 2,
          "vmSize": "Standard_D2_v3",
          "availabilityProfile": "AvailabilitySet",
          "osType": "Windows",
          "OSDiskSizeGB": 100,
          "vnetSubnetId": "/subscriptions/SUBSCRIPTION/resourceGroups/RESOURCEGROUP/providers/Microsoft.Network/virtualNetworks/VNETNAME/subnets/SUBNETNAME"                
        }
      ],
      "windowsProfile": {
        "adminUsername": "ADMINUSERWINDOWS",
        "adminPassword": "WINDOWSPASSWORD"
      },
      "linuxProfile": {
        "adminUsername": "ADMINUSERLINUX",
        "ssh": {
          "publicKeys": [
            {
              "keyData": "LINUXPUBLICKEY"
            }
          ]
        }
      },
      "servicePrincipalProfile": {
        "clientId": "SPNAME",
        "secret": "SPPASSWORD"
      }
    }
  }
  ```

After the cluster creation I've updated the vnet subnets to add the k8s cluster route table.

Few points:

1) The most recent k8s version that I've been able to deploy was the 1.8.3 
2) I've issue with the deployment of image on the windows node but seems related to the RS3 issue because I'm able to deploy microsoft/windowsservercore:1709 image. 
3)  I cannot see the Windows node resource consumption(seems fixed with the k8s 1.9.3)
4) The Windows node description show:  "Container Runtime Version: docker://Unknown "    (???) but I'm able to deploy container(ex: microsoft/windowsservercore:1709) on this node.

**Comment by mboret** [comment]
@JiangtianLi Any update about this issue?

**Comment by JiangtianLi** [comment]
@mboret acs-engine has switched to use Azure CNI as default for Windows cluster and custom VNET is supported with Azure CNI. With kubenet, custom VNET is still under investigation.

**Comment by mboret** [comment]
@JiangtianLi  This still doesn't work for me with another acs-engine version and an hybrid cluster with custom VNET. Even if I'm using Azure CNI(I ran into the same issue: https://github.com/Azure/acs-engine/issues/2565 with acs-engine v0.15.0 and kubernetes 1.10 and the same defintion I've post previously). 

Summary, I'm able to deploy an hybrid cluster with custom Vnet, only if I'm using this PR with kubenet.

**Comment by mboret** [comment]
For sure. Created: https://github.com/Azure/acs-engine/issues/2612

**Pull request closed without merging**
