### PR TITLE
Add e2e test for openshift vnet

### PR DESCRIPTION
**Pull request by ritazh**
**What this PR does / why we need it**:
Add e2e test for Openshift with vnet

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

### CODE REVIEW

**Comment by kargakis** [comment]
/hold

I think this should be a separate test vs updating the existing test.

@jim-minter @pweil-

**Comment by kargakis** [comment]
Fixes https://github.com/Azure/acs-engine/issues/2985

**Comment by kargakis** [comment]
We are flakying a lot on https://github.com/Azure/acs-engine/issues/2982

**Comment by jim-minter** [comment]
I agree this should be a separate test.
@ritazh please cc @jim-minter @kargakis @pweil- on openshift-related PRs

**Comment by kwoodson** [comment]
@ritazh, could you rebase and fix the conflicts for this PR?  Thanks!

**Comment by jim-minter** [comment]
@kwoodson this needs to be an additional test, not replacing the existing one - can you open a new PR based on Rita's work to take this forward?

**Comment by kwoodson** [comment]
@jim-minter @ritazh 

I have added https://github.com/Azure/acs-engine/pull/3274 to take the place of this PR.  Feel free to comment there.

**Pull request closed without merging**
