### PR TITLE
openshift: workaround other bad images with an additional umount

### LINKED ISSUE #3313: openshift: docker and waagent race condition for storage drive
On startup the waagent process and docker race to format disks:

From chat:
```
[12:36:46] <jminter> waagent and docker race at startup
[12:36:51] <jminter> docker starts
[12:37:09] <jminter> docker mounts sda2->/var/lib/docker/containers
[12:37:19] <jminter> waagent formats sdb1, mounts sdb1->/var/lib/docker
[12:37:31] <jminter> docker falls to pieces in a sorry heap
```

Mount command:
```
[root@ocp-master-24079797-0 ~]# mount
/dev/sda1 on / type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
/dev/sda2 on /var type xfs (rw,relatime,seclabel,attr2,inode64,grpquota)
/dev/sda2 on /var/lib/docker/containers type xfs (rw,relatime,seclabel,attr2,inode64,grpquota)
/dev/sda2 on /var/lib/docker/overlay2 type xfs (rw,relatime,seclabel,attr2,inode64,grpquota)
/dev/sdb1 on /var/lib/docker type xfs (rw,relatime,seclabel,attr2,inode64,grpquota)
```
docker-storage-setup file
```
[root@ocp-master-24079797-0 ~]# cat /etc/sysconfig/docker-storage-setup 
STORAGE_DRIVER=overlay2
```

Jim's first PR to tell waagent to not format the disk.
https://github.com/openshift/openshift-ansible/pull/8875

### PR DESCRIPTION
**Pull request by jim-minter**
fixes #3313

### CODE REVIEW

**Comment by jim-minter** [comment]
@kwoodson fyi
@CecileRobertMichon please can you hit merge on this straight?

**Comment by CecileRobertMichon** [comment]
@jim-minter done

**Comment by jim-minter** [comment]
many thanks @CecileRobertMichon

**Pull request merged**
