### PR TITLE
undo cilium changes to base64 encoding

### PR DESCRIPTION
**Pull request by jackfrancis**
**What this PR does / why we need it**: Reverts part of #3248 

Our cilium E2E tests have been broken since that change.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**If applicable**:
- [ ] documentation
- [ ] unit tests
- [ ] tested backward compatibility (ie. deploy with previous version, upgrade with this branch)

**Release note**:

```
undo cilium changes to base64 encoding
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
@PaulCharlton I've reverted the cilium changeset from #3248 because we've been unable to build v1.9._n_ clusters since then. We use the following example api model in our tests:

https://github.com/Azure/acs-engine/blob/master/examples/networkpolicy/kubernetes-cilium.json

Is there a particular subset of k8s APIs that your change was targeted toward? You should be able to repro by building a cilium-enabled v1.9.8 cluster using the above api model against master. What we're seeing is that we have no name resolution. This PR fixes that.

**Comment by PaulCharlton** [comment]
@jackfrancis thanks -- I had imagined that the CI testing would have picked up such an inconsistency.  I did not personally test against 1.9.   My change set was specifically needed for the etcd encryption key.

**Comment by jackfrancis** [comment]
@PaulCharlton Currently our CI testing doesn't include cilium inline. This PR doesn't revert the changes to `base64.StdEncoding` (from `base64.URLEncoding`). Any concerns with merging this reversion to the cilium-specific cert paving?

**Comment by PaulCharlton** [comment]
LGTM

**Comment by jackfrancis** [comment]
Thanks for weighing in @PaulCharlton :)

**Pull request merged**
