### PR TITLE
Move docker version to 1.13.1 for DCOS

### PR DESCRIPTION
**Pull request by jsilberm**
**What this PR does / why we need it**:
Moves the docker version for DCOS under acs-engine from 1.11 to 1.13.1.
This puts acs-engine in sync with the Mesosphere DCOS docker version.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

https://github.com/Azure/acs-engine/issues/816

**Special notes for your reviewer**:

**Release note**:

```release-note
```

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/818)

### CODE REVIEW

**Comment by JackQuincy** [comment]
@wangtt03 can we get this file in the china mirror and can you ping back here with the url.
@dmitsh is it okay to use the mesosphere mirror or do we need to use the cdn?

**Comment by JackQuincy** [comment]
@acs-bot test this please

**Comment by jsilberm** [comment]
Help please.    I don't have any visibiity in to what check failed.   Can you please provide access/share?

**Comment by JackQuincy** [comment]
Our ci tests are broken, that said this failure was caused due to not regenerating templates.go since the last time one of the files in /parts was modified. Easiest way to regenerate is make build, and you can verify with make ci. Make sure you are using go 1.8 as it changes the templates.go slightly and you won't pass our server ci if you use a different version. Easiest way to not have a go version issue is to use the dev environment scripts in /scripts

**Comment by jsilberm** [comment]
So I will need to add "templates.go" to the commit?   (and do so before someone else checks in anything to /parts?)

**Comment by JackQuincy** [comment]
You will have merge conflicts and have to rebase/merge whenever someone checks into parts, I know its annoying but it was the best way for other requirements we have. That wouldn't cause this though. This problem is that you didn't run make build and add templates.go to the commit.

**Comment by jsilberm** [comment]
Any insight as to which proto package needs to be upgraded?
< // This is a compile-time assertion to ensure that this generated file
< // is compatible with the proto package it is being compiled against.
< // A compilation error at this line likely means your copy of the
< // proto package needs to be updated.
< const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package
<

**Comment by JackQuincy** [comment]
you don't need to hand edit. make build will make the necessary changes

**Comment by jsilberm** [comment]
I didn't hand edit.  I tried this also in the scripts/devenv.   The devenv was missing both "protoc" and "protoc-gen-go" --- and those I installed by hand.   I'm getting 'make build' to work fine.  'make ci' keeps failing as below:

+ diff -I '.*bindataFileInfo.*' --exclude=.git -r /gopath/src/github.com/portworx/acs-engine/scripts/.. /tmp/tmp.XVnwts8xBM
diff -I '.*bindataFileInfo.*' '--exclude=.git' -r /gopath/src/github.com/portworx/acs-engine/scripts/../vendor/github.com/onsi/gomega/ghttp/protobuf/simple_message.pb.go /tmp/tmp.XVnwts8xBM/vendor/github.com/onsi/gomega/ghttp/protobuf/simple_message.pb.go
1c1
< // Code generated by protoc-gen-go. DO NOT EDIT.
---
> // Code generated by protoc-gen-go.
2a3
> // DO NOT EDIT!
24,29d24
< // This is a compile-time assertion to ensure that this generated file
< // is compatible with the proto package it is being compiled against.
< // A compilation error at this line likely means your copy of the
< // proto package needs to be updated.
< const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package
<
37,40c32,34
< func (m *SimpleMessage) Reset()                    { *m = SimpleMessage{} }
< func (m *SimpleMessage) String() string            { return proto.CompactTextString(m) }
< func (*SimpleMessage) ProtoMessage()               {}
< func (*SimpleMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }
---
> func (m *SimpleMessage) Reset()         { *m = SimpleMessage{} }
> func (m *SimpleMessage) String() string { return proto.CompactTextString(m) }
> func (*SimpleMessage) ProtoMessage()    {}
61,78d54
< }
<
< func init() {
< 	proto.RegisterType((*SimpleMessage)(nil), "protobuf.SimpleMessage")
< }
<
< func init() { proto.RegisterFile("simple_message.proto", fileDescriptor0) }
<
< var fileDescriptor0 = []byte{
< 	// 114 bytes of a gzipped FileDescriptorProto
< 	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0xce, 0xcc, 0x2d,
< 	0xc8, 0x49, 0x8d, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
< 	0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a, 0x4e, 0x5c, 0xbc, 0xc1, 0x60, 0x15, 0xbe, 0x10,
< 	0x05, 0x42, 0xc2, 0x5c, 0xdc, 0x29, 0xa9, 0xc5, 0xc9, 0x45, 0x99, 0x05, 0x25, 0x99, 0xf9, 0x79,
< 	0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0x9c, 0x42, 0x5c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x4c, 0x0a, 0x4c,
< 	0x1a, 0xac, 0x42, 0x02, 0x5c, 0x1c, 0xb9, 0xa9, 0x25, 0x89, 0x29, 0x89, 0x25, 0x89, 0x12, 0xcc,
< 	0x0a, 0x8c, 0x1a, 0x9c, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x92, 0xa0, 0xea, 0xdb, 0x64, 0x00,
< 	0x00, 0x00,
+ echo 'go generate produced changes that were not already present'
go generate produced changes that were not already present
+ exit 1
+ rm -rf /tmp/tmp.XVnwts8xBM
Makefile:35: recipe for target 'validate-generated' failed
make: *** [validate-generated] Error 1

**Comment by JackQuincy** [comment]
we don't use those packages. I'm not sure why they are in templates.go. We use 

> go get github.com/jteeuwen/go-bindata/... 

which is ran when you do make build. I'd revert the file and just do make build from inside the dev env container and it should update it for you.

**Comment by jsilberm** [comment]
Sorry for these issues.  But now you "should" be able to reproduce what I'm seeing:

   go get github.com/portworx/acs-engine
   cd $GOPATH/src/github.com/portworx/acs-engine
   make build

[...]
vendor/github.com/onsi/gomega/ghttp/test_server_test.go
vendor/github.com/onsi/gomega/ghttp/protobuf/protobuf.go
vendor/github.com/onsi/gomega/ghttp/protobuf/protobuf.go:3: running "protoc": exec: "protoc": executable file not found in $PATH

**Comment by JackQuincy** [comment]
@acs-bot test this please

**Comment by jsilberm** [comment]
Sorry again for the confusion on my part.  Thanks again for your time.
Anything else needed here?

**Comment by jsilberm** [comment]
Hi @JackQuincy :  Any other action needed from me here?  Appreciate your help.  Thanks.

**Comment by JackQuincy** [comment]
We need to get the the changes into china too. I just don't know if that mirror would already have the needed files. @ritazh can you(or do you know who can) help replicate the new docker build into the china cloud storage account?

**Comment by JackQuincy** [comment]
Changing my mind will update the issue and leave it open to track the china change.

**Pull request merged**
