### PR TITLE
Fix calico for k8s 1.12

### LINKED ISSUE #4035: No networks found in /etc/cni/net.d
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
0.23.1
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.12.1

**What happened**:
I deployed a new cluster with VMSS, but when I run `kubectl get nodes` both the master and agent is stuck in NotReady

```
NAME                                STATUS     ROLES     AGE       VERSION
k8s-linuxpool-26767313-vmss000000   NotReady   agent     25m       v1.12.1
k8s-master-26767313-0               NotReady   master    25m       v1.12.1
```

Looking at the logs on the master I keep getting this

```
Oct 15 19:39:49 k8s-master-26767313-0 kubelet[8227]: I1015 19:39:49.259332    8227 azure_dd.go:191] got a matching size in getMaxDataDiskCount, Name: Standard_D2_v2, MaxDataDiskCount: %!s(int32=8)
Oct 15 19:39:51 k8s-master-26767313-0 kubelet[8227]: W1015 19:39:51.408636    8227 cni.go:188] Unable to update cni config: No networks found in /etc/cni/net.d
Oct 15 19:39:51 k8s-master-26767313-0 kubelet[8227]: E1015 19:39:51.408753    8227 kubelet.go:2167] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Oct 15 19:39:56 k8s-master-26767313-0 kubelet[8227]: W1015 19:39:56.409604    8227 cni.go:188] Unable to update cni config: No networks found in /etc/cni/net.d
Oct 15 19:39:56 k8s-master-26767313-0 kubelet[8227]: E1015 19:39:56.410079    8227 kubelet.go:2167] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Oct 15 19:39:59 k8s-master-26767313-0 kubelet[8227]: I1015 19:39:59.278270    8227 azure_dd.go:191] got a matching size in getMaxDataDiskCount, Name: Standard_D2_v2, MaxDataDiskCount: %!s(int32=8)
Oct 15 19:40:01 k8s-master-26767313-0 kubelet[8227]: W1015 19:40:01.411396    8227 cni.go:188] Unable to update cni config: No networks found in /etc/cni/net.d
Oct 15 19:40:01 k8s-master-26767313-0 kubelet[8227]: E1015 19:40:01.411514    8227 kubelet.go:2167] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Oct 15 19:40:06 k8s-master-26767313-0 kubelet[8227]: W1015 19:40:06.412430    8227 cni.go:188] Unable to update cni config: No networks found in /etc/cni/net.d
Oct 15 19:40:06 k8s-master-26767313-0 kubelet[8227]: E1015 19:40:06.412565    8227 kubelet.go:2167] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Oct 15 19:40:09 k8s-master-26767313-0 kubelet[8227]: I1015 19:40:09.289949    8227 azure_dd.go:191] got a matching size in getMaxDataDiskCount, Name: Standard_D2_v2, MaxDataDiskCount: %!s(int32=8)
Oct 15 19:40:11 k8s-master-26767313-0 kubelet[8227]: W1015 19:40:11.413686    8227 cni.go:188] Unable to update cni config: No networks found in /etc/cni/net.d
Oct 15 19:40:11 k8s-master-26767313-0 kubelet[8227]: E1015 19:40:11.414202    8227 kubelet.go:2167] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Oct 15 19:40:16 k8s-master-26767313-0 kubelet[8227]: W1015 19:40:16.415124    8227 cni.go:188] Unable to update cni config: No networks found in /etc/cni/net.d
Oct 15 19:40:16 k8s-master-26767313-0 kubelet[8227]: E1015 19:40:16.415229    8227 kubelet.go:2167] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Oct 15 19:40:19 k8s-master-26767313-0 kubelet[8227]: I1015 19:40:19.302982    8227 azure_dd.go:191] got a matching size in getMaxDataDiskCount, Name: Standard_D2_v2, MaxDataDiskCount: %!s(int32=8)
Oct 15 19:40:21 k8s-master-26767313-0 kubelet[8227]: W1015 19:40:21.416138    8227 cni.go:188] Unable to update cni config: No networks found in /etc/cni/net.d
Oct 15 19:40:21 k8s-master-26767313-0 kubelet[8227]: E1015 19:40:21.416613    8227 kubelet.go:2167] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```

**What you expected to happen**:
K8S nodes get fully up and running

**How to reproduce it** (as minimally and precisely as possible):
Deploy a new cluster, I'm not sure if it is related to VMSS

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by oivindoh**
**What this PR does / why we need it**:

Allows calico-node daemonset to be scheduled, and thus k8s 1.12 to be used with calico again.

**Which issue this PR fixes**

Fixes #4035 - in line with comments there and https://github.com/coreos/flannel/pull/1045

**Special notes for your reviewer**:

Successfully tested deployment using the following input model:

```json
{
  "apiVersion": "vlabs",
  "properties": {
    "servicePrincipalProfile": {
      "secret": "x",
      "clientId": "x"
    },
    "orchestratorProfile": {
      "orchestratorRelease": "1.12",
      "kubernetesConfig": {
        "kubeletConfig": {
          "--max-pods": "80"
        },
        "etcdDiskSizeGB": "256",
        "dockerEngineVersion": "17.03.*",
        "networkPolicy": "calico",
        "enableRbac": true
      },
      "orchestratorType": "Kubernetes"
    },
    "agentPoolProfiles": [
      {
        "availabilityProfile": "AvailabilitySet",
        "count": 1,
        "vmSize": "Standard_D4s_v3",
        "name": "linux1",
        "distro": "aks",
        "acceleratedNetworkingEnabled": true,
        "storageProfile": "ManagedDisks"
      }
    ],
    "linuxProfile": {
      "adminUsername": "x",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "x"
          }
        ]
      }
    },
    "masterProfile": {
      "vmSize": "Standard_D2s_v3",
      "count": 1,
      "dnsPrefix": "112fixcalico",
      "distro": "aks"
    }
  }
}
```

**If applicable**:
- [ ] documentation
- [ ] unit tests
- [ ] tested backward compatibility (ie. deploy with previous version, upgrade with this branch)

**Release note**:

```release-note
Calico addon now works with Kubernetes 1.12
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
Hi @oivindoh, is this fix only for k8s 1.12 (and above)? I.e., what are the effects of this change on cluster 1.11 and below?

Thanks for this!

**Comment by oivindoh** [comment]
The fix is for 1.12 because it introduces more NoSchedule taints, but should be backward-compatible.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#toleration-v1-core

I believe tolerating any form of noschedule taint should be ok here since this is a critical cluster component.

**Comment by jackfrancis** [comment]
@oivindoh our tests on < 1.12 clusters failed, so I accepted your changes for 1.12 and greater (see my follow-up commit)

**Pull request merged**
