### PR TITLE
Add support for Kubernetes 1.12.0

### PR DESCRIPTION
**Pull request by mboersma**
**What this PR does / why we need it**:

See https://github.com/kubernetes/kubernetes/releases/tag/v1.12.0
and https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md#v1120

TODO:

- [x] upload Windows binary

**If applicable**:
- [ ] documentation
- [ ] unit tests
- [ ] tested backward compatibility (ie. deploy with previous version, upgrade with this branch)

**Release note**:

```release-note
Add support for Kubernetes 1.12.0
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
HPA is failing after 1.11-->1.12 upgrades.

```
$ kubectl describe hpa php-apache-kubernetes-uksouth-30786-843
Name:                                                  php-apache-kubernetes-uksouth-30786-843
Namespace:                                             default
Labels:                                                <none>
Annotations:                                           <none>
CreationTimestamp:                                     Tue, 02 Oct 2018 16:04:08 +0000
Reference:                                             Deployment/php-apache-kubernetes-uksouth-30786-843
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  0% (0) / 5%
Min replicas:                                          1
Max replicas:                                          10
Deployment pods:                                       1 current / 1 desired
Conditions:
  Type            Status  Reason            Message
  ----            ------  ------            -------
  AbleToScale     True    ReadyForNewScale  recommended size matches current size
  ScalingActive   True    ValidMetricFound  the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited  True    TooFewReplicas    the desired replica count is increasing faster than the maximum scale rate
Events:
  Type     Reason                        Age                From                       Message
  ----     ------                        ----               ----                       -------
  Warning  FailedGetResourceMetric       38m (x3 over 39m)  horizontal-pod-autoscaler  unable to get metrics for resource cpu: no metrics returned from resource metrics API
  Warning  FailedComputeMetricsReplicas  38m (x3 over 39m)  horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
```

**Comment by jackfrancis** [comment]
Confirmed that upgrading clusters does not deliver updated component versions:

```
$ kubectl get nodes
NAME                        STATUS   ROLES    AGE   VERSION
k8s-agentpool1-16834821-1   Ready    agent    55m   v1.12.0
k8s-master-16834821-0       Ready    master   77m   v1.12.0
$ kubectl describe pod metrics-server-789c47657d-jc6lh -n kube-system | grep 'Image\:'
    Image:         k8s.gcr.io/metrics-server-amd64:v0.2.1
$ kubectl describe pod heapster-855c6c8b5b-6jsn7 -n kube-system | grep 'Image\:'
    Image:         k8s.gcr.io/heapster-amd64:v1.5.3
    Image:         k8s.gcr.io/addon-resizer:1.8.1
$ kubectl describe pod kube-addon-manager-k8s-master-16834821-0 -n kube-system | grep 'Image\:'
    Image:          k8s.gcr.io/kube-addon-manager-amd64:v8.7
```

Also, cluster-autoscaler is not present in `/etc/kubernetes/addons/`.

**Comment by mboersma** [comment]
Actually `k8s.gcr.io/kube-addon-manager-amd64:v8.7` is correct post-upgrade. So it looks like only addons-related components failed to be updated.

**Comment by jackfrancis** [comment]
1.12 upgrade and scale tests passed

**Pull request merged**
