### PR TITLE
Fix an issue caused by WinNAT

### PR DESCRIPTION
**Pull request by JiangtianLi**
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/520)

### CODE REVIEW

**Comment by JackQuincy** [comment]
@acs-bot test this please

**Comment by JiangtianLi** [comment]
@acs-bot test this please

**Comment by JiangtianLi** [comment]
@JackQuincy Yes, we need to merge properly. We can hold this until 1.6 is in.

**Comment by JiangtianLi** [comment]
@acs-bot test this please

**Comment by JiangtianLi** [comment]
@acs-bot test this please

**Pull request merged**
