### PR TITLE
Create a --set flag for generate

### LINKED ISSUE #733: Create a --set flag for generate
#**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

It would be nice if you could pass in the custom values for an acs cluster via the command line instead of having to edit a file on disk. This would help facilitate more automation around the creation of clusters. It would work just like the helm `--set` flag does now which takes a comma separated list of key/value pairs. So an example could look like the following:

```
acs-engine generate --set \
"masterProfile.count=3,\
agentPoolProfile.count=4,\
windowsProfile.adminPassword=${SOME_ENV_VAR_FETCHED_FROM_VAULT}" \
examples/kubernetes.json

### PR DESCRIPTION
**Pull request by jcorioland**
**What this PR does / why we need it**: this PR adds support for a --flag to the generate command to make possible to override values from the api model JSON file using the CLI:

`acs-engine generate --set linuxProfile.adminUsername=jcorioland,agentPoolProfiles[0].count=5 kubernetes.json`

**Which issue this PR fixes**: fixes #733 

**Special notes for your reviewer**:

It supports all fields and arrays under the `properties` node.
It introduces some refactoring of the generate command itself and new unit tests.
It adds a dependency to [Jeffail/gabs](https://github.com/Jeffail/gabs) for JSON manipulations.

**If applicable**:
- [x] documentation
- [x] unit tests

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@jcorioland did you decide to add the --set flag to deploy in a separate PR?

**Comment by jcorioland** [comment]
@CecileRobertMichon yes, I will do that in another PR as it may lead to a some refactoring to share code between generate and deploy command. I've created an issue (#2796) to work on the deploy command later.

**Comment by flyboarder** [comment]
@jcorioland can you confirm this works for setting the `linuxProfile.ssh.publicKeys[0].keyData='rsa ABC...`

I am getting the following output:
```
acs-engine generate --api-model ./config/develop.json --set servicePrincipalProfile.clientID=test,servicePrincipalProfile.secret=test,linuxProfile.ssh.publicKeys[0].keyData="test" 
INFO[0000] --set flag array value detected. Name: linuxProfile.ssh.publicKeys, Index: 0, PropertyName: keyData 
INFO[0000] new api model file has been generated during merge: /tmp/mergedApiModel136504300 
INFO[0000] Error returned by LoadContainerService: Namespace Properties.LinuxProfile.SSH.PublicKeys is not caught, Key: 'Properties.LinuxProfile.SSH.PublicKeys' Error:Field validation for 'PublicKeys' failed on the 'required' tag 
FATA[0000] error loading API model in generateCmd: error parsing the api model: Namespace Properties.LinuxProfile.SSH.PublicKeys is not caught, Key: 'Properties.LinuxProfile.SSH.PublicKeys' Error:Field validation for 'PublicKeys' failed on the 'required' tag 
```

**Comment by jcorioland** [comment]
@flyboarder hmm, this is weird. I've just tested with a sample json api model file and it seems to work:

```
./bin/acs-engine generate --api-model ./pkg/acsengine/testdata/simple/kubernetes.json --set servicePrincipalProfile.clientID=test,servicePrincipalProfile.secret=test,linuxProfile.ssh.publicKeys[0].keyData="test"
INFO[0000] --set flag array value detected. Name: linuxProfile.ssh.publicKeys, Index: 0, PropertyName: keyData
INFO[0000] new api model file has been generated during merge: /tmp/mergedApiModel819228615
INFO[0000] Generating assets into _output/masterdns1...
root@e52276aaed30:/gopath/src/github.com/Azure/acs-engine# cat /tmp/mergedApiModel819228615
{"apiVersion":"vlabs","properties":{"agentPoolProfiles":[{"availabilityProfile":"AvailabilitySet","count":3,"name":"agentpool1","vmSize":"Standard_D2_v2"},{"availabilityProfile":"AvailabilitySet","count":3,"name":"agentpool2","vmSize":"Standard_D2_v2"}],"certificateProfile":{"apiServerCertificate":"apiServerCertificate","apiServerPrivateKey":"apiServerPrivateKey","caCertificate":"caCertificate","caPrivateKey":"caPrivateKey","clientCertificate":"clientCertificate","clientPrivateKey":"clientPrivateKey","etcdClientCertificate":"etcdClientCertificate","etcdClientPrivateKey":"etcdClientPrivateKey","etcdPeerCertificates":["etcdPeerCertificate0"],"etcdPeerPrivateKeys":["etcdPeerPrivateKey0"],"etcdServerCertificate":"etcdServerCertificate","etcdServerPrivateKey":"etcdServerPrivateKey","kubeConfigCertificate":"kubeConfigCertificate","kubeConfigPrivateKey":"kubeConfigPrivateKey"},"linuxProfile":{"adminUsername":"azureuser","ssh":{"publicKeys":[{"keyData":"test"}]}},"masterProfile":{"count":1,"dnsPrefix":"masterdns1","vmSize":"Standard_D2_v2"},"orchestratorProfile":{"orchestratorType":"Kubernetes"},"servicePrincipalProfile":{"clientID":"test","clientId":"ServicePrincipalClientID","secret":"test"}}}
``

**Pull request merged**
