### PR TITLE
Fix for loop value

### PR DESCRIPTION
**Pull request by lastcoolnameleft**
See http://stackoverflow.com/questions/4176347/using-bash-c-with-loops-and-standard-output-redirection

```
# /bin/bash -c "for i in {1..5}; do echo MyFirstApp \$i;  done"
MyFirstApp 1
MyFirstApp 2
MyFirstApp 3
MyFirstApp 4
MyFirstApp 5
# /bin/bash -c "for i in {1..5}; do echo MyFirstApp $i;  done"
MyFirstApp 5
MyFirstApp 5
MyFirstApp 5
MyFirstApp 5
MyFirstApp 5
```

### CODE REVIEW

**Comment by rutsky** [comment]
LGTM.

IMO it's better to wrap whole `bash -c` argument with single quotes:

```
/bin/bash -c 'for i in {1..5}; do echo MyFirstApp $i; done'
```

**Comment by lastcoolnameleft** [comment]
@rutsky For strings that don't require interpolation, I wholeheartedly agree.  However, in this case, we want the number, not the literal $i:

```
# /bin/bash -c 'for i in {1..5}; do echo MyFirstApp \$i; sleep 1; done'
MyFirstApp $i
MyFirstApp $i
MyFirstApp $i
MyFirstApp $i
MyFirstApp $i
# /bin/bash -c "for i in {1..5}; do echo MyFirstApp \$i; sleep 1; done"
MyFirstApp 1
MyFirstApp 2
MyFirstApp 3
MyFirstApp 4
MyFirstApp 5
```

**Comment by lastcoolnameleft** [comment]
@rutsky Fair point.  I've changed it to use single quotes.

**Comment by raveeram** [comment]
Thank you for your contribution!

**Pull request merged**
