### PR TITLE
ref(*): remove gitignored templates.go

### PR DESCRIPTION
**Pull request by seanknox**
This is a follow-up to https://github.com/Azure/acs-engine/pull/915, which added `./pkg/acsengine/templates.go` to gitignore. This removes it from the repo.

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/973)

### CODE REVIEW

**Comment by seanknox** [comment]
@dmitsh looks like we need to add a `make build` somewhere in the CI tasks. where's the right spot?

**Comment by rjtsdl** [comment]
I think it failed at `make validate-generated`. I think we can deprecate 'validate-generated'. How do you think @dmitsh

**Comment by colemickens** [comment]
Assuming this passes and we have a strategy for regurgitating this in the new RP, this LGTM.

**Comment by JackQuincy** [comment]
@colemickens we are now generating it as part of our make build-binary command.

**Comment by colemickens** [comment]
If I were better at GIFs I would insert a very celebratory jubilant GIF here. This was so painful when dealing with multi-commit PRs. This will improve life greatly. Thanks @seanknox and @JackQuincy !

**Comment by seanknox** [comment]
@colemickens 
giphy-downsized

**Pull request merged**
