### PR TITLE
Enable billing extension for AzureChinaCloud

### PR DESCRIPTION
**Pull request by karataliu**
**What this PR does / why we need it**:
Enable billing extension for AzureChinaCloud
Compute.AKS-Engine.Linux.Billing & Compute.AKS.Linux.Billing are deployed in mooncake.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**If applicable**:
- [ ] documentation
- [ ] unit tests
- [ ] tested backward compatibility (ie. deploy with previous version, upgrade with this branch)

**Release note**:
```release-note
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
future note to self: lgtm pending release of hold

**Comment by karataliu** [comment]
+Fix on comment

**Comment by CecileRobertMichon** [comment]
@karataliu please reopen in https://github.com/Azure/aks-engine if still relevant.

**Pull request closed without merging**
