### PR TITLE
Add support for using the Azure Instance Metadata service.

### LINKED ISSUE #896: Use Azure Instance Metadata service
We should explore using the new Azure Instance Metadata service to provide instance metadata for the kubelet + cloud provider.

### PR DESCRIPTION
**Pull request by brendandburns**
@colemickens @jackfrancis @seanknox

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/1036)

Fixes #896

### CODE REVIEW

**Comment by brendandburns** [comment]
Rebased, I think this is ready to merge whenever it is green.

**Comment by seanknox** [comment]
I want to merge this right after we cut v0.4.0 tomorrow, just to give us some time to find any kinks. If you give me access to your source branch and I can rebase as necessary.

**Comment by brendandburns** [comment]
@seanknox done.

**Comment by seanknox** [comment]
Awesome, excited to get this in. For maintainers with access, please hold off on merging until we cut v0.4.0. It'll go in right after that.

**Comment by seanknox** [comment]
Just realized that instance metadata is off by default (by virtue of not setting to true), is that right? If so we could merge now.

**Comment by brendandburns** [comment]
Yes, this is off by default.

**Comment by brendandburns** [comment]
Also, they're not supported except in HEAD kubernetes :)

**Comment by seanknox** [comment]
giphy 1

**Pull request merged**
