### PR TITLE
Kubernetes: disable accelerated networking if Azure CNI

### PR DESCRIPTION
**Pull request by jackfrancis**
**What this PR does / why we need it**: See #3546 and:

Azure/azure-container-networking#222

While we diagnose possible issues w/ Azure CNI on accelerated networking-backed VMs, let's disable this combination by default for folks who aren't explicitly enabling accelerated networking.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**If applicable**:
- [ ] documentation
- [ ] unit tests
- [ ] tested backward compatibility (ie. deploy with previous version, upgrade with this branch)

**Release note**:

```
Kubernetes: disable accelerated networking if Azure CNI
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
@sylr @sharmasushant FYI

**Comment by jackfrancis** [comment]
@khenidak FYI

**Comment by sharmasushant** [comment]
@jackfrancis We have done tests on several accelnet enabled VMs with Azure CNI and have not seen any kind of issues so far that can be attributed to [`Azure CNI` + `AccelNet`] combination
From our side, feel free start enabling accelnet even if Azure CNI is in use for a cluster.

**Comment by jackfrancis** [comment]
@sharmasushant this PR was never merged, so we're on the same page here

**Pull request closed without merging**
