### PR TITLE
Add flags for activating the kubernetes cert signing API.

### LINKED ISSUE #1026: Add flags for activating the kubernetes cert signing API
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): FEATURE

---
We need to add cert-signing functionality to Kubernetes API server for bootstrapping.

### PR DESCRIPTION
**Pull request by brendandburns**
**What this PR does / why we need it**:
This adds cert-signing functionality to acs-engine

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1026

**Special notes for your reviewer**:

**Release note**:
```release-note
Add support for certificate signing to the master.
```

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/1025)

### CODE REVIEW

**Comment by seanknox** [comment]
@acs-bot test this please

**Comment by seanknox** [comment]
@dmitsh This PR seems stuck in CI. Can investigate the root cause? We can discuss at standup if the team needs to take action.

**Comment by colemickens** [comment]
Do the kubelets need a flag/config change to actually start taking advantage of this for their HTTP(S) server?

**Comment by JackQuincy** [comment]
Do we care that older clusters won't have the ca.key file?

**Comment by brendandburns** [comment]
Given that we're cutting releases, can't older clusters just use an older release?

What is the general deprecation policy (it prob. doesn't exist)

Calling @seanknox @anhowe to see what they think about this...

**Comment by seanknox** [comment]
> Given that we're cutting releases, can't older clusters just use an older release?

Yep. Additionally the primary acs-engine use case is for provisioning of the cluster. Previous releases will be available for those that need older functionality.

**Comment by seanknox** [comment]
@anhowe this LGTM, let me know if you have any concerns before merging into HEAD.

**Comment by seanknox** [comment]
giphy-downsized 5

**Pull request merged**
