### PR TITLE
change default windows node network policy to Azure CNI

### PR DESCRIPTION
**Pull request by saiyan86**
**What this PR does / why we need it**:

This PR makes Azure CNI as default network policy for clusters with Windows nodes.

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by saiyan86** [comment]
@tamilmani1989 
@sharmasushant 
@jackfrancis 
@JiangtianLi

**Comment by jackfrancis** [comment]
@saiyan86 Thanks! Let's do this in `pkg/api/vlabs/const.go` instead

**Comment by saiyan86** [comment]
@jackfrancis Hi Jack, please take a look for the new change.

Thanks,
Yongli

**Comment by jackfrancis** [comment]
FYI @JiangtianLi I'm going to merge this one

**Pull request merged**
