### PR TITLE
Add codecov yaml

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**: Add a 0.5% threshold under which the codecov PR status check can be green even if coverage decreased.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**If applicable**:
- [ ] documentation
- [ ] unit tests
- [ ] tested backward compatibility (ie. deploy with previous version, upgrade with this branch)

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@jackfrancis @kargakis thoughts on making the threshold 1%?

**Comment by jackfrancis** [comment]
So if you reduce by 0.9% you're fine, but if you reduce by 1.0% you're blocked?

**Comment by CecileRobertMichon** [comment]
> So if you reduce by 0.9% you're fine, but if you reduce by 1.0% you're blocked?

Yes, if I wrote the yaml correctly that's what should happen. To be precise, 1.0% you get a green check, 1.01% you get a red cross.

**Comment by jackfrancis** [comment]
Slight preference for -0.5% instead of -1.0% tolerance. Anecdotally, how many PRs reduce coverage by more than 0.5% for good reasons?

**Pull request merged**
