### PR TITLE
Reenable azurefile test

### PR DESCRIPTION
**Pull request by PatrickLang**
**What this PR does / why we need it**:

Reenables the Windows E2E azurefiles test. I'm not aware of any bugs blocking it :)

### CODE REVIEW

**Comment by andyzhangx** [comment]
it failed at azure file PVC creation, not even ready to attach on windows agent:
```
• Failure [1806.783 seconds]
Azure Container Cluster using the Kubernetes Orchestrator
/go/src/github.com/Azure/acs-engine/test/e2e/kubernetes/kubernetes_test.go:60
  with a windows agent pool
  /go/src/github.com/Azure/acs-engine/test/e2e/kubernetes/kubernetes_test.go:742
    should be able to attach azure file [It]
    /go/src/github.com/Azure/acs-engine/test/e2e/kubernetes/kubernetes_test.go:817

    Expected error:
        <*errors.errorString | 0xc420210020>: {
            s: "Timeout exceeded (30m0s) while waiting for PersistentVolumeClaims (pvc-azurefile) to become ready",
        }
        Timeout exceeded (30m0s) while waiting for PersistentVolumeClaims (pvc-azurefile) to become ready
    not to have occurred

    /go/src/github.com/Azure/acs-engine/test/e2e/kubernetes/kubernetes_test.go:831
------------------------------
```

**Comment by PatrickLang** [comment]
Hmm, passed k8s-windows-1.9-release-e2e , k8s-windows-1.10-release-e2e on first try. rerunning the others.


@andyzhangx Do you think I should merge this as-is, or are there changes coming that could help avoid the PersistentVolumeClaims timeout?

**Comment by andyzhangx** [comment]
@PatrickLang finally I found this failure is due to a bug in v1.11, storage account creation will fail due to go sdk version upgrade: https://github.com/kubernetes/kubernetes/issues/65845
As for this test, it's a good regression test, I think we should make it merged first.  @jackfrancis @CecileRobertMichon

**Comment by PatrickLang** [comment]
I'm putting in a temporary skip for v1.11. Once we get fix merged upstream we can enable this test on v1.11+

I'm trying hard to get Windows tests passing consistently here because we need to get to a known good version of acs-engine for Kubernetes upstream testing.

**Pull request merged**
