### PR TITLE
Fix container start timeout in latest Windows image

### LINKED ISSUE #959: Container on Windows agent doesn't have outbound internet connection
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
v0.3.0
---
The container on Windows agent doesn't have outbound internet connection. Bascially, it cannot resolve the DNS.

```
PS C:\Agent> Invoke-WebRequest -Uri http://bing.com -UseBasicParsing
Invoke-WebRequest : The remote name could not be resolved: 'bing.com'
At line:1 char:1
+ Invoke-WebRequest -Uri http://bing.com -UseBasicParsing
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

However, if I RDP to the machine, and use the docker to create the same image, it can resolve the DNS and get the result.

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.6.6

**What happened**:
No outbound internet connection from container.

**What you expected to happen**:
Outbound internet connections should be allow in the container.

**How to reproduce it** (as minimally and precisely as possible):
Deploy a cluster with Windows agent.

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by JiangtianLi**
**What this PR does / why we need it**:
We switch to use "latest" Windows Server image and in recent Windows Update, the container start time takes more than the default 2 minutes. It causes subsequent code path to be executed to setup Windows container. This PR extends the timeout for Windows, specifically for start container here.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #959 

**Special notes for your reviewer**:

**Release note**:

```release-note
```

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/967)

### CODE REVIEW

**Comment by seanknox** [comment]
@JiangtianLi would this fix the outbound internet issue (https://github.com/Azure/acs-engine/issues/959)?

**Comment by JiangtianLi** [comment]
@seanknox  Yes, it is exactly to fix that issue.

**Comment by seanknox** [comment]
I'm going to manually test myself first and then merge in.

**Comment by JiangtianLi** [comment]
@seanknox Thanks. I also am doing manual test. I'll see if it is quick to add to regression test.

**Comment by robbiezhang** [comment]
@JiangtianLi does it mean we need to expect up to 10 minutes to start the Windows container?

**Comment by JiangtianLi** [comment]
@robbiezhang That parameter is the timeout limit according to [here](https://github.com/JiangtianLi/kubernetes/blob/k8swin166/cmd/kubelet/app/options/options.go#L197). So I guess the bigger, the safer. It may affect other scenario so that it wait longer time to timeout. To mitigate the issue, we need to choose some number in-between. If 5 minutes has worked for most scenario, we can use that.

**Comment by seanknox** [comment]
My understanding of this toggle is it's to short-circuit long-running Docker operations, e.g. an image pull or starting a (Windows) container. It looks like we have a performance regression with the Windows VM we're using on agents that requires us to increase the default 2m timeout to something larger. Waiting (up to) 10m on Docker operations seems reasonable in this case (sluggish Windows performance) though I'm not sure what the other operational impacts there might be. Long-term, we should of course improve the VM performance.

**Pull request merged**
