### PR TITLE
Kubernetes v1.9.4 support

### LINKED ISSUE #2151: Internal Load Balancer not automatically adding target network IP configurations
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
0.12.1
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.9.1

**What happened**:
Internal Load Balancer created and associated with availability set but no target network ip configurations 
were added. Manually adding them in the portal is a functional workaround.

**What you expected to happen**:
Minimally, the target ip configuration of the load balancer endpoints should be added.

**How to reproduce it** (as minimally and precisely as possible):
1. Deploy acs kubernetes cluster with single master, single agentpool. 
Use "availabilityProfile": "AvailabilitySet"

2. Create Kubernetes service of type LoadBalancer, annotate with "service.beta.kubernetes.io/azure-load-balancer-internal=true"

3. Observe no target network ip configurations were added to the backend pool. Test to confirm that traffic does not flow as expected.

**Anything else we need to know**:
Deployed to custom vnet

### LINKED ISSUE #2392: K8s in Azure breaks internal LB if only one service uses ILB annotation
**Is this a request for help?**:
NO
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
master-latest (cd92d6949c66be875f5708eafb371a04666181fe)
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
I have deployed fresh cluster (GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b) using acs-engine. Major configuration settings:
* RBAC on
* networking - flannel
* custom VNET
* 3 agent pools

I have noticed that if I do any change to a service using ILB annotation `service.beta.kubernetes.io/azure-load-balancer-internal: "true"`, if it's the only one service using ILB, the ILB itself is being deleted and recreated:
```
 "operationName": {
        "value": "Microsoft.Network/loadBalancers/delete",
        "localizedValue": "Microsoft.Network/loadBalancers/delete"
```
```
    "operationName": {
        "value": "Microsoft.Network/loadBalancers/write",
        "localizedValue": "Microsoft.Network/loadBalancers/write"
    },
```

The issue is that, although backend pool is created, no servers are attached to it, rendering everything behind ILB down.

While other ILB-enabled services exists, the operation is just write (with no delete first) as expected 

**What you expected to happen**:
ILB is reconfigured instead of being deleted

**How to reproduce it** (as minimally and precisely as possible):
* Deploy cluster
* create nginx with ILB
* change anything (add a port, label etc)
* observe how ILB is being deleted

### PR DESCRIPTION
**Pull request by jackfrancis**
**What this PR does / why we need it**: Adds support for Kubernetes v1.9.4

https://github.com/kubernetes/kubernetes/releases/tag/v1.9.4

Fixes #2392 
Fixes #2151

**Release note**:

```
adds Kubernetes v1.9.4 support
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
@feiskyer Created this placeholder PR to help track issues that v1.9.4 will fix. If you are aware of any others in addition to the two marked in the PR description, let me know! And thanks for tagging those as fixed by v1.9.4!

**Comment by feiskyer** [comment]
@jackfrancis kubernetes v1.9.4 released

**Comment by jackfrancis** [comment]
Thanks @feiskyer, we're on it. We will merge this when @JiangtianLi has published a Windows image.

**Comment by jackfrancis** [comment]
@feiskyer FYI we have anecdotal evidence that 1.9.4 doesn't fix the ILB issues. @lachie83 observed:

```
I0313 18:39:30.413890       1 azure_backoff.go:193] LoadBalancerClient.List(levo-cluster-5aa81894) - backoff: success
E0313 18:39:30.414016       1 service_controller.go:776] Failed to process service kube-system/kubernetes-dashboard. Retrying in 2m40s: error getting LB for service kube-system/kubernetes-dashboard: Service(kube-system/kubernetes-dashboard) - Loadbalancer not found
I0313 18:39:30.414086       1 event.go:218] Event(v1.ObjectReference{Kind:"Service", Namespace:"kube-system", Name:"kubernetes-dashboard", UID:"81333ac3-26ed-11e8-a63a-000d3afd54de", APIVersion:"v1", ResourceVersion:"475", FieldPath:""}): type: 'Warning' reason: 'CreatingLoadBalancerFailed' Error creating load balancer (will retry): error getting LB for service kube-system/kubernetes-dashboard: Service(kube-system/kubernetes-dashboard) - Loadbalancer not found
```

**Comment by feiskyer** [comment]
>  FYI we have anecdotal evidence that 1.9.4 doesn't fix the ILB issues. @lachie83 observed:

@jackfrancis Those services are ClusterIP or NodePort, azure cloud provider won't create a ILB for them. And the error message you have could be omit safely.

To create a ILB, you need a LoadBalancer service with annotation `"service.beta.kubernetes.io/azure-load-balancer-internal": "true"`

**Pull request merged**
