### PR TITLE
add node labels arg to windows setup script

### PR DESCRIPTION
**Pull request by JamesEarle**
@jackfrancis @JiangtianLi 

Addresses #563

Adding KUBELET_NODE_LABELS to ArgList, need to figure out how to access the GetAgentKubernetesLabels function from here, if possible

### CODE REVIEW

**Comment by JiangtianLi** [comment]
@JamesEarle Thanks for fixing this. It is hard to see the diff, possibly due to line endings. Can you fix it?

**Comment by JamesEarle** [comment]
@JiangtianLi my changes are the additions from line 294-299, adding "--node-labels `$KUBELET_NODE_LABELS" to the args list. I haven't completed this though, as I'm not sure how to access the func `GetAgentKubernetesLabels` in engine.go from the kuberneteswindowssetup.ps1, specifically in the `Write-KubernetesStartFiles`.

Do you know if I can do this? Working with Jack on it.

**Comment by JamesEarle** [comment]
@JiangtianLi the changes should be easier to see in the most recent commit.

**Comment by JiangtianLi** [comment]
@JamesEarle You can take a look at how windowsTelemetryGUID is passed to ps1.

**Pull request merged**
