### PR TITLE
fix(docker): don't add vendor/ to docker container, refactor container build/run

### LINKED ISSUE #1101: Building acs-engine is extremely slow in Docker container
---

**Is this an ISSUE or FEATURE REQUEST?**  Issue

---

**What version of acs-engine?**: latest

---

Building acs-engine is currently extremely slow, at least on Mac. 
Specifically, `make build` calls `go list ./…` which takes forever before listing (still hanging after 10 minutes in my case).

### PR DESCRIPTION
**Pull request by seanknox**
**What this PR does / why we need it**: 
- We want dev dependencies to be handled via the container image, not the host system. 
- Refactored build and run container process to use `make build-container` and `make run-container` respectively. 
- Removed unnecessary privileged container mode
- Ensure `.git/` is added to containers, needed for developers and how `acs-engine version` derives version.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1101

**Special notes for your reviewer**:

**Release note**:

```release-note
```

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/1206)

### CODE REVIEW

**Comment by seanknox** [comment]
@dmitsh does jenkins use `scripts/devenv.sh`? We're moving away from it in our dev workflow, but can keep the script if needed.

**Comment by jchauncey** [comment]
Im not sure i understand why we want to remove vendor/ from the build image? If you are going to do that you might as well just remove vendor/ completely from the repo. Since you will need to run a `make bootstrap` before you do anything in CI.

**Comment by seanknox** [comment]
We’re keeping vendor, just changing how it is loaded into a container: built into the image as opposed to added as a volume.

**Comment by seanknox** [comment]
Are we good here? Would like to get this in for three multiple Microsoft teams who've asked for it...

**Comment by seanknox** [comment]
> Did we get an answer to any jenkins breakage by removing scripts/devenv.sh?

Not yet.

**Comment by seanknox** [comment]
Talked with @jchauncey who suggested a better technique, closing in favor of https://github.com/Azure/acs-engine/pull/1226

**Pull request closed without merging**
