### PR TITLE
Fix prometheus extension due to renaming cse

### PR DESCRIPTION
**Pull request by ritazh**
**What this PR does / why we need it**:
Update prometheus extension with new cse naming convention
Tested this extension on both master and agent

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Fixes https://github.com/Azure/acs-engine/issues/2926

FYI @trstringer

### CODE REVIEW

**Comment by trstringer** [comment]
Looks good to me! Thanks, @ritazh! :+1: :smile:

**Comment by neurot1cal** [comment]
@CecileRobertMichon @ritazh Do we think this should resolve the issues with extensions in VMSS as well? Or was there anything specific to VMSS still that will prevent extensions from working?

**Comment by CecileRobertMichon** [comment]
@neurot1cal I think VMSS might be a separate problem. I'm working on a PR to fix it.

**Comment by CecileRobertMichon** [comment]
Yes @ritazh is correct there are two separate issues, the timeout one won't be addressed by my PR, only the naming incompatibility. PR opened at #3031.

**Pull request merged**
