### PR TITLE
Optimizing template conditional blocks in K8s templates

### PR DESCRIPTION
**Pull request by tariq1890**
Inverting blocks that have {{if not }} .. else ... patterns to use {{if ..}} else.. instead. This way it's more human-readable and intuitive.

### CODE REVIEW

**Comment by jackfrancis** [comment]
added nits, otherwise /lgtm pending E2E

**Comment by tariq1890** [comment]
@jackfrancis I have made the changes as suggested by you. if you are okay with the rest of the changes, I will commit the new ones

**Comment by tariq1890** [comment]
@mboersma Sorry I have this habit of amending and force pushing :P

**Pull request merged**
