### PR TITLE
Ensure DCOS 1.9 uses docker-engine_1.13.1

### PR DESCRIPTION
**Pull request by jsilberm**
**What this PR does / why we need it**:
Related to [PR 818](https://github.com/Azure/acs-engine/pull/818), which gets DCOS upgraded to docker-engine_1.13.1.   

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
Missed one file as it relates to DCOS 1.9.
I've got ahead and rerun 'make build && make ci' successfully --- learning from previous experiece.
Everything passed.

**Release note**:

```release-note
```

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/871)

### CODE REVIEW

**Comment by jsilberm** [comment]
Please let me know if there's something blocking on my end.  Thanks for your attention.

**Comment by JackQuincy** [comment]
@acs-bot test this please

**Comment by jsilberm** [comment]
Merge please?   Thanks.

**Comment by jsilberm** [comment]
Please?

**Pull request merged**
