### PR TITLE
Add test to prevent modifying /etc/hosts twice

### PR DESCRIPTION
**Pull request by benformosa**
**What this PR does / why we need it**:
Fixes an issue that causes docker swarm init to fail with BYO DNS

**Which issue this PR fixes**
fixes: #760

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/789)

### CODE REVIEW

**Comment by JackQuincy** [comment]
@acs-bot  test this please

**Comment by rjtsdl** [comment]
@benformosa , the test failed, because you didn't regenerate template.go file.
Do 
```
git pull 
make ci
```

Once all passed, template.go file get updated. Include that into this PR.

**Comment by JackQuincy** [comment]
please run make build(preferable in the dev env, ./scripts/devenv.sh). Uur templates are loaded into the templates.go file.

**Comment by benformosa** [comment]
@rjtsdl, @JackQuincy Thanks for the advice. I've redone the commit, including the changes to `template.go`.

**Pull request merged**
