### PR TITLE
Commit minor changes to generated code

### PR DESCRIPTION
**Pull request by cpuguy83**
It seems the generated code is slightly different than whats committed,
so this updates what's committed in the repo to what is actually being
generated.

No functional changes.

### CODE REVIEW

**Comment by tariq1890** [comment]
I don't think this should have been committed. From what I've seen, the go-bindata repo hasn't changed since this commit #3477.

**Comment by jackfrancis** [comment]
@tariq1890 you are correct :)

**Comment by cpuguy83** [comment]
Yeah, apparently my go-bindata was outdated even though I just installed it very recently ;) Will make a revert PR.

**Comment by cpuguy83** [comment]
Oh looks like @jackfrancis already took care of it!
Sorry!

**Comment by tariq1890** [comment]
I guess we really need a way of locking on to a particular go-bindata version :).

**Pull request merged**
