### PR TITLE
Update NVIDIA drivers to 396

### PR DESCRIPTION
**Pull request by wbuchwalter**
Update NVIDIA drivers from 390 to 396 to enable support for CUDA 9.2.
cc @sozercan @lachie83

### CODE REVIEW

**Comment by lachie83** [comment]
Please also update gpu.md as it references the driver version also

**Comment by jackfrancis** [comment]
Thanks for the callout @lachie83! Done.

Also @wbuchwalter, FYI, I fixed merge conflict by rebasing / force-pushing.

**Pull request merged**
