### PR TITLE
added AUTOCLEAN (=y/n) to groovy scripts

### PR DESCRIPTION
**Pull request by dmitsh**
- y : remove resource group by the end of the test
 - n : preserve resource group if the test failed

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/378)

### CODE REVIEW

**Comment by weinong** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/azure/acs-engine/378)*

**Comment by weinong** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/azure/acs-engine/378#-:-KekdrRmg_16lgpsoklo:bnfp4nl)*

**Comment by dmitsh** [comment]
@acs-bot please test this

**Comment by dmitsh** [comment]
@acs-bot test this please

**Pull request merged**
