### PR TITLE
adjust pagefile size on Windows node

### LINKED ISSUE #4013: Adjust Windows pagefile to avoid kubelet failures
@xandyzhangx ran into an issue where once some pods were scheduled, the kubelet & docker instances were up to 2GB+ and pagefile was exhausted.

We need an investigation to figure out what the right pagefile size is to avoid crashing the kubelet.

Also see #3999

### PR DESCRIPTION
**Pull request by andyzhangx**
adjust pagefile size on Windows

**What this PR does / why we need it**:
adjust pagefile size on Windows node

With this PR, the pagefileset would be like following:
```
PS D:\> wmic pagefileset
Caption             Description           InitialSize  MaximumSize  Name             SettingID
D:\ 'pagefile.sys'  'pagefile.sys' @ D:\  8096         8096         D:\pagefile.sys  pagefile.sys @ D:
```

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #4013

**Special notes for your reviewer**:

**If applicable**:
- [ ] documentation
- [ ] unit tests
- [ ] tested backward compatibility (ie. deploy with previous version, upgrade with this branch)

**Release note**:

```
adjust pagefile size on Windows node
```

@PatrickLang

### CODE REVIEW

**Comment by jackfrancis** [comment]
@PatrickLang for final review/merge

**Comment by PatrickLang** [comment]
Looks good to me. if `wmic` is ever removed, then this approach can be used instead to set it with a WMI call: https://p0w3rsh3ll.wordpress.com/2013/03/17/pagefile-configuration-and-guidance/

Looking at test failures...

**Comment by PatrickLang** [comment]
Also of note - this does require a reboot but one is done at the end of `kuberneteswindowssetup.ps1`

**Comment by PatrickLang** [comment]
re-running tests. Both timed out during windows provisioning. That could be a problem caused by this change.

**Comment by andyzhangx** [comment]
@PatrickLang How could I know which agent vm size current test is using?

**Comment by jackfrancis** [comment]
@andyzhangx https://github.com/Azure/acs-engine/blob/master/examples/e2e-tests/kubernetes/windows/definition.json

**Comment by andyzhangx** [comment]
just tried on a D2_V2 VM, it works well:
```
2018-10-24T00:30:33.0877210+00:00: Adjust pagefile size
Updating property(s) of '\\38109k8s9000\ROOT\CIMV2:Win32_PageFileSetting.Name="D:\\pagefile.sys"'

Property(s) update successful.
```

Can we get log file `c:\AzureData\CustomDataSetupScript.log` of provision failed windows node?

**Comment by andyzhangx** [comment]
How to rerun those tests?

**Comment by andyzhangx** [comment]
I got a repro which kubelet could not start up on v1.12, it's due to `client version 1.38 is too new`, below are the kubelet logs:
```
I1025 06:52:03.617775   21732 server.go:408] Version: v1.12.1
E1025 06:52:04.096501   21732 server.go:731] Kubelet needs to run as uid `0`. It is being run as -1
W1025 06:52:04.096501   21732 server.go:741] setting OOM scores is unsupported in this build
E1025 06:52:04.096501   21732 perfcounter_nodestats.go:144] Unable to get cpu perf counter data; err: unable to collect data from counter. Error code is 800007d6
I1025 06:52:04.096501   21732 kubelet.go:304] Watching apiserver
W1025 06:52:04.099505   21732 iptables.go:155] Error checking iptables version, assuming version at least 1.4.11: executable file not found in %PATH%
I1025 06:52:04.103501   21732 client.go:104] Start docker client with request timeout=2m0s
E1025 06:52:04.103501   21732 kube_docker_client.go:91] failed to retrieve docker version: Error response from daemon: client version 1.38 is too new. Maximum supported API version is 1.37
W1025 06:52:04.103501   21732 kube_docker_client.go:92] Using empty version for docker client, this may sometimes cause compatibility issue.
F1025 06:52:04.104809   21732 server.go:262] failed to run Kubelet: failed to create kubelet: failed to get docker version: Error response from daemon: client version 1.38 is too new. Maximum supported API version is 1.37
```

While If I run `docker version` command, it shows it's using `1.37`

Adjust pagefile size operation works well.
```
2018-10-25T05:45:12.3798723+00:00: Adjust pagefile size
Updating property(s) of '\\38109k8s9000\ROOT\CIMV2:Win32_PageFileSetting.Name="D:\\pagefile.sys"'
Property(s) update successful.
```

Anyway, the test failure is not related to this PR.

**Comment by andyzhangx** [comment]
rebased and let's see the test result
new CI test should include this PR since it would make the windows node more stable

**Pull request merged**
