### PR TITLE
Install image-gc configurable will sane defaults

### LINKED ISSUE #1374: Install image-gc configurable will sane defaults
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Feature request

---

**What version of acs-engine?**: All

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**:

Docker images fill the agent filesystem

**What you expected to happen**:

Setup sane defaults for and allow user-specified configuration image-gc eg.

`-image-gc-high-threshold=50 --image-gc-low-threshold=30`

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by nalthoff**
**What this PR does / why we need it**:

This enhances the k8s cluster definition to allow the user to set custom values for --image-gc-high-threshold and --image-gc-low-threshold. If the user doesn't set the values, the default k8s values are explicity set (85/80)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1374  

**Special notes for your reviewer**:

Documentation updated as well. Unit tests were not written, but if needed please let me know where/how

**Release note**:

```release-note
```
NONE

### CODE REVIEW

**Comment by SaaldjorMike** [comment]
According to https://kubernetes.io/docs/admin/kubelet/ the default high threshold is:

`      --image-gc-high-threshold int32                           The percent of disk usage after which image garbage collection is always run. (default 85)
`

but according to the docs at https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/ it seems that it is 90%?

`image-gc-high-threshold, the percent of disk usage which triggers image garbage collection. Default is 90%.`

Did I miss something or is one of those pages out of date?

**Comment by nalthoff** [comment]
@SaaldjorMike  Yup. I dug into the defaults for 1.5, 1.6 and 1.7 and decided to go with the 1.7 defaults for all of them since they were pretty similar.

**Comment by nalthoff** [comment]
@lachie83  Here is the PR for the issue you created for me.

**Comment by lachie83** [comment]
Thanks for taking care of this @nalthoff. Very much appreciated!

**Pull request merged**
