### PR TITLE
Kubernetes containerd support configurable ContainerdDownloadURLBase and kubernetesPodInfraContainerSpec 

### PR DESCRIPTION
**Pull request by karataliu**
**What this PR does / why we need it**:
1. Allow ContainerdDownloadURLBase to be configurable.
2. Make use of kubernetesPodInfraContainerSpec

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
#3583

**Special notes for your reviewer**:

**If applicable**:
- [ ] documentation
- [ ] unit tests
- [x] tested backward compatibility (ie. deploy with previous version, upgrade with this branch)

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
initial scan through code looks sane, running ad hoc containerd cluster E2E tests to validate

**Comment by karataliu** [comment]
@jackfrancis  @CecileRobertMichon  Could you please help trigger test rerun?

**Comment by karataliu** [comment]
ping

**Comment by jackfrancis** [comment]
tested out O.K., thanks for this!

**Pull request merged**
