### PR TITLE
increased VM size for e2e dcos deployments

### LINKED ISSUE #3080: DCOS e2e test is unreliable
The DCOS e2e tests fail frequently with this error:

```Azure Container Cluster using the DCOS Orchestrator regardless of agent pool type 
  should be able to install marathon
  /go/src/github.com/Azure/acs-engine/test/e2e/dcos/dcos_test.go:66

• Failure [8.101 seconds]
Azure Container Cluster using the DCOS Orchestrator
/go/src/github.com/Azure/acs-engine/test/e2e/dcos/dcos_test.go:45
  regardless of agent pool type
  /go/src/github.com/Azure/acs-engine/test/e2e/dcos/dcos_test.go:46
    should be able to install marathon [It]
    /go/src/github.com/Azure/acs-engine/test/e2e/dcos/dcos_test.go:66

    Expected error:
        <*ssh.ExitError | 0xc420264ec0>: {
            Waitmsg: {status: 1, signal: "", msg: "", lang: ""},
        }
        Process exited with status 1
    not to have occurred

    /go/src/github.com/Azure/acs-engine/test/e2e/dcos/dcos_test.go:68
------------------------------


Summarizing 1 Failure:

[Fail] Azure Container Cluster using the DCOS Orchestrator regardless of agent pool type [It] should be able to install marathon ```

### PR DESCRIPTION
**Pull request by dmitsh**
increased VM size for e2e DC/OS deployments

fixes #3080

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
Looks like the dcos test failed with:

```
2018/05/29 20:34:17 SSH Command: ssh -i /go/src/github.com/Azure/acs-engine/_output/dcos-southcentralus-59978-ssh -p 2200 azureuser@dcos-southcentralus-59978.southcentralus.cloudapp.azure.com
2018/05/29 20:34:21 Error while trying dcos cluster setup:Process exited with status 1
2018/05/29 20:34:21 Output:URL [http://localhost:80/pkgpanda/active.buildinfo.full.json] is unreachable.```

**Comment by dmitsh** [comment]
Yes, it seems that most of the failures happen in southcentralus region.
The failure is a network error when downloading the binary.
I will place dcos binary in CDN and update the link.

**Comment by CecileRobertMichon** [comment]
> 

Yes, it seems that most of the failures happen in southcentralus region. The failure is a network error when downloading the binary. I will place dcos binary in CDN and update the link.
--

In that case is it still necessary to increase the VM sizes?

**Comment by dmitsh** [comment]
Yes, it is recommended, as D2S_v3 is faster. We are using it for all our tests.

**Pull request merged**
