### PR TITLE
Fix cni cleanup during kubelet start to be graceful & not loose any logs

### PR DESCRIPTION
**Pull request by madhanrm**
**What this PR does / why we need it**:
* Save the CNI Logs
* Gracefully shutdown CNI instances & cleanup CNI json & locks if any

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**If applicable**:
- [ ] documentation
- [ ] unit tests
- [ ] tested backward compatibility (ie. deploy with previous version, upgrade with this branch)

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by madhanrm** [comment]
@sharmasushant @tamilmani1989

**Comment by madhanrm** [comment]
ping @jackfrancis @PatrickLang

**Comment by PatrickLang** [comment]
Is the intention here to handle node upgrades with the same script, and delete old data in case it changes? I wouldn't expect this script to generally be called more than once, so I'm not sure why we need to delete these

**Comment by PatrickLang** [comment]
Talked to @dineshgovindasamy on this. Looks good. Need to check test results before merge

**Comment by madhanrm** [comment]
@PatrickLang Do we have scenario for Upgrades here?

This is more to cover host restart or kubelet restart.

**Comment by PatrickLang** [comment]
No upgrade tests yet on Windows. On my backlog.

**Comment by PatrickLang** [comment]
rescheduled failed tests. they're unrelated to this change

**Pull request merged**
