### PR TITLE
Remove deprecated --reconcile-cidr, add explicit --storage-backend, bump addons-manager.

### PR DESCRIPTION
**Pull request by brendandburns**
@colemickens

### CODE REVIEW

**Comment by colemickens** [comment]
When do you think we need to move to `etcd3`, @brendandburns ?

**Comment by brendandburns** [comment]
@anhowe what is the best way to automatically update those files?

@colemickens we should bump to etcd3 when we roll to 1.6 (where it is the default)

**Comment by anhowe** [comment]
Run "go test" under the pkg/acsengine directory.  From there diff the expected vs. err files, and then diff each file, and mv .err file to expected file.

Also, ping me, and I can run this quickly.

**Comment by brendandburns** [comment]
@anhowe sure, go ahead and update the tests, thanks!

(I tried running, but I see lots of non-k8s diffs, so I must have some problem in my setup...)

**Comment by anhowe** [comment]
@brendandburns - test files are updated and merged

**Pull request merged**
