### PR TITLE
Enable DNS tests when windows nodes are present

### PR DESCRIPTION
**Pull request by jsturtevant**
**What this PR does / why we need it**:
Starts to improve the windows e2e tests for kubernetes from issue #3632.

This PR does the following:

- Include a linux agent node in the windows end to end tests. This will enable testing of other scenarios down the line such as testing dns works accross linux and windows pods.
- Enable DNS checks that are disabled during windows only tests.
- added stability to a windows File mount tests when it is run continuously (during dev work)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**If applicable**:
- [ ] documentation
- [ ] unit tests
- [ ] tested backward compatibility (ie. deploy with previous version, upgrade with this branch)

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by jsturtevant** [comment]
@PatrickLang could you do a review?

**Comment by PatrickLang** [comment]
/lgtm 
Thanks, especially for reenabling those other tests. That was on the backburner and I forgot about it.

**Comment by PatrickLang** [comment]
@jsturtevant can you rebase to fix the merge conflict?

**Comment by jsturtevant** [comment]
@PatrickLang fixed the merge conflict.  ready for review again

**Pull request merged**
