### PR TITLE
Stop kubelet before update and reboot faster

### PR DESCRIPTION
**Pull request by PatrickLang**
**What this PR does / why we need it**:

If you're creating a cluster as part of a test pass - the nodes appear to be ready before any patches are installed. This change will stop the kubelet so the node is not "ready", and also reboot faster. Once the reboot happens - the kubelet will be running and the testing can commence.

cc @adelina-t

### CODE REVIEW

**Comment by PatrickLang** [comment]
This was failing until #4119 & #4141 merged. Retesting now

**Comment by PatrickLang** [comment]
@adelina-t @dineshgovindasamy - I added the workaround to remove the Azure CNI lock after reboot. Can you review?

**Comment by PatrickLang** [comment]
/hold

The scheduled task still doesn't run after reboot. If you run `Get-ScheduledTask -TaskName "RemoveLock" | Start-ScheduledTask` it will complete, but it never starts automatically. Need to dig more into this.

**Comment by CecileRobertMichon** [comment]
@PatrickLang can you please move this to https://github.com/Azure/aks-engine?

**Pull request closed without merging**
