### PR TITLE
update to latest Ubuntu 16.04-LTS image

### PR DESCRIPTION
**Pull request by jackfrancis**
**What this PR does / why we need it**: Update to 16.04.201801050 image by default

**Release note**:

```
Ubuntu 16.04.201801050
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
@benkoller could you kindly check if there is a more recent version of Ubuntu 16.04-LTS in German cloud?

`az vm image list -p Canonical -f UbuntuServer -s 16.04-LTS --all` should work

**Comment by benkoller** [comment]
@jackfrancis The latest version is `16.04.201801050`. For reference, the full list of images (newest at the bottom):

```
[
  {
    "offer": "UbuntuServer",
    "publisher": "Canonical",
    "sku": "16.04-LTS",
    "urn": "Canonical:UbuntuServer:16.04-LTS:16.04.201701130",
    "version": "16.04.201701130"
  },
  {
    "offer": "UbuntuServer",
    "publisher": "Canonical",
    "sku": "16.04-LTS",
    "urn": "Canonical:UbuntuServer:16.04-LTS:16.04.201703300",
    "version": "16.04.201703300"
  },
  {
    "offer": "UbuntuServer",
    "publisher": "Canonical",
    "sku": "16.04-LTS",
    "urn": "Canonical:UbuntuServer:16.04-LTS:16.04.201706191",
    "version": "16.04.201706191"
  },
  {
    "offer": "UbuntuServer",
    "publisher": "Canonical",
    "sku": "16.04-LTS",
    "urn": "Canonical:UbuntuServer:16.04-LTS:16.04.201707270",
    "version": "16.04.201707270"
  },
  {
    "offer": "UbuntuServer",
    "publisher": "Canonical",
    "sku": "16.04-LTS",
    "urn": "Canonical:UbuntuServer:16.04-LTS:16.04.201708030",
    "version": "16.04.201708030"
  },
  {
    "offer": "UbuntuServer",
    "publisher": "Canonical",
    "sku": "16.04-LTS",
    "urn": "Canonical:UbuntuServer:16.04-LTS:16.04.201708110",
    "version": "16.04.201708110"
  },
  {
    "offer": "UbuntuServer",
    "publisher": "Canonical",
    "sku": "16.04-LTS",
    "urn": "Canonical:UbuntuServer:16.04-LTS:16.04.201708151",
    "version": "16.04.201708151"
  },
  {
    "offer": "UbuntuServer",
    "publisher": "Canonical",
    "sku": "16.04-LTS",
    "urn": "Canonical:UbuntuServer:16.04-LTS:16.04.201709190",
    "version": "16.04.201709190"
  },
  {
    "offer": "UbuntuServer",
    "publisher": "Canonical",
    "sku": "16.04-LTS",
    "urn": "Canonical:UbuntuServer:16.04-LTS:16.04.201710110",
    "version": "16.04.201710110"
  },
  {
    "offer": "UbuntuServer",
    "publisher": "Canonical",
    "sku": "16.04-LTS",
    "urn": "Canonical:UbuntuServer:16.04-LTS:16.04.201710261",
    "version": "16.04.201710261"
  },
  {
    "offer": "UbuntuServer",
    "publisher": "Canonical",
    "sku": "16.04-LTS",
    "urn": "Canonical:UbuntuServer:16.04-LTS:16.04.201711072",
    "version": "16.04.201711072"
  },
  {
    "offer": "UbuntuServer",
    "publisher": "Canonical",
    "sku": "16.04-LTS",
    "urn": "Canonical:UbuntuServer:16.04-LTS:16.04.201711160",
    "version": "16.04.201711160"
  },
  {
    "offer": "UbuntuServer",
    "publisher": "Canonical",
    "sku": "16.04-LTS",
    "urn": "Canonical:UbuntuServer:16.04-LTS:16.04.201711211",
    "version": "16.04.201711211"
  },
  {
    "offer": "UbuntuServer",
    "publisher": "Canonical",
    "sku": "16.04-LTS",
    "urn": "Canonical:UbuntuServer:16.04-LTS:16.04.201712080",
    "version": "16.04.201712080"
  },
  {
    "offer": "UbuntuServer",
    "publisher": "Canonical",
    "sku": "16.04-LTS",
    "urn": "Canonical:UbuntuServer:16.04-LTS:16.04.201801050",
    "version": "16.04.201801050"
  }
]
```

**Comment by jackfrancis** [comment]
@benkoller Thanks so much! Are you able to test this PR:

https://github.com/Azure/acs-engine/pull/2036

(if not, just a thumbs up and we can move that forward)

**Comment by benkoller** [comment]
Sorry, wont be able to test for a while

**Pull request merged**
