### PR TITLE
Version artifacts gathering in openshift e2e 

### PR DESCRIPTION
**Pull request by kargakis**
Builds on top of https://github.com/Azure/acs-engine/pull/2996

@jim-minter @mjudeikis @kwoodson @pweil-

### CODE REVIEW

**Comment by kargakis** [comment]
WIP until I actually test with 3.10

**Comment by kargakis** [comment]
openshift test flaked on the etcd timeout issue

**Comment by kargakis** [comment]
The code coverage context being red blocks tide from merging this PR fyi @CecileRobertMichon @jackfrancis

**Comment by CecileRobertMichon** [comment]
@kargakis I can change codecov config to not block below a certain threshold, it hasn't been a problem up to now since code coverage wasn't a required status check.

**Comment by kargakis** [comment]
Yeah, please do

**Comment by CecileRobertMichon** [comment]
@Kargakis #3115 is merged, if you rebase we can try getting acs-bot to merge this one (otherwise if I can just merge it manually, let me know)

**Comment by kargakis** [comment]
Rebased, I will babysit this PR until it gets merged, thanks!

**Comment by kargakis** [comment]
docs failure:
```
$ az group deployment create --name dcos-southeastasia-63351 --resource-group dcos-southeastasia-63351 --template-file /go/src/github.com/Azure/acs-engine/_output/dcos-southeastasia-63351/azuredeploy.json --parameters /go/src/github.com/Azure/acs-engine/_output/dcos-southeastasia-63351/azuredeploy.parameters.json
...............
$ timeout 60 az vm list -g dcos-southeastasia-63351

2018/05/31 17:29:08 SSH Key: /go/src/github.com/Azure/acs-engine/_output/dcos-southeastasia-63351-ssh
2018/05/31 17:29:08 Master Node: azureuser@dcos-southeastasia-63351.southeastasia.cloudapp.azure.com
2018/05/31 17:29:08 SSH Command: ssh -i /go/src/github.com/Azure/acs-engine/_output/dcos-southeastasia-63351-ssh -p 2200 azureuser@dcos-southeastasia-63351.southeastasia.cloudapp.azure.com
2018/05/31 17:29:13 Error while trying dcos cluster setup:Process exited with status 1
2018/05/31 17:29:13 Output:URL [http://localhost:80/pkgpanda/active.buildinfo.full.json] is unreachable.

2018/05/31 17:29:13 Circle?:true
2018/05/31 17:29:13 Jenkins?:false
2018/05/31 17:29:13 Point:test,branch=pull/3053,build_number=29314,ci=circleci,commit-sha=e98bd1405c3b456787ccb2e66114f49b5203934f,definition=examples/dcos.json,job=dcos-e2e,location=southeastasia,orchestrator=dcos,subscription_id=5684bae7-6a09-47a6-bdf1-695d1fd8ac1f node-wait-error-count=1,node-wait-secs=5.135910503,provision-error-count=0,provision-secs=915.512304025,test-error-count=0,test-secs=0,total-secs=920.651160986 1527787753413285965
2018/05/31 17:29:13 Deleting Group:dcos-southeastasia-63351

$ timeout 60 az group delete --name dcos-southeastasia-63351 --no-wait --yes
2018/05/31 17:29:18 Error while trying to provision cluster:Error trying to install dcos client:Process exited with status 1
exit status 1
test.mk:29: recipe for target 'test-dcos' failed
make: *** [test-dcos] Error 1
Exited with code 2
```
restarting

**Comment by CecileRobertMichon** [comment]
@kargakis the DCOS test has been flaky lately https://github.com/Azure/acs-engine/issues/3080, apologies for the inconvenience. We might want to reopen that issue.

**Comment by kargakis** [comment]
k8s-windows-1.8-release-e2e failure:
```
$ az group deployment create --name kubernetes-southcentralus-54245 --resource-group kubernetes-southcentralus-54245 --template-file /go/src/github.com/Azure/acs-engine/_output/kubernetes-southcentralus-54245/azuredeploy.json --parameters /go/src/github.com/Azure/acs-engine/_output/kubernetes-southcentralus-54245/azuredeploy.parameters.json
.............................................................2018/05/31 17:55:20 
Error from deployment for kubernetes-southcentralus-54245 in resource group kubernetes-southcentralus-54245:exit status 1
2018/05/31 17:55:20 Command Output: ERROR: Deployment failed. Correlation ID: 6cd045a0-828d-4f50-b899-15001f175c99. {

  "status": "Failed",

  "error": {

    "code": "ResourceDeploymentFailure",

    "message": "The resource operation completed with terminal provisioning state 'Failed'.",

    "details": [

      {

        "code": "OSProvisioningTimedOut",

        "message": "OS Provisioning for VM '38681k8s9000' did not finish in the allotted time. The VM may still finish provisioning successfully. Please check provisioning state later."

      }

    ]

  }

}
```
restarting

**Comment by kargakis** [comment]
This probably needs a github approval on top of the github labels in order to get automatically merged (seems github approvals are required to enable merging PRs in this repo).

**Comment by CecileRobertMichon** [comment]
This isn't auto-merging because of tide cert errors, merging now.

**Pull request merged**
