### PR TITLE
Hybrid Swarm Mode

### PR DESCRIPTION
**Pull request by radu-matei**
**What this PR does / why we need it**:
Adds a `swarmmode-hybrid.json` cluster definition, with documentation for a hybrid Swarm Mode cluster with Linux masters and Linux and Windows agents.

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/891)

### CODE REVIEW

**Comment by anhowe** [comment]
@radu-matei thanks for the documentation, but Swarm-Mode does not support windows: https://github.com/Azure/acs-engine/blob/master/pkg/api/vlabs/validate.go#L288.

**Comment by radu-matei** [comment]
It actually deploys the Windows agents and joins them in the Swarm
https://github.com/Azure/acs-engine/blob/dd2edf94e182dd9006ddf3fa8f8388b4e5a1eed5/parts/Install-ContainerHost-And-Join-Swarm.ps1

**Comment by radu-matei** [comment]
Any update on this topic?

**Comment by shrutir25** [comment]
@JiangtianLi - could you review this PR ?

**Comment by JiangtianLi** [comment]
In api model 2017-01-31 swarmmode doesn't support Windows. @amanohar Do you have context when and why Windows agent was enabled for vlabs in swarmmode?

**Comment by jchauncey** [comment]
Whats the status on this?

**Comment by jackfrancis** [comment]
@radu-matei I managed to get this working with our E2E runner with some tweaks to the api model. See PR #1456, which I based on your fork. This change is now in master, thanks so much!

**Comment by radu-matei** [comment]
That is great to hear!
Thanks!

**Pull request closed without merging**
