### PR TITLE
Fixed templates issue

### PR DESCRIPTION
**Pull request by shrutir25**
Reference to Issue #352

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/518)

### CODE REVIEW

**Comment by shrutir25** [comment]
@acs-bot test this please

**Comment by shrutir25** [comment]
@JackQuincy could you take a look

**Comment by JackQuincy** [comment]
@acs-bot test this please

**Comment by JackQuincy** [comment]
LGTM just going to wait on @acs-bot  to finish before signing off.

**Comment by JackQuincy** [comment]
@acs-bot  test this please

**Comment by JackQuincy** [comment]
was strange acs-bot appeared to have ran the tests and they all passed but acs bot didn't realize they had ran/finished. Will try again

**Comment by JackQuincy** [comment]
@acs-bot test this please

**Comment by JackQuincy** [comment]
I'm suprised this merged as cole made changes to templates.go. Shruti can you pull down latest and merge with coles changes? I'm thinking we will run into issues in the merge, should be trivial to regenerate, but we should do that before we merge.

**Comment by JackQuincy** [comment]
@acs-bot test this please

**Comment by JackQuincy** [comment]
@acs-bot test this please

**Comment by JackQuincy** [comment]
@acs-bot test this please

**Comment by JackQuincy** [comment]
I can't tell if the test failures are caused by this review or if it is flakiness. It appears to be flakiness but I'm not sure.

**Pull request merged**
