### PR TITLE
Cluster Key Vault

### PR DESCRIPTION
**Pull request by khenidak**
**What this PR does / why we need it**:
Creates a Keyvault per cluster. This key vault will hold the key used to encrypt etcd secrets as part of the upstream work we are doing. 

**Which issue this PR fixes**
None

**Special notes for your reviewer**:
*When the cluster is non-MSI*
User provided service principal will have create, encrypt and decrypt permission on keys of that said vault.
*When the cluster is MSI*
No permission is added, the cloud provider will add permission to node's service principal as it starts. 

The keyvault is always created, User have control on vault SKU via a template parameter.
The key vault name is part of /etc/kubernets/azure.json generated by the bootstrap script
@jdumars @slack 

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/1115)

### CODE REVIEW

**Comment by seanknox** [comment]
@khenidak Thanks Kal! Can you open an issue describing the scope of work in a bit more detail? We also use issues to track for our backlog.

**Comment by seanknox** [comment]
@acs-bot test this please

**Comment by khenidak** [comment]
@seanknox you mean like this https://github.com/Azure/acs-engine/issues/1116 ?

**Comment by khenidak** [comment]
@brendanburns looks like i need read permission on Jenkins to be able to see the reports..

**Comment by khenidak** [comment]
@seanknox  how can i get read on Jenkins?

**Comment by weinong** [comment]
@khenidak looks like all tests related to k8s failed.
@anhowe this change will block RP until RP has write access to KV.

**Comment by seanknox** [comment]
@khenidak you should have CI permission now. builds should trigger automatically on new commits from now on.

**Comment by khenidak** [comment]
Please hold merge until this is finalized https://github.com/kubernetes/kubernetes/pull/48574

**Comment by khenidak** [comment]
this PR depends upstream work (which depends on Azure SDK), We are depending on a resolution for this https://github.com/Azure/azure-sdk-for-go/issues/764

**Pull request closed without merging**
