### PR TITLE
[WIP] add EMSI support

### LINKED ISSUE #2324: [Feature] support authentication through EMSI
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Feature
---

**What version of acs-engine?**:
until now
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
Azure Identity team had a new feature called explicit MSI (EMSI)
I have an upstream PR (https://github.com/kubernetes/kubernetes/pull/60253) to support it.

**What you expected to happen**:
acs-engine need to wire things up, and support this new feature :)

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by rjtsdl**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2324

**Special notes for your reviewer**:
I just send this out first, want to make sure my change didn't break any existing feature with 
EnableUserAssignedID to be false/omit

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
Thanks @rjtsdl! Could you make the config flag a `*bool` so that we can infer more about user intent, e.g.:

- nil = user did not express an opinion (assign default)
- *true = user explicitly says yes
- *false = user explicitly says no

You can see other examples of the above implementation in `KubernetesConfig` type spec

**Comment by rjtsdl** [comment]
@jackfrancis sounds good, will do :)

**Comment by jackfrancis** [comment]
@rjtsdl Is this ready for review?

**Comment by jackfrancis** [comment]
Sorry, nevermind, I see the `*bool` stuff still isn't there :)

**Comment by rjtsdl** [comment]
@jackfrancis not yet, i haven't get an E2E scenario working yet.  And EMSI is still a private preview. We will plan to start merging once it is public preview. 

Same for the upstream change :)

**Pull request closed without merging**
