### PR TITLE
Kubernetes GPU: ensure nvidia drivers install after docker is installed

### PR DESCRIPTION
**Pull request by jackfrancis**
**What this PR does / why we need it**: Two changes after debuggin that restore consistent GPU-enabled cluster deployments:

- ensure that nvidia installation happens after docker install (nvidia driver has a dockder dependency)
- lazy umount

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**If applicable**:
- [ ] documentation
- [ ] unit tests
- [ ] tested backward compatibility (ie. deploy with previous version, upgrade with this branch)

**Release note**:

```
Kubernetes GPU: ensure nvidia drivers install after docker is installed
```

### CODE REVIEW

**Comment by sozercan** [comment]
seems like something is preventing `/usr/lib/x86_64-linux-gnu` from being unmounted which causes `ldconfig` fails after that.

```
sudo umount /usr/lib/x86_64-linux-gnu
umount: /usr/lib/x86_64-linux-gnu: target is busy
```

**Comment by jackfrancis** [comment]
@sozercan should we retry that umount operation to account for "locks" on the umount target?

**Comment by sozercan** [comment]
@jackfrancis i don't think its a time issue, something is blocking unmount operation

**Comment by jackfrancis** [comment]
Are the effects of this failure concrete/known? What is non-functional so long as this umount + ldconfig errata persists?

@wbuchwalter any thoughts?

**Comment by jackfrancis** [comment]
Also, @wbuchwalter if you have any working 1.10-vintage GPU clusters available, I'd love to see the stdout logs of the nvidia install under `/var/log/cloud-init-output.log` on one of the agent nodes.

What we're seeing now is that both `ldconfig` statements fail, as well as the `umount` statement:

```
+ sudo ldconfig
/sbin/ldconfig.real: Cannot lstat /usr/lib/x86_64-linux-gnu/tls: No such file or directory
/sbin/ldconfig.real: Cannot lstat /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0: No such file or directory
+ umount /usr/lib/x86_64-linux-gnu
umount: /usr/lib/x86_64-linux-gnu: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
```

and 

```
+ sudo ldconfig
/sbin/ldconfig.real: Cannot lstat /usr/lib/x86_64-linux-gnu/tls: No such file or directory
/sbin/ldconfig.real: Cannot lstat /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0: No such file or directory
```

Driver installation works, but we're now getting inconsistent results trying to schedule GPU workloads against these newly built clusters.

**Comment by wbuchwalter** [comment]
@jackfrancis I have a 1.10.5 cluster deployed about 10 days ago with GPUs.
`sudo ldconfig` appears to have succeeded on all nodes and I haven't noticed any scheduling issues for GPU workloads.
```
+-----------------------------------------------------------------------------+
+ sudo ldconfig
+ retrycmd_if_failure 5 10 60 systemctl restart kubelet
+ retries=5
+ wait_sleep=10
+ timeout=60
+ shift
+ shift
+ shift
+ seq 1 5
+ timeout 60 systemctl restart kubelet
+ [ 0 -eq 0 ]
+ break
+ echo Executed "systemctl restart kubelet" 1 times
Executed "systemctl restart kubelet" 1 times
```

**Pull request merged**
