### PR TITLE
[DC/OS] Set 1.9 as default DCOS version and upgrade Packages

### PR DESCRIPTION
**Pull request by wbuchwalter**
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/457)

### CODE REVIEW

**Comment by wbuchwalter** [comment]
@anhowe Is there any way to quickly regenerate the expected template and params for the tests? Since 1.9 is now the default version all the test files not tied to a specific version needs to be upgraded, do I have to regenerate them one by one?

**Comment by wbuchwalter** [comment]
All tests should now be updated correctly.
PR is ready to be reviewed.

**Comment by JackQuincy** [comment]
@acs-bot test this please

**Comment by JackQuincy** [comment]
Our CI/CD pipeline is trying to deploy a cluster and it is still deploying 40ish minutes later. The custom script to bring the masters up is taking >40 mins right now. Did you have a successful test with the updated bootstrap urls?

**Comment by wbuchwalter** [comment]
@JackQuincy Should be fixed now, it deploys successfully on my side.

@acs-bot test this please

**Comment by JackQuincy** [comment]
@acs-bot test this please

**Comment by JackQuincy** [comment]
@wbuchwalter looks like the templates.go is out of date can you regenerate in a go1.8 install and push an update? Easiest way is to use the devenv scripts in the repo to set up development environment container.

**Comment by JackQuincy** [comment]
@acs-bot test this please

**Comment by JackQuincy** [comment]
@acs-bot test this please

**Pull request merged**
