### PR TITLE
Unit test standalone agent pool scenario and misc agent pool only fixes

### PR DESCRIPTION
**Pull request by amanohar**
**What this PR does / why we need it**:
1) ACS Engine enabled creation of standalone agent pools: https://github.com/Azure/acs-engine/pull/1290. The template generation code path is shared by both full cluster creation scenario and agent pool only scenario. The unit test in this PR validates that agent pool only scenario template is a syntactically correct JSON.
2) Fix typo in subnet mask
3) Convert AccessProfiles to be a map instead of an array

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/1305)

### CODE REVIEW

**Comment by jchauncey** [comment]
How is the location set for these tests?

**Comment by seanknox** [comment]
@jchauncey via `test/e2e/kubernetes-deployments.json`:

```json
{
	"deployments": [
		{
			"cluster_definition": "windows/kubernetes-hybrid.json",
			"location": "eastus"
		},
		{
			"cluster_definition": "windows/kubernetes.json",
			"location": "eastus"
		},
		{
			"cluster_definition": "disks-managed/kubernetes-preAttachedDisks-vmas.json",
			"location": "eastus"
		},
		{
			"cluster_definition": "disks-managed/kubernetes-vmas.json",
			"location": "eastus"
		},
		{
			"cluster_definition": "disks-storageaccount/kubernetes.json",
			"location": "westcentralus"
		},
		{
			"cluster_definition": "kubernetes-releases/kubernetes1.5.json",
			"location": "southcentralus"
		},
		{
			"cluster_definition": "networkpolicy/kubernetes-calico.json",
			"location": "southcentralus"
		},
		{
			"cluster_definition": "custom-pod-cidr/kubernetes.json",
			"location": "southcentralus"
		},
		{
			"cluster_definition": "vnet/kubernetesvnet.json",
			"location": "southcentralus"
		}
	]
}
```

e2e tests appear to be failing due to regional Azure slowness:
```
ERROR: Deployment failed. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "OSProvisioningTimedOut",
        "message": "OS Provisioning for VM '27443acs9010' did not finish in the allotted time. The VM may still finish provisioning successfully. Please check provisioning state later."
      }
    ]
  }
}
```

**Comment by jchauncey** [comment]
ah yeah forgot about that json

**Comment by amanohar** [comment]
@seanknox fixed the subnet mask
@slack please sign off again.

**Pull request merged**
