### PR TITLE
Revert "Fixes #116. Naming container when starting"

### LINKED ISSUE #116: [kubernetes] systemctl stop kubelet.service
Unable to stop kubelet.service via systemctl on k8s master node.

```
> systemctl stop kubelet.service
> systemctl status kubelet.service
Nov 22 01:29:19 k8s-master-1479775666-0 systemd[1]: Stopping Kubelet...
Nov 22 01:29:19 k8s-master-1479775666-0 docker[26894]: Error response from daemon: No such container: kubelet

```

Should be a fairly easy fix if you name the docker image when starting:
https://github.com/Azure/acs-engine/blob/master/parts/kubernetesmastercustomdata.yml#L323

### PR DESCRIPTION
**Pull request by colemickens**
Reverts Azure/acs-engine#121

### CODE REVIEW

**Comment by colemickens** [comment]
cc: @raveeram please review and merge asap.

**Comment by colemickens** [comment]
We need to revert this as it has a syntax error and broke Kubernetes.

**Comment by jpoon** [comment]
Thanks @colemickens. Sorry for breaking things :(

**Comment by colemickens** [comment]
No worries, we caught it quickly. I'm working on CI/CD that will prevent this even making it in in the future.

**Pull request merged**
