### PR TITLE
Heapster Service missing from addon and is breaking dashboard charts

### LINKED ISSUE #3124: Heapster Service missing from addon is breaking dashboard charts
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**: v0.17.1

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**: Kubernetes

---

**What happened**: When using the dashboard, no charts are appearing for any of the nodes/pods.

---

**What you expected to happen**: Charts to appear in dashboard

---

**How to reproduce it** (as minimally and precisely as possible): Deploy heapster and dashboard addons. Navigate to dashboards and no charts appear.

---

**Anything else we need to know**:

The dashboard addon is configured to point at http://heapster.kube-system:80 for metrics, but the heapster addon does not define a Service, so the DNS lookup fails. The dashboard cant find heapster and so it hides the charts. Manually adding the Service back to the heapster addon fixes the problem.

This may be related to #3113

### PR DESCRIPTION
**Pull request by ewok2030**
**What this PR does / why we need it**: Dashboard charts not working without it

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3124 and maybe #3113

**Special notes for your reviewer**:

**If applicable**:
- [ ] documentation
- [ ] unit tests
- [ ] tested backward compatibility (ie. deploy with previous version, upgrade with this branch)

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
Thanks @ewok2030! Was this only recently noticed <just because>? Or is this actually a regression?

**Comment by ewok2030** [comment]
It’s included in the previous k8s version addons, but it looks like it got accidentally removed during some recent maintenance. 

It wouldn’t have raised any errors during testing because the dashboard just assumes healster is not available and hides the charts.

**Comment by ewok2030** [comment]
@jackfrancis Yes, this is only an issue in 1.9+. The Service object is present in the 1.6/1.7/1.8 addons - it just looks like it got dropped by mistake in #2753.

**Comment by jackfrancis** [comment]
Thanks for confirming @ewok2030!

/approve
/lgtm

**Pull request merged**
