### PR TITLE
[WIP] metrics-server 0.3.1 for k8s 1.12, deprecate heapster

### PR DESCRIPTION
**Pull request by jackfrancis**
**What this PR does / why we need it**: Needs a working HPA story to go with it.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**If applicable**:
- [ ] documentation
- [ ] unit tests
- [ ] tested backward compatibility (ie. deploy with previous version, upgrade with this branch)

**Release note**:

```
metrics-server 0.3.1 for k8s 1.12
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
@andyzhangx @feiskyer if you have any guidance on an HPA story for a non-heapster-enabled cluster (like 1.12 should be), that would be 👍

**Comment by feiskyer** [comment]
@jackfrancis It's safe to use metrics-server for HPA. Actually, heapster setup scripts have been removed in kubernetes 1.12.

**Comment by jackfrancis** [comment]
@feiskyer Thanks, there must be something else missing in the 0.3.1 metrics-server implementation, as this PR doesn't currently work for HPA. (I am assuming that the previous HPA commands work)

**Comment by feiskyer** [comment]
> Thanks, there must be something else missing in the 0.3.1 metrics-server implementation, as this PR doesn't currently work for HPA.

What problems have you found?

**Pull request closed without merging**
